export declare const flagSet: {
  "cifAE": string[];
  "cifAG": string[];
  "cifAM": string[];
  "cifAO": string[];
  "cifAT": string[];
  "cifAU": string[];
  "cifAZ": string[];
  "cifBA": string[];
  "cifBB": string[];
  "cifBD": string[];
  "cifBE": string[];
  "cifBF": string[];
  "cifBG": string[];
  "cifBH": string[];
  "cifBI": string[];
  "cifBJ": string[];
  "cifBO": string[];
  "cifBS": string[];
  "cifBW": string[];
  "cifCA": string[];
  "cifCD": string[];
  "cifCF": string[];
  "cifCG": string[];
  "cifCH": string[];
  "cifCI": string[];
  "cifCL": string[];
  "cifCM": string[];
  "cifCR": string[];
  "cifCO": string[];
  "cifCN": string[];
  "cifCU": string[];
  "cifCV": string[];
  "cifCZ": string[];
  "cifDE": string[];
  "cifDJ": string[];
  "cifDK": string[];
  "cifDZ": string[];
  "cifEE": string[];
  "cifER": string[];
  "cifET": string[];
  "cifFI": string[];
  "cifFM": string[];
  "cifFR": string[];
  "cifGA": string[];
  "cifGB": string[];
  "cifGD": string[];
  "cifGE": string[];
  "cifGH": string[];
  "cifGM": string[];
  "cifGR": string[];
  "cifGW": string[];
  "cifGY": string[];
  "cifHK": string[];
  "cifHN": string[];
  "cifHU": string[];
  "cifID": string[];
  "cifIE": string[];
  "cifIL": string[];
  "cifIN": string[];
  "cifIQ": string[];
  "cifIR": string[];
  "cifIS": string[];
  "cifIT": string[];
  "cifJM": string[];
  "cifJO": string[];
  "cifJP": string[];
  "cifKE": string[];
  "cifKI": string[];
  "cifKM": string[];
  "cifKN": string[];
  "cifKP": string[];
  "cifKR": string[];
  "cifKW": string[];
  "cifLA": string[];
  "cifLC": string[];
  "cifLR": string[];
  "cifLS": string[];
  "cifLT": string[];
  "cifLU": string[];
  "cifLV": string[];
  "cifLY": string[];
  "cifMA": string[];
  "cifMC": string[];
  "cifMG": string[];
  "cifMH": string[];
  "cifMK": string[];
  "cifML": string[];
  "cifMM": string[];
  "cifMN": string[];
  "cifMR": string[];
  "cifMU": string[];
  "cifMV": string[];
  "cifMW": string[];
  "cifMY": string[];
  "cifMZ": string[];
  "cifNA": string[];
  "cifNE": string[];
  "cifNG": string[];
  "cifNL": string[];
  "cifNO": string[];
  "cifNP": string[];
  "cifNR": string[];
  "cifNU": string[];
  "cifNZ": string[];
  "cifPA": string[];
  "cifPE": string[];
  "cifPG": string[];
  "cifPH": string[];
  "cifPK": string[];
  "cifPL": string[];
  "cifPW": string[];
  "cifQA": string[];
  "cifRO": string[];
  "cifRU": string[];
  "cifRW": string[];
  "cifSB": string[];
  "cifSC": string[];
  "cifSD": string[];
  "cifSE": string[];
  "cifSG": string[];
  "cifSI": string[];
  "cifSK": string[];
  "cifSL": string[];
  "cifSN": string[];
  "cifSO": string[];
  "cifSR": string[];
  "cifSS": string[];
  "cifST": string[];
  "cifSY": string[];
  "cifTD": string[];
  "cifSZ": string[];
  "cifTG": string[];
  "cifTH": string[];
  "cifTJ": string[];
  "cifTL": string[];
  "cifTN": string[];
  "cifTO": string[];
  "cifTR": string[];
  "cifTT": string[];
  "cifTV": string[];
  "cifTW": string[];
  "cifTZ": string[];
  "cifUA": string[];
  "cifUG": string[];
  "cifUS": string[];
  "cifUY": string[];
  "cifUZ": string[];
  "cifVC": string[];
  "cifVE": string[];
  "cifVN": string[];
  "cifWS": string[];
  "cifXK": string[];
  "cifYE": string[];
  "cifZM": string[];
  "cifZW": string[];
  "cifZA": string[];
  "cifAL": string[];
  "cifAR": string[];
  "cifBR": string[];
  "cifBY": string[];
  "cifCY": string[];
  "cifDM": string[];
  "cifGN": string[];
  "cifGQ": string[];
  "cifKG": string[];
  "cifLB": string[];
  "cifMT": string[];
  "cifKH": string[];
  "cifLI": string[];
  "cifNI": string[];
  "cifOM": string[];
  "cifSA": string[];
}
export declare const cifAE: string[];
export declare const cifAG: string[];
export declare const cifAM: string[];
export declare const cifAO: string[];
export declare const cifAT: string[];
export declare const cifAU: string[];
export declare const cifAZ: string[];
export declare const cifBA: string[];
export declare const cifBB: string[];
export declare const cifBD: string[];
export declare const cifBE: string[];
export declare const cifBF: string[];
export declare const cifBG: string[];
export declare const cifBH: string[];
export declare const cifBI: string[];
export declare const cifBJ: string[];
export declare const cifBO: string[];
export declare const cifBS: string[];
export declare const cifBW: string[];
export declare const cifCA: string[];
export declare const cifCD: string[];
export declare const cifCF: string[];
export declare const cifCG: string[];
export declare const cifCH: string[];
export declare const cifCI: string[];
export declare const cifCL: string[];
export declare const cifCM: string[];
export declare const cifCR: string[];
export declare const cifCO: string[];
export declare const cifCN: string[];
export declare const cifCU: string[];
export declare const cifCV: string[];
export declare const cifCZ: string[];
export declare const cifDE: string[];
export declare const cifDJ: string[];
export declare const cifDK: string[];
export declare const cifDZ: string[];
export declare const cifEE: string[];
export declare const cifER: string[];
export declare const cifET: string[];
export declare const cifFI: string[];
export declare const cifFM: string[];
export declare const cifFR: string[];
export declare const cifGA: string[];
export declare const cifGB: string[];
export declare const cifGD: string[];
export declare const cifGE: string[];
export declare const cifGH: string[];
export declare const cifGM: string[];
export declare const cifGR: string[];
export declare const cifGW: string[];
export declare const cifGY: string[];
export declare const cifHK: string[];
export declare const cifHN: string[];
export declare const cifHU: string[];
export declare const cifID: string[];
export declare const cifIE: string[];
export declare const cifIL: string[];
export declare const cifIN: string[];
export declare const cifIQ: string[];
export declare const cifIR: string[];
export declare const cifIS: string[];
export declare const cifIT: string[];
export declare const cifJM: string[];
export declare const cifJO: string[];
export declare const cifJP: string[];
export declare const cifKE: string[];
export declare const cifKI: string[];
export declare const cifKM: string[];
export declare const cifKN: string[];
export declare const cifKP: string[];
export declare const cifKR: string[];
export declare const cifKW: string[];
export declare const cifLA: string[];
export declare const cifLC: string[];
export declare const cifLR: string[];
export declare const cifLS: string[];
export declare const cifLT: string[];
export declare const cifLU: string[];
export declare const cifLV: string[];
export declare const cifLY: string[];
export declare const cifMA: string[];
export declare const cifMC: string[];
export declare const cifMG: string[];
export declare const cifMH: string[];
export declare const cifMK: string[];
export declare const cifML: string[];
export declare const cifMM: string[];
export declare const cifMN: string[];
export declare const cifMR: string[];
export declare const cifMU: string[];
export declare const cifMV: string[];
export declare const cifMW: string[];
export declare const cifMY: string[];
export declare const cifMZ: string[];
export declare const cifNA: string[];
export declare const cifNE: string[];
export declare const cifNG: string[];
export declare const cifNL: string[];
export declare const cifNO: string[];
export declare const cifNP: string[];
export declare const cifNR: string[];
export declare const cifNU: string[];
export declare const cifNZ: string[];
export declare const cifPA: string[];
export declare const cifPE: string[];
export declare const cifPG: string[];
export declare const cifPH: string[];
export declare const cifPK: string[];
export declare const cifPL: string[];
export declare const cifPW: string[];
export declare const cifQA: string[];
export declare const cifRO: string[];
export declare const cifRU: string[];
export declare const cifRW: string[];
export declare const cifSB: string[];
export declare const cifSC: string[];
export declare const cifSD: string[];
export declare const cifSE: string[];
export declare const cifSG: string[];
export declare const cifSI: string[];
export declare const cifSK: string[];
export declare const cifSL: string[];
export declare const cifSN: string[];
export declare const cifSO: string[];
export declare const cifSR: string[];
export declare const cifSS: string[];
export declare const cifST: string[];
export declare const cifSY: string[];
export declare const cifTD: string[];
export declare const cifSZ: string[];
export declare const cifTG: string[];
export declare const cifTH: string[];
export declare const cifTJ: string[];
export declare const cifTL: string[];
export declare const cifTN: string[];
export declare const cifTO: string[];
export declare const cifTR: string[];
export declare const cifTT: string[];
export declare const cifTV: string[];
export declare const cifTW: string[];
export declare const cifTZ: string[];
export declare const cifUA: string[];
export declare const cifUG: string[];
export declare const cifUS: string[];
export declare const cifUY: string[];
export declare const cifUZ: string[];
export declare const cifVC: string[];
export declare const cifVE: string[];
export declare const cifVN: string[];
export declare const cifWS: string[];
export declare const cifXK: string[];
export declare const cifYE: string[];
export declare const cifZM: string[];
export declare const cifZW: string[];
export declare const cifZA: string[];
export declare const cifAL: string[];
export declare const cifAR: string[];
export declare const cifBR: string[];
export declare const cifBY: string[];
export declare const cifCY: string[];
export declare const cifDM: string[];
export declare const cifGN: string[];
export declare const cifGQ: string[];
export declare const cifKG: string[];
export declare const cifLB: string[];
export declare const cifMT: string[];
export declare const cifKH: string[];
export declare const cifLI: string[];
export declare const cifNI: string[];
export declare const cifOM: string[];
export declare const cifSA: string[];