export declare const linearSet: {
  "cil3d": string[];
  "cil3dRotate": string[];
  "cil4k": string[];
  "cilAccessibility": string[];
  "cilAccessible": string[];
  "cilAccountLogout": string[];
  "cilActionRedo": string[];
  "cilActionUndo": string[];
  "cilAddressBook": string[];
  "cilAddressCard": string[];
  "cilAirplaneModeOff": string[];
  "cilAirplaneMode": string[];
  "cilAirplay": string[];
  "cilAlarmAdd": string[];
  "cilAlarmOff": string[];
  "cilAlarmOn": string[];
  "cilAlarmSnooze": string[];
  "cilAlarm": string[];
  "cilAlbum": string[];
  "cilAlignCenter": string[];
  "cilAlignLeft": string[];
  "cilAlignRight": string[];
  "cilAmericanFootball": string[];
  "cilAnimal": string[];
  "cilAperture": string[];
  "cilApple": string[];
  "cilApplicationsSettings": string[];
  "cilApplications": string[];
  "cilAppsSettings": string[];
  "cilApps": string[];
  "cilArchive": string[];
  "cilArrowBottom": string[];
  "cilArrowCircleBottom": string[];
  "cilArrowCircleLeft": string[];
  "cilArrowCircleRight": string[];
  "cilArrowCircleTop": string[];
  "cilArrowLeft": string[];
  "cilArrowRight": string[];
  "cilArrowThickBottom": string[];
  "cilArrowThickCircleDown": string[];
  "cilArrowThickCircleLeft": string[];
  "cilArrowThickCircleRight": string[];
  "cilArrowThickCircleUp": string[];
  "cilArrowThickFromBottom": string[];
  "cilArrowThickFromRight": string[];
  "cilArrowThickFromTop": string[];
  "cilArrowThickLeft": string[];
  "cilArrowThickRight": string[];
  "cilArrowThickSquareDown": string[];
  "cilArrowThickSquareLeft": string[];
  "cilArrowThickSquareRight": string[];
  "cilArrowThickSquareUp": string[];
  "cilArrowThickToBottom": string[];
  "cilArrowThickToLeft": string[];
  "cilArrowThickToRight": string[];
  "cilArrowThickToTop": string[];
  "cilArrowThickTop": string[];
  "cilArrowTop": string[];
  "cilArtTrack": string[];
  "cilAssistiveListeningSystem": string[];
  "cilAsteriskCircle": string[];
  "cilAsterisk": string[];
  "cilAt": string[];
  "cilAudioDescription": string[];
  "cilAudioSpectrum": string[];
  "cilAudio": string[];
  "cilAvTimer": string[];
  "cilBabyCarriage": string[];
  "cilBaby": string[];
  "cilBackspace": string[];
  "cilBadge": string[];
  "cilBalanceScaleLeft": string[];
  "cilBalanceScaleRight": string[];
  "cilBalanceScale": string[];
  "cilBan": string[];
  "cilBank": string[];
  "cilBarChart": string[];
  "cilBarcode": string[];
  "cilBaseball": string[];
  "cilBasketArrowDown": string[];
  "cilBasketLoaded": string[];
  "cilBasketPlus": string[];
  "cilBasket": string[];
  "cilBasketball": string[];
  "cilBath": string[];
  "cilBathroom": string[];
  "cilBattery0": string[];
  "cilBattery1": string[];
  "cilBattery2": string[];
  "cilBattery3": string[];
  "cilBattery4": string[];
  "cilBattery5": string[];
  "cilBatteryAlert": string[];
  "cilBatteryAlt0": string[];
  "cilBatteryAlt1": string[];
  "cilBatteryAlt2": string[];
  "cilBatteryAlt3": string[];
  "cilBatteryAltEmpty": string[];
  "cilBatteryAltFull": string[];
  "cilBatteryAltSlash": string[];
  "cilBatteryCharge": string[];
  "cilBatteryEmpty": string[];
  "cilBatteryFull": string[];
  "cilBatterySlash": string[];
  "cilBatteryUnknown": string[];
  "cilBeachAccess": string[];
  "cilArrowThickFromLeft": string[];
  "cilBeaker": string[];
  "cilBed": string[];
  "cilBellExclamation": string[];
  "cilBellPlus": string[];
  "cilBellRing": string[];
  "cilBellSlash": string[];
  "cilBell": string[];
  "cilBikeAlt": string[];
  "cilBike": string[];
  "cilBlind": string[];
  "cilBirthdayCake": string[];
  "cilBluetoothConnected": string[];
  "cilBluetoothSettings": string[];
  "cilBluetoothSearching": string[];
  "cilBluetoothSlash": string[];
  "cilBluetooth": string[];
  "cilBlurCircular": string[];
  "cilBlurLinear": string[];
  "cilBlurSlash": string[];
  "cilBlur": string[];
  "cilBoatAlt": string[];
  "cilBoat": string[];
  "cilBold": string[];
  "cilBoltAlt": string[];
  "cilBoltCircle": string[];
  "cilBolt": string[];
  "cilBookOpen": string[];
  "cilBook": string[];
  "cilBookmark": string[];
  "cilBookmarks": string[];
  "cilBorderAll": string[];
  "cilBorderBottom": string[];
  "cilBorderClear": string[];
  "cilBorderHorizontal": string[];
  "cilBorderInner": string[];
  "cilBorderLeft": string[];
  "cilBorderOuter": string[];
  "cilBorderRight": string[];
  "cilBorderStyle": string[];
  "cilBorderTop": string[];
  "cilBorderVertical": string[];
  "cilBowlingPins": string[];
  "cilBowling": string[];
  "cilBox": string[];
  "cilBraille": string[];
  "cilBrandingWatermark": string[];
  "cilBriefcaseArrowLeft": string[];
  "cilBriefcaseArrowRight": string[];
  "cilBriefcaseSlash": string[];
  "cilBriefcase": string[];
  "cilBrightnessAuto": string[];
  "cilBrightnessHigh": string[];
  "cilBrightnessLow": string[];
  "cilBrightnessMedium": string[];
  "cilBrightness": string[];
  "cilBritishPoundCircle": string[];
  "cilBritishPoundSlash": string[];
  "cilBroadcastTower": string[];
  "cilBritishPound": string[];
  "cilBrush": string[];
  "cilBrowser": string[];
  "cilBug": string[];
  "cilBuildingBusinessSlash": string[];
  "cilBuildingBusiness": string[];
  "cilBuildingSlash": string[];
  "cilBuilding": string[];
  "cilBurger": string[];
  "cilBusAlt": string[];
  "cilBullhorn": string[];
  "cilBusTimer": string[];
  "cilBus": string[];
  "cilCalculator": string[];
  "cilCalendarCheck": string[];
  "cilCalendarEvent": string[];
  "cilCalendarAlt": string[];
  "cilCalendarNote": string[];
  "cilCalendarMinus": string[];
  "cilCalendarTimes": string[];
  "cilCalendarPlus": string[];
  "cilBrushAlt": string[];
  "cilCalendarToday": string[];
  "cilCalendarViewDay": string[];
  "cilCalendar": string[];
  "cilCallMade": string[];
  "cilCallMerge": string[];
  "cilCallMissedOutgoing": string[];
  "cilCallMissed": string[];
  "cilCallReceived": string[];
  "cilCallSplit": string[];
  "cilCallSwapCalls": string[];
  "cilCallToAction": string[];
  "cilCameraControl": string[];
  "cilCameraEnhance": string[];
  "cilCameraPlus": string[];
  "cilCameraRoll": string[];
  "cilCameraSwitch": string[];
  "cilCamera": string[];
  "cilCarAlt": string[];
  "cilCar": string[];
  "cilCardGiftcard": string[];
  "cilCardMembership": string[];
  "cilCaretBottom": string[];
  "cilCaretLeft": string[];
  "cilCaretRight": string[];
  "cilCardTravel": string[];
  "cilCaretTop": string[];
  "cilCartArrowDown": string[];
  "cilCartLoaded": string[];
  "cilCartPlus": string[];
  "cilCartSlash": string[];
  "cilCart": string[];
  "cilCastConnected": string[];
  "cilCasino": string[];
  "cilCastForEducation": string[];
  "cilCast": string[];
  "cilCat": string[];
  "cilCc": string[];
  "cilCenterFocusWeak": string[];
  "cilCenterFocus": string[];
  "cilChalkboardTeacher": string[];
  "cilChartArea": string[];
  "cilChartBubble": string[];
  "cilChartDonut": string[];
  "cilChartLine": string[];
  "cilChartMultiline": string[];
  "cilChartPie": string[];
  "cilChartShow": string[];
  "cilChartTable": string[];
  "cilChart": string[];
  "cilChatBubble": string[];
  "cilChatSquare": string[];
  "cilCheckAlt": string[];
  "cilCheckCircle": string[];
  "cilCheckDoubleAlt": string[];
  "cilCheckDouble": string[];
  "cilCheck": string[];
  "cilChevronBottomAlt": string[];
  "cilChevronBottom": string[];
  "cilChevronCircleDownAlt": string[];
  "cilChevronCircleDown": string[];
  "cilChevronCircleLeftAlt": string[];
  "cilChevronCircleLeft": string[];
  "cilChevronCircleRightAlt": string[];
  "cilChevronCircleRight": string[];
  "cilChevronCircleUpAlt": string[];
  "cilChevronCircleUp": string[];
  "cilChevronDoubleDownAlt": string[];
  "cilChevronDoubleDown": string[];
  "cilChevronDoubleLeftAlt": string[];
  "cilChevronDoubleLeft": string[];
  "cilChevronDoubleRightAlt": string[];
  "cilChevronDoubleRight": string[];
  "cilChevronDoubleUpAlt": string[];
  "cilChevronDoubleUp": string[];
  "cilChevronLeftAlt": string[];
  "cilChevronLeft": string[];
  "cilChevronRightAlt": string[];
  "cilChevronSquareDownAlt": string[];
  "cilChevronSquareDown": string[];
  "cilChevronRight": string[];
  "cilChevronSquareLeftAlt": string[];
  "cilChevronSquareLeft": string[];
  "cilChevronSquareRightAlt": string[];
  "cilChevronSquareRight": string[];
  "cilChevronSquareUpAlt": string[];
  "cilChevronSquareUp": string[];
  "cilChevronTopAlt": string[];
  "cilChevronTop": string[];
  "cilChildFriendly": string[];
  "cilChild": string[];
  "cilCircle": string[];
  "cilCity": string[];
  "cilClearAll": string[];
  "cilClone": string[];
  "cilClipboard": string[];
  "cilClosedCaptioning": string[];
  "cilClock": string[];
  "cilCloudDownload": string[];
  "cilCloudCheck": string[];
  "cilCloudCircle": string[];
  "cilCloudSlash": string[];
  "cilCloud": string[];
  "cilCode": string[];
  "cilCloudUpload": string[];
  "cilCoffee": string[];
  "cilCog": string[];
  "cilColorBorder": string[];
  "cilColorFill": string[];
  "cilColorPalette": string[];
  "cilColumns": string[];
  "cilCommand": string[];
  "cilCommentBubbleCheck": string[];
  "cilCommentBubbleEdit": string[];
  "cilCommentBubbleMinus": string[];
  "cilCommentBubblePlus": string[];
  "cilCommentBubbleExclamation": string[];
  "cilCommentBubbleQuestion": string[];
  "cilCommentBubbleX": string[];
  "cilCommentBubbleSmile": string[];
  "cilCommentBubble": string[];
  "cilCommentSquareCheck": string[];
  "cilCommentBubbleLines": string[];
  "cilCommentSquareEdit": string[];
  "cilCommentSquareExclamation": string[];
  "cilCommentSquareImage": string[];
  "cilCommentSquareLines": string[];
  "cilCommentSquareMinus": string[];
  "cilCommentSquarePlus": string[];
  "cilCommentSquareRateReview": string[];
  "cilCommentSquareSmile": string[];
  "cilCommentSquareX": string[];
  "cilCommentSquare": string[];
  "cilCommute": string[];
  "cilCompare": string[];
  "cilCompassCalibration": string[];
  "cilCompassSlash": string[];
  "cilCompass": string[];
  "cilCompressWide": string[];
  "cilCompress": string[];
  "cilContactMail": string[];
  "cilContactPhone": string[];
  "cilContact": string[];
  "cilContacts": string[];
  "cilContrast": string[];
  "cilControl": string[];
  "cilCopy": string[];
  "cilCouch": string[];
  "cilCreditCard": string[];
  "cilCropRotate": string[];
  "cilCrop": string[];
  "cilCursorMove": string[];
  "cilCursor": string[];
  "cilCut": string[];
  "cilDataTransferDown": string[];
  "cilDataTransferUp": string[];
  "cilDeaf": string[];
  "cilDelete": string[];
  "cilDescription": string[];
  "cilDeveloperBoard": string[];
  "cilDeviceUnknown": string[];
  "cilDevicesImportant": string[];
  "cilDevicesOther": string[];
  "cilDevicesSlash": string[];
  "cilDevices": string[];
  "cilDial": string[];
  "cilDialpad": string[];
  "cilDiamond": string[];
  "cilDinner": string[];
  "cilDirections": string[];
  "cilDisabled": string[];
  "cilDns": string[];
  "cilDock": string[];
  "cilDocument": string[];
  "cilDog": string[];
  "cilDollarCircleSlash": string[];
  "cilDollarCircle": string[];
  "cilDollarSlash": string[];
  "cilDollar": string[];
  "cilDonate": string[];
  "cilDoor": string[];
  "cilDoubleQuoteSansLeft": string[];
  "cilDoubleQuoteSansRight": string[];
  "cilDoubleQuoteSerifLeft": string[];
  "cilDoubleQuoteSerifRight": string[];
  "cilDrinkAlcohol": string[];
  "cilDrink": string[];
  "cilDropSlash": string[];
  "cilDrop": string[];
  "cilDvr": string[];
  "cilEar": string[];
  "cilEco": string[];
  "cilEducation": string[];
  "cilElevator": string[];
  "cilEnergyCircle": string[];
  "cilEnergy": string[];
  "cilEnvelopeClosed": string[];
  "cilEnvelopeLetter": string[];
  "cilEnvelopeMinus": string[];
  "cilEnvelopeOpen": string[];
  "cilEnvelopePlus": string[];
  "cilEqualizer": string[];
  "cilEthernetAlt": string[];
  "cilEthernet": string[];
  "cilEuroCircleSlash": string[];
  "cilEuroCircle": string[];
  "cilEuroSlash": string[];
  "cilEuro": string[];
  "cilEvStation": string[];
  "cilExclamationCircle": string[];
  "cilExcerpt": string[];
  "cilExclamation": string[];
  "cilExitToApp": string[];
  "cilExpandLeft": string[];
  "cilExpandDown": string[];
  "cilExpandRight": string[];
  "cilExpandUp": string[];
  "cilExposure": string[];
  "cilExternalLink": string[];
  "cilEyeSlash": string[];
  "cilEye": string[];
  "cilEyedropper": string[];
  "cilFace": string[];
  "cilFaceDead": string[];
  "cilFactorySlash": string[];
  "cilFactory": string[];
  "cilFastfood": string[];
  "cilFax": string[];
  "cilFeaturedPlaylist": string[];
  "cilFeaturedVideo": string[];
  "cilFiberDvr": string[];
  "cilFiberManual": string[];
  "cilFiberNew": string[];
  "cilFiberPin": string[];
  "cilFiberSmart": string[];
  "cilFileAcrobat": string[];
  "cilFileAdd": string[];
  "cilFileArchive": string[];
  "cilFileCode": string[];
  "cilFileAudio": string[];
  "cilFileImage": string[];
  "cilFileExcel": string[];
  "cilFileDoc": string[];
  "cilFilePdf": string[];
  "cilFilePowerpoint": string[];
  "cilFilePpt": string[];
  "cilFileXls": string[];
  "cilFileWord": string[];
  "cilFileVideo": string[];
  "cilFilterFrames": string[];
  "cilFile": string[];
  "cilFilterPhoto": string[];
  "cilFilter": string[];
  "cilFindReplace": string[];
  "cilFingerprint": string[];
  "cilFindInPage": string[];
  "cilFire": string[];
  "cilFlagAlt": string[];
  "cilFlagTriangle": string[];
  "cilFlag": string[];
  "cilFlame": string[];
  "cilFlagRectangle": string[];
  "cilFlash": string[];
  "cilFlightLand": string[];
  "cilFlightTakeoff": string[];
  "cilFlipToBack": string[];
  "cilFlipToFront": string[];
  "cilFlip": string[];
  "cilFlower": string[];
  "cilFolderAlt": string[];
  "cilFolderOpen": string[];
  "cilFolderPlus": string[];
  "cilFolderShared": string[];
  "cilFolder": string[];
  "cilFolderSpecial": string[];
  "cilFont": string[];
  "cilFootball": string[];
  "cilFork": string[];
  "cilFridge": string[];
  "cilFrown": string[];
  "cilFullscreenExit": string[];
  "cilFullscreen": string[];
  "cilFunctionsAlt": string[];
  "cilFunctions": string[];
  "cilGamepad": string[];
  "cilGarage": string[];
  "cilGem": string[];
  "cilGif": string[];
  "cilGift": string[];
  "cilGlass": string[];
  "cilGlobeAltLock": string[];
  "cilGlobeLock": string[];
  "cilGlobeAlt": string[];
  "cilGlobe": string[];
  "cilGolfAlt": string[];
  "cilGolf": string[];
  "cilGradient": string[];
  "cilGrain": string[];
  "cilGridSlash": string[];
  "cilGraph": string[];
  "cilGrid": string[];
  "cilHappy": string[];
  "cilHardDrive": string[];
  "cilHamburgerMenu": string[];
  "cilHd": string[];
  "cilHdr": string[];
  "cilHeader": string[];
  "cilHdrSlash": string[];
  "cilHeadphonesMute": string[];
  "cilHeadphonesMic": string[];
  "cilHeadphones": string[];
  "cilHealing": string[];
  "cilHeart": string[];
  "cilHighligt": string[];
  "cilHighQuality": string[];
  "cilHighlighter": string[];
  "cilHistory": string[];
  "cilHome": string[];
  "cilHospital": string[];
  "cilHotTub": string[];
  "cilHotel": string[];
  "cilHourglass": string[];
  "cilHq": string[];
  "cilHouse": string[];
  "cilHttps": string[];
  "cilIdBadge": string[];
  "cilIdCard": string[];
  "cilHttp": string[];
  "cilImageBroken": string[];
  "cilImage": string[];
  "cilImagePlus": string[];
  "cilInboxIn": string[];
  "cilInboxOut": string[];
  "cilImages": string[];
  "cilInbox": string[];
  "cilIndentDecrease": string[];
  "cilIndentIncrease": string[];
  "cilIndustrySlash": string[];
  "cilInfinity": string[];
  "cilInfo": string[];
  "cilInputAntenna": string[];
  "cilInputComponent": string[];
  "cilIndustry": string[];
  "cilInputHdmi": string[];
  "cilInputPowerOff": string[];
  "cilInputPower": string[];
  "cilInputSvideo": string[];
  "cilInput": string[];
  "cilInstitution": string[];
  "cilInvert": string[];
  "cilItalic": string[];
  "cilJustifyCenter": string[];
  "cilJustifyRight": string[];
  "cilJustifyLeft": string[];
  "cilKeyAlt": string[];
  "cilKey": string[];
  "cilKeyboardHide": string[];
  "cilKitchen": string[];
  "cilLan": string[];
  "cilKeyboard": string[];
  "cilLanguage": string[];
  "cilLayersSlash": string[];
  "cilLaundry": string[];
  "cilLaptop": string[];
  "cilLayers": string[];
  "cilLeaf": string[];
  "cilLemon": string[];
  "cilLevelDown": string[];
  "cilLevelUp": string[];
  "cilLibraryAdd": string[];
  "cilLibraryBookmark": string[];
  "cilLibraryBooks": string[];
  "cilLibraryMusic": string[];
  "cilLifeRing": string[];
  "cilLightbulb": string[];
  "cilLibraryBuilding": string[];
  "cilLineSpacing": string[];
  "cilLineWeight": string[];
  "cilLineStyle": string[];
  "cilLinkAlt": string[];
  "cilLinkBroken": string[];
  "cilLinkIntact": string[];
  "cilLink": string[];
  "cilListFilter": string[];
  "cilLinkSlash": string[];
  "cilListHighPriority": string[];
  "cilListLowPriority": string[];
  "cilListNumberedRtl": string[];
  "cilListNumbered": string[];
  "cilListRich": string[];
  "cilList": string[];
  "cilLocationGpsFixed": string[];
  "cilLocationGps": string[];
  "cilLocationPinCheck": string[];
  "cilLocationPinEdit": string[];
  "cilLocationPinSlash": string[];
  "cilLocationPinPlus": string[];
  "cilLocationGpsOff": string[];
  "cilLocationPin": string[];
  "cilLockLocked": string[];
  "cilLockMinus": string[];
  "cilLockPlus": string[];
  "cilLockUnlocked": string[];
  "cilLoop1": string[];
  "cilLoopCircular": string[];
  "cilLocomotive": string[];
  "cilLoopSquare": string[];
  "cilLowVision": string[];
  "cilLoop": string[];
  "cilLoyalty": string[];
  "cilMagnifyingGlass": string[];
  "cilMail": string[];
  "cilMailbox": string[];
  "cilMapAlt": string[];
  "cilMap": string[];
  "cilMediaEjectCircle": string[];
  "cilMediaEjectSquare": string[];
  "cilMediaEject": string[];
  "cilMediaPauseCircle": string[];
  "cilMediaPauseSquare": string[];
  "cilMediaPause": string[];
  "cilMediaPlayCircle": string[];
  "cilMediaPlaySquare": string[];
  "cilMediaRecordCircle": string[];
  "cilMediaPlay": string[];
  "cilMediaRecordSquare": string[];
  "cilMediaRecord": string[];
  "cilMediaSkipBackwardCircle": string[];
  "cilMediaSkipBackwardSquare": string[];
  "cilMediaSkipBackward": string[];
  "cilMediaSkipForwardCircle": string[];
  "cilMediaSkipForwardSquare": string[];
  "cilMediaSkipForward": string[];
  "cilMediaStepBackwardCircle": string[];
  "cilMediaStepBackwardSquare": string[];
  "cilMediaStepBackward": string[];
  "cilMediaStepForwardCircle": string[];
  "cilMediaStepForwardSquare": string[];
  "cilMediaStepForward": string[];
  "cilMediaStopCircle": string[];
  "cilMediaStopSquare": string[];
  "cilMediaStop": string[];
  "cilMedicalCross": string[];
  "cilMemory": string[];
  "cilMeh": string[];
  "cilMenu": string[];
  "cilMicAlt": string[];
  "cilMicSettings": string[];
  "cilMicSlash": string[];
  "cilMic": string[];
  "cilMicrochip": string[];
  "cilMicrophoneSettings": string[];
  "cilMicrophoneAlt": string[];
  "cilMicrophone": string[];
  "cilMinusCircle": string[];
  "cilMinusSquare": string[];
  "cilMinus": string[];
  "cilMobileArrowAdd": string[];
  "cilMicrophoneSlash": string[];
  "cilMobileArrowRemove": string[];
  "cilMobileLandscape": string[];
  "cilMobileLock": string[];
  "cilMobileMinus": string[];
  "cilMobilePlus": string[];
  "cilMobilePortrait": string[];
  "cilMobileSettings": string[];
  "cilMobileSlash": string[];
  "cilMobileSms": string[];
  "cilMobileSpeaker": string[];
  "cilMobileVolume": string[];
  "cilMobileDeveloperMode": string[];
  "cilMoneyBillAlt": string[];
  "cilMoneyBillAlt2": string[];
  "cilMoneyBill": string[];
  "cilMonitor": string[];
  "cilMoney": string[];
  "cilMoodGood": string[];
  "cilMoodBad": string[];
  "cilMore": string[];
  "cilMoodVeryBad": string[];
  "cilMouseAlt": string[];
  "cilMotorbike": string[];
  "cilMouse": string[];
  "cilMouthSlash": string[];
  "cilMouth": string[];
  "cilMove": string[];
  "cilMoodVeryGood": string[];
  "cilMovieAlt": string[];
  "cilMovie": string[];
  "cilMugTea": string[];
  "cilMug": string[];
  "cilMusicNoteAlt": string[];
  "cilMusicNoteSlash": string[];
  "cilMusicNote": string[];
  "cilNetworkCheck": string[];
  "cilMusicVideo": string[];
  "cilNewspaper": string[];
  "cilNewReleases": string[];
  "cilNew": string[];
  "cilNoteAdd": string[];
  "cilNote": string[];
  "cilNotes": string[];
  "cilObjectGroup": string[];
  "cilObjectUngroup": string[];
  "cilOpacity": string[];
  "cilOpentype": string[];
  "cilOven": string[];
  "cilOptions": string[];
  "cilOverscanSettings": string[];
  "cilOverscan": string[];
  "cilPageRestore": string[];
  "cilPage": string[];
  "cilPageview": string[];
  "cilPaintBucket": string[];
  "cilPaint": string[];
  "cilPaperclip": string[];
  "cilPaperPlane": string[];
  "cilParagraph": string[];
  "cilParking": string[];
  "cilPenAlt": string[];
  "cilPenFancy": string[];
  "cilPenNib": string[];
  "cilPen": string[];
  "cilPaw": string[];
  "cilPencil": string[];
  "cilPeople": string[];
  "cilPercent": string[];
  "cilPersonFemale": string[];
  "cilPeople_Plus": string[];
  "cilPerson": string[];
  "cilPetrolStation": string[];
  "cilPhoneBluetooth": string[];
  "cilPhoneCall": string[];
  "cilPhoneCallEnd": string[];
  "cilPhoneCallback": string[];
  "cilPhoneForward": string[];
  "cilPhoneInTalk": string[];
  "cilPhoneLock": string[];
  "cilPhoneMinus": string[];
  "cilPhoneMissed": string[];
  "cilPhonePaused": string[];
  "cilPhonePlus": string[];
  "cilPhoneRingVolume": string[];
  "cilPhoneVolume": string[];
  "cilPhone": string[];
  "cilPhoneSettings": string[];
  "cilPictureInPictureAlt": string[];
  "cilPin": string[];
  "cilPictureInPicture": string[];
  "cilPlant": string[];
  "cilPlaylistAddCheck": string[];
  "cilPlaylistPlay": string[];
  "cilPlaylistAdd": string[];
  "cilPizza": string[];
  "cilPlusCircle": string[];
  "cilPlusOne": string[];
  "cilPlusSquare": string[];
  "cilPlus": string[];
  "cilPool": string[];
  "cilPortableWifiOff": string[];
  "cilPortableWifi": string[];
  "cilPowerSettings": string[];
  "cilPowerStandby": string[];
  "cilPregnant": string[];
  "cilPrint": string[];
  "cilPrinter": string[];
  "cilPrinterSlash": string[];
  "cilPushchair": string[];
  "cilPuzzlePiece": string[];
  "cilQrCode": string[];
  "cilPuzzle": string[];
  "cilQueueAdd": string[];
  "cilQueueMusic": string[];
  "cilQueueRemove": string[];
  "cilQueuePlayNext": string[];
  "cilQueue": string[];
  "cilRadio": string[];
  "cilRailway": string[];
  "cilRandom": string[];
  "cilRecentActors": string[];
  "cilRectangle": string[];
  "cilRecycle": string[];
  "cilReload": string[];
  "cilRemoteControl": string[];
  "cilRemoteSettings": string[];
  "cilReplay": string[];
  "cilReportSlash": string[];
  "cilReport": string[];
  "cilResizeBoth": string[];
  "cilResizeHeight": string[];
  "cilRestaurantMenu": string[];
  "cilResizeWidth": string[];
  "cilRestaurant": string[];
  "cilRestore": string[];
  "cilRoomSlash": string[];
  "cilRoom": string[];
  "cilRouter": string[];
  "cilRowing": string[];
  "cilRoundedCorner": string[];
  "cilRssAlt": string[];
  "cilRss": string[];
  "cilRssSquare": string[];
  "cilRubleCircleSlash": string[];
  "cilRubleCircle": string[];
  "cilRubleSlash": string[];
  "cilRuble": string[];
  "cilSad": string[];
  "cilRunning": string[];
  "cilSatelite": string[];
  "cilSchool": string[];
  "cilScanner": string[];
  "cilSave": string[];
  "cilScooter": string[];
  "cilScreenDeskopSlash": string[];
  "cilScreenDesktop": string[];
  "cilScreenHorizontal": string[];
  "cilScreenLandscape": string[];
  "cilScreenLockHorizontal": string[];
  "cilScreenLockLandscape": string[];
  "cilScreenLockPortrait": string[];
  "cilScreenLockRotation": string[];
  "cilScreenMirroring": string[];
  "cilScreenPortrait": string[];
  "cilScreenLockVertical": string[];
  "cilScreenRotation": string[];
  "cilScreenSmartphone": string[];
  "cilScreenVertical": string[];
  "cilScript": string[];
  "cilScrubber": string[];
  "cilSdcard": string[];
  "cilSearch": string[];
  "cilLibrary": string[];
  "cilSelectAll": string[];
  "cilSend": string[];
  "cilSelect": string[];
  "cilSettings": string[];
  "cilShareAll": string[];
  "cilShareBoxed": string[];
  "cilShareAlt": string[];
  "cilShieldAlt": string[];
  "cilShare": string[];
  "cilShieldCheck": string[];
  "cilShieldPlus": string[];
  "cilShieldSlash": string[];
  "cilShieldMinus": string[];
  "cilShieldX": string[];
  "cilShield": string[];
  "cilShopMediaTwo": string[];
  "cilSecurity": string[];
  "cilShortText": string[];
  "cilShopMedia": string[];
  "cilSignalCellular0": string[];
  "cilShower": string[];
  "cilSignLanguage": string[];
  "cilSignalCellular2": string[];
  "cilSignalCellular1": string[];
  "cilSignalCellular3": string[];
  "cilSignalCellular4": string[];
  "cilSignalCellularNoInternet0": string[];
  "cilSignalCellularNoInternet1": string[];
  "cilSignalCellularNoInternet4": string[];
  "cilSignalCellularNoInternet2": string[];
  "cilSignalCellularNoInternet3": string[];
  "cilSignalCellularOff": string[];
  "cilSignalOff": string[];
  "cilSignal": string[];
  "cilSignpost": string[];
  "cilSimSlash": string[];
  "cilSim": string[];
  "cilSitemap": string[];
  "cilSlowMotion": string[];
  "cilSmilePlus": string[];
  "cilSmile": string[];
  "cilSmokeFree": string[];
  "cilSmokeSlash": string[];
  "cilSmoke": string[];
  "cilSmokingRoom": string[];
  "cilSoccer": string[];
  "cilSofa": string[];
  "cilSorroundSound": string[];
  "cilSortAlphaUp": string[];
  "cilSortAscending": string[];
  "cilSortAlphaDown": string[];
  "cilSortDescending": string[];
  "cilSortNumericDown": string[];
  "cilSortNumericUp": string[];
  "cilSpaceBar": string[];
  "cilSpa": string[];
  "cilSpeakerGroup": string[];
  "cilSpeaker": string[];
  "cilSpeak": string[];
  "cilSpeechNotesSlash": string[];
  "cilSpeechNotes": string[];
  "cilSpeechBubble": string[];
  "cilSpeech": string[];
  "cilSpeedometer": string[];
  "cilSpreadsheet": string[];
  "cilSquare": string[];
  "cilStarHalf": string[];
  "cilStarCircle": string[];
  "cilStar": string[];
  "cilStorage": string[];
  "cilStickyNote": string[];
  "cilStore": string[];
  "cilStream": string[];
  "cilStrikethrough": string[];
  "cilSubtitles": string[];
  "cilSubway": string[];
  "cilSwapHorizontalCircle": string[];
  "cilSwapVerticalCircle": string[];
  "cilSwapVertical": string[];
  "cilSwimming": string[];
  "cilSwapHorizontal": string[];
  "cilSyncProblem": string[];
  "cilSyncDisabled": string[];
  "cilTablet": string[];
  "cilSync": string[];
  "cilTennisBall": string[];
  "cilTask": string[];
  "cilTerminal": string[];
  "cilTaxi": string[];
  "cilTennis": string[];
  "cilTerrain": string[];
  "cilTextDirectionLtr": string[];
  "cilTextDirectionRtl": string[];
  "cilTextHeight": string[];
  "cilTextRotateVertical": string[];
  "cilTextFormatClear": string[];
  "cilTextRotationUp": string[];
  "cilTextRotationDown": string[];
  "cilTextSize": string[];
  "cilTextRotationNone": string[];
  "cilTextSquare": string[];
  "cilTextShapes": string[];
  "cilTextWidth": string[];
  "cilTextStrike": string[];
  "cilTimeline": string[];
  "cilText": string[];
  "cilTimer": string[];
  "cilToggleOn": string[];
  "cilToilet": string[];
  "cilToll": string[];
  "cilTouchApp": string[];
  "cilToggleOff": string[];
  "cilTraffic": string[];
  "cilTrainAlt": string[];
  "cilTrain": string[];
  "cilTransferWithinAStation": string[];
  "cilTram": string[];
  "cilTransfer": string[];
  "cilTranslate": string[];
  "cilTrashAlt": string[];
  "cilTrashArrowUp": string[];
  "cilTrashSweep": string[];
  "cilTrashX": string[];
  "cilTrash": string[];
  "cilTriangle": string[];
  "cilTruck": string[];
  "cilTvDvr": string[];
  "cilTty": string[];
  "cilTvLive": string[];
  "cilTvSlash": string[];
  "cilUnderline": string[];
  "cilTv": string[];
  "cilUpdate": string[];
  "cilUniversalAccess": string[];
  "cilUsb": string[];
  "cilUserFemale": string[];
  "cilUserUnfollow": string[];
  "cilUserFollow": string[];
  "cilUserSecret": string[];
  "cilUser": string[];
  "cilVector": string[];
  "cilVericalSplit": string[];
  "cilVerticalAlignBottom": string[];
  "cilVerticalAlignCenter": string[];
  "cilVerticalAlignTop": string[];
  "cilVideoLibrary": string[];
  "cilVideoLabel": string[];
  "cilVideoMissed": string[];
  "cilVideoPlus": string[];
  "cilVideoSlash": string[];
  "cilVideo": string[];
  "cilVideoSwitch": string[];
  "cilVideogame": string[];
  "cilViewAgenda": string[];
  "cilViewArray": string[];
  "cilViewCarousel": string[];
  "cilViewColumn": string[];
  "cilViewModule": string[];
  "cilViewQuilt": string[];
  "cilViewStream": string[];
  "cilVoiceOverRecord": string[];
  "cilVoiceOverSlash": string[];
  "cilVoice": string[];
  "cilVoicemail": string[];
  "cilVolumeHigh": string[];
  "cilVolumeLow": string[];
  "cilVolumeOff": string[];
  "cilVote": string[];
  "cilWalk": string[];
  "cilWallet": string[];
  "cilWallpaper": string[];
  "cilWarning": string[];
  "cilWatch": string[];
  "cilWaves": string[];
  "cilWc": string[];
  "cilWeights": string[];
  "cilWeightlifitng": string[];
  "cilWheelchair": string[];
  "cilWifiLock": string[];
  "cilWidgets": string[];
  "cilWifiSignal0": string[];
  "cilWifiSignal1": string[];
  "cilWifiSignal2": string[];
  "cilWifiSignal3": string[];
  "cilWifiSignal4": string[];
  "cilWifiSignalLock0": string[];
  "cilWifiSignalLock1": string[];
  "cilWifiSignalLock3": string[];
  "cilWifiSignalLock4": string[];
  "cilWifi": string[];
  "cilWifiSignalOff": string[];
  "cilWindowMaximize": string[];
  "cilWindowMinimize": string[];
  "cilWindow": string[];
  "cilWindowRestore": string[];
  "cilWrapText": string[];
  "cilXCircle": string[];
  "cilXSquare": string[];
  "cilX": string[];
  "cilYenCircleSlash": string[];
  "cilWifiSignalLock2": string[];
  "cilYenCircle": string[];
  "cilYenSlash": string[];
  "cilYen": string[];
  "cilZoomOut": string[];
  "cilZoom": string[];
  "cilZoomIn": string[];
}
export declare const cil3d: string[];
export declare const cil3dRotate: string[];
export declare const cil4k: string[];
export declare const cilAccessibility: string[];
export declare const cilAccessible: string[];
export declare const cilAccountLogout: string[];
export declare const cilActionRedo: string[];
export declare const cilActionUndo: string[];
export declare const cilAddressBook: string[];
export declare const cilAddressCard: string[];
export declare const cilAirplaneModeOff: string[];
export declare const cilAirplaneMode: string[];
export declare const cilAirplay: string[];
export declare const cilAlarmAdd: string[];
export declare const cilAlarmOff: string[];
export declare const cilAlarmOn: string[];
export declare const cilAlarmSnooze: string[];
export declare const cilAlarm: string[];
export declare const cilAlbum: string[];
export declare const cilAlignCenter: string[];
export declare const cilAlignLeft: string[];
export declare const cilAlignRight: string[];
export declare const cilAmericanFootball: string[];
export declare const cilAnimal: string[];
export declare const cilAperture: string[];
export declare const cilApple: string[];
export declare const cilApplicationsSettings: string[];
export declare const cilApplications: string[];
export declare const cilAppsSettings: string[];
export declare const cilApps: string[];
export declare const cilArchive: string[];
export declare const cilArrowBottom: string[];
export declare const cilArrowCircleBottom: string[];
export declare const cilArrowCircleLeft: string[];
export declare const cilArrowCircleRight: string[];
export declare const cilArrowCircleTop: string[];
export declare const cilArrowLeft: string[];
export declare const cilArrowRight: string[];
export declare const cilArrowThickBottom: string[];
export declare const cilArrowThickCircleDown: string[];
export declare const cilArrowThickCircleLeft: string[];
export declare const cilArrowThickCircleRight: string[];
export declare const cilArrowThickCircleUp: string[];
export declare const cilArrowThickFromBottom: string[];
export declare const cilArrowThickFromRight: string[];
export declare const cilArrowThickFromTop: string[];
export declare const cilArrowThickLeft: string[];
export declare const cilArrowThickRight: string[];
export declare const cilArrowThickSquareDown: string[];
export declare const cilArrowThickSquareLeft: string[];
export declare const cilArrowThickSquareRight: string[];
export declare const cilArrowThickSquareUp: string[];
export declare const cilArrowThickToBottom: string[];
export declare const cilArrowThickToLeft: string[];
export declare const cilArrowThickToRight: string[];
export declare const cilArrowThickToTop: string[];
export declare const cilArrowThickTop: string[];
export declare const cilArrowTop: string[];
export declare const cilArtTrack: string[];
export declare const cilAssistiveListeningSystem: string[];
export declare const cilAsteriskCircle: string[];
export declare const cilAsterisk: string[];
export declare const cilAt: string[];
export declare const cilAudioDescription: string[];
export declare const cilAudioSpectrum: string[];
export declare const cilAudio: string[];
export declare const cilAvTimer: string[];
export declare const cilBabyCarriage: string[];
export declare const cilBaby: string[];
export declare const cilBackspace: string[];
export declare const cilBadge: string[];
export declare const cilBalanceScaleLeft: string[];
export declare const cilBalanceScaleRight: string[];
export declare const cilBalanceScale: string[];
export declare const cilBan: string[];
export declare const cilBank: string[];
export declare const cilBarChart: string[];
export declare const cilBarcode: string[];
export declare const cilBaseball: string[];
export declare const cilBasketArrowDown: string[];
export declare const cilBasketLoaded: string[];
export declare const cilBasketPlus: string[];
export declare const cilBasket: string[];
export declare const cilBasketball: string[];
export declare const cilBath: string[];
export declare const cilBathroom: string[];
export declare const cilBattery0: string[];
export declare const cilBattery1: string[];
export declare const cilBattery2: string[];
export declare const cilBattery3: string[];
export declare const cilBattery4: string[];
export declare const cilBattery5: string[];
export declare const cilBatteryAlert: string[];
export declare const cilBatteryAlt0: string[];
export declare const cilBatteryAlt1: string[];
export declare const cilBatteryAlt2: string[];
export declare const cilBatteryAlt3: string[];
export declare const cilBatteryAltEmpty: string[];
export declare const cilBatteryAltFull: string[];
export declare const cilBatteryAltSlash: string[];
export declare const cilBatteryCharge: string[];
export declare const cilBatteryEmpty: string[];
export declare const cilBatteryFull: string[];
export declare const cilBatterySlash: string[];
export declare const cilBatteryUnknown: string[];
export declare const cilBeachAccess: string[];
export declare const cilArrowThickFromLeft: string[];
export declare const cilBeaker: string[];
export declare const cilBed: string[];
export declare const cilBellExclamation: string[];
export declare const cilBellPlus: string[];
export declare const cilBellRing: string[];
export declare const cilBellSlash: string[];
export declare const cilBell: string[];
export declare const cilBikeAlt: string[];
export declare const cilBike: string[];
export declare const cilBlind: string[];
export declare const cilBirthdayCake: string[];
export declare const cilBluetoothConnected: string[];
export declare const cilBluetoothSettings: string[];
export declare const cilBluetoothSearching: string[];
export declare const cilBluetoothSlash: string[];
export declare const cilBluetooth: string[];
export declare const cilBlurCircular: string[];
export declare const cilBlurLinear: string[];
export declare const cilBlurSlash: string[];
export declare const cilBlur: string[];
export declare const cilBoatAlt: string[];
export declare const cilBoat: string[];
export declare const cilBold: string[];
export declare const cilBoltAlt: string[];
export declare const cilBoltCircle: string[];
export declare const cilBolt: string[];
export declare const cilBookOpen: string[];
export declare const cilBook: string[];
export declare const cilBookmark: string[];
export declare const cilBookmarks: string[];
export declare const cilBorderAll: string[];
export declare const cilBorderBottom: string[];
export declare const cilBorderClear: string[];
export declare const cilBorderHorizontal: string[];
export declare const cilBorderInner: string[];
export declare const cilBorderLeft: string[];
export declare const cilBorderOuter: string[];
export declare const cilBorderRight: string[];
export declare const cilBorderStyle: string[];
export declare const cilBorderTop: string[];
export declare const cilBorderVertical: string[];
export declare const cilBowlingPins: string[];
export declare const cilBowling: string[];
export declare const cilBox: string[];
export declare const cilBraille: string[];
export declare const cilBrandingWatermark: string[];
export declare const cilBriefcaseArrowLeft: string[];
export declare const cilBriefcaseArrowRight: string[];
export declare const cilBriefcaseSlash: string[];
export declare const cilBriefcase: string[];
export declare const cilBrightnessAuto: string[];
export declare const cilBrightnessHigh: string[];
export declare const cilBrightnessLow: string[];
export declare const cilBrightnessMedium: string[];
export declare const cilBrightness: string[];
export declare const cilBritishPoundCircle: string[];
export declare const cilBritishPoundSlash: string[];
export declare const cilBroadcastTower: string[];
export declare const cilBritishPound: string[];
export declare const cilBrush: string[];
export declare const cilBrowser: string[];
export declare const cilBug: string[];
export declare const cilBuildingBusinessSlash: string[];
export declare const cilBuildingBusiness: string[];
export declare const cilBuildingSlash: string[];
export declare const cilBuilding: string[];
export declare const cilBurger: string[];
export declare const cilBusAlt: string[];
export declare const cilBullhorn: string[];
export declare const cilBusTimer: string[];
export declare const cilBus: string[];
export declare const cilCalculator: string[];
export declare const cilCalendarCheck: string[];
export declare const cilCalendarEvent: string[];
export declare const cilCalendarAlt: string[];
export declare const cilCalendarNote: string[];
export declare const cilCalendarMinus: string[];
export declare const cilCalendarTimes: string[];
export declare const cilCalendarPlus: string[];
export declare const cilBrushAlt: string[];
export declare const cilCalendarToday: string[];
export declare const cilCalendarViewDay: string[];
export declare const cilCalendar: string[];
export declare const cilCallMade: string[];
export declare const cilCallMerge: string[];
export declare const cilCallMissedOutgoing: string[];
export declare const cilCallMissed: string[];
export declare const cilCallReceived: string[];
export declare const cilCallSplit: string[];
export declare const cilCallSwapCalls: string[];
export declare const cilCallToAction: string[];
export declare const cilCameraControl: string[];
export declare const cilCameraEnhance: string[];
export declare const cilCameraPlus: string[];
export declare const cilCameraRoll: string[];
export declare const cilCameraSwitch: string[];
export declare const cilCamera: string[];
export declare const cilCarAlt: string[];
export declare const cilCar: string[];
export declare const cilCardGiftcard: string[];
export declare const cilCardMembership: string[];
export declare const cilCaretBottom: string[];
export declare const cilCaretLeft: string[];
export declare const cilCaretRight: string[];
export declare const cilCardTravel: string[];
export declare const cilCaretTop: string[];
export declare const cilCartArrowDown: string[];
export declare const cilCartLoaded: string[];
export declare const cilCartPlus: string[];
export declare const cilCartSlash: string[];
export declare const cilCart: string[];
export declare const cilCastConnected: string[];
export declare const cilCasino: string[];
export declare const cilCastForEducation: string[];
export declare const cilCast: string[];
export declare const cilCat: string[];
export declare const cilCc: string[];
export declare const cilCenterFocusWeak: string[];
export declare const cilCenterFocus: string[];
export declare const cilChalkboardTeacher: string[];
export declare const cilChartArea: string[];
export declare const cilChartBubble: string[];
export declare const cilChartDonut: string[];
export declare const cilChartLine: string[];
export declare const cilChartMultiline: string[];
export declare const cilChartPie: string[];
export declare const cilChartShow: string[];
export declare const cilChartTable: string[];
export declare const cilChart: string[];
export declare const cilChatBubble: string[];
export declare const cilChatSquare: string[];
export declare const cilCheckAlt: string[];
export declare const cilCheckCircle: string[];
export declare const cilCheckDoubleAlt: string[];
export declare const cilCheckDouble: string[];
export declare const cilCheck: string[];
export declare const cilChevronBottomAlt: string[];
export declare const cilChevronBottom: string[];
export declare const cilChevronCircleDownAlt: string[];
export declare const cilChevronCircleDown: string[];
export declare const cilChevronCircleLeftAlt: string[];
export declare const cilChevronCircleLeft: string[];
export declare const cilChevronCircleRightAlt: string[];
export declare const cilChevronCircleRight: string[];
export declare const cilChevronCircleUpAlt: string[];
export declare const cilChevronCircleUp: string[];
export declare const cilChevronDoubleDownAlt: string[];
export declare const cilChevronDoubleDown: string[];
export declare const cilChevronDoubleLeftAlt: string[];
export declare const cilChevronDoubleLeft: string[];
export declare const cilChevronDoubleRightAlt: string[];
export declare const cilChevronDoubleRight: string[];
export declare const cilChevronDoubleUpAlt: string[];
export declare const cilChevronDoubleUp: string[];
export declare const cilChevronLeftAlt: string[];
export declare const cilChevronLeft: string[];
export declare const cilChevronRightAlt: string[];
export declare const cilChevronSquareDownAlt: string[];
export declare const cilChevronSquareDown: string[];
export declare const cilChevronRight: string[];
export declare const cilChevronSquareLeftAlt: string[];
export declare const cilChevronSquareLeft: string[];
export declare const cilChevronSquareRightAlt: string[];
export declare const cilChevronSquareRight: string[];
export declare const cilChevronSquareUpAlt: string[];
export declare const cilChevronSquareUp: string[];
export declare const cilChevronTopAlt: string[];
export declare const cilChevronTop: string[];
export declare const cilChildFriendly: string[];
export declare const cilChild: string[];
export declare const cilCircle: string[];
export declare const cilCity: string[];
export declare const cilClearAll: string[];
export declare const cilClone: string[];
export declare const cilClipboard: string[];
export declare const cilClosedCaptioning: string[];
export declare const cilClock: string[];
export declare const cilCloudDownload: string[];
export declare const cilCloudCheck: string[];
export declare const cilCloudCircle: string[];
export declare const cilCloudSlash: string[];
export declare const cilCloud: string[];
export declare const cilCode: string[];
export declare const cilCloudUpload: string[];
export declare const cilCoffee: string[];
export declare const cilCog: string[];
export declare const cilColorBorder: string[];
export declare const cilColorFill: string[];
export declare const cilColorPalette: string[];
export declare const cilColumns: string[];
export declare const cilCommand: string[];
export declare const cilCommentBubbleCheck: string[];
export declare const cilCommentBubbleEdit: string[];
export declare const cilCommentBubbleMinus: string[];
export declare const cilCommentBubblePlus: string[];
export declare const cilCommentBubbleExclamation: string[];
export declare const cilCommentBubbleQuestion: string[];
export declare const cilCommentBubbleX: string[];
export declare const cilCommentBubbleSmile: string[];
export declare const cilCommentBubble: string[];
export declare const cilCommentSquareCheck: string[];
export declare const cilCommentBubbleLines: string[];
export declare const cilCommentSquareEdit: string[];
export declare const cilCommentSquareExclamation: string[];
export declare const cilCommentSquareImage: string[];
export declare const cilCommentSquareLines: string[];
export declare const cilCommentSquareMinus: string[];
export declare const cilCommentSquarePlus: string[];
export declare const cilCommentSquareRateReview: string[];
export declare const cilCommentSquareSmile: string[];
export declare const cilCommentSquareX: string[];
export declare const cilCommentSquare: string[];
export declare const cilCommute: string[];
export declare const cilCompare: string[];
export declare const cilCompassCalibration: string[];
export declare const cilCompassSlash: string[];
export declare const cilCompass: string[];
export declare const cilCompressWide: string[];
export declare const cilCompress: string[];
export declare const cilContactMail: string[];
export declare const cilContactPhone: string[];
export declare const cilContact: string[];
export declare const cilContacts: string[];
export declare const cilContrast: string[];
export declare const cilControl: string[];
export declare const cilCopy: string[];
export declare const cilCouch: string[];
export declare const cilCreditCard: string[];
export declare const cilCropRotate: string[];
export declare const cilCrop: string[];
export declare const cilCursorMove: string[];
export declare const cilCursor: string[];
export declare const cilCut: string[];
export declare const cilDataTransferDown: string[];
export declare const cilDataTransferUp: string[];
export declare const cilDeaf: string[];
export declare const cilDelete: string[];
export declare const cilDescription: string[];
export declare const cilDeveloperBoard: string[];
export declare const cilDeviceUnknown: string[];
export declare const cilDevicesImportant: string[];
export declare const cilDevicesOther: string[];
export declare const cilDevicesSlash: string[];
export declare const cilDevices: string[];
export declare const cilDial: string[];
export declare const cilDialpad: string[];
export declare const cilDiamond: string[];
export declare const cilDinner: string[];
export declare const cilDirections: string[];
export declare const cilDisabled: string[];
export declare const cilDns: string[];
export declare const cilDock: string[];
export declare const cilDocument: string[];
export declare const cilDog: string[];
export declare const cilDollarCircleSlash: string[];
export declare const cilDollarCircle: string[];
export declare const cilDollarSlash: string[];
export declare const cilDollar: string[];
export declare const cilDonate: string[];
export declare const cilDoor: string[];
export declare const cilDoubleQuoteSansLeft: string[];
export declare const cilDoubleQuoteSansRight: string[];
export declare const cilDoubleQuoteSerifLeft: string[];
export declare const cilDoubleQuoteSerifRight: string[];
export declare const cilDrinkAlcohol: string[];
export declare const cilDrink: string[];
export declare const cilDropSlash: string[];
export declare const cilDrop: string[];
export declare const cilDvr: string[];
export declare const cilEar: string[];
export declare const cilEco: string[];
export declare const cilEducation: string[];
export declare const cilElevator: string[];
export declare const cilEnergyCircle: string[];
export declare const cilEnergy: string[];
export declare const cilEnvelopeClosed: string[];
export declare const cilEnvelopeLetter: string[];
export declare const cilEnvelopeMinus: string[];
export declare const cilEnvelopeOpen: string[];
export declare const cilEnvelopePlus: string[];
export declare const cilEqualizer: string[];
export declare const cilEthernetAlt: string[];
export declare const cilEthernet: string[];
export declare const cilEuroCircleSlash: string[];
export declare const cilEuroCircle: string[];
export declare const cilEuroSlash: string[];
export declare const cilEuro: string[];
export declare const cilEvStation: string[];
export declare const cilExclamationCircle: string[];
export declare const cilExcerpt: string[];
export declare const cilExclamation: string[];
export declare const cilExitToApp: string[];
export declare const cilExpandLeft: string[];
export declare const cilExpandDown: string[];
export declare const cilExpandRight: string[];
export declare const cilExpandUp: string[];
export declare const cilExposure: string[];
export declare const cilExternalLink: string[];
export declare const cilEyeSlash: string[];
export declare const cilEye: string[];
export declare const cilEyedropper: string[];
export declare const cilFace: string[];
export declare const cilFaceDead: string[];
export declare const cilFactorySlash: string[];
export declare const cilFactory: string[];
export declare const cilFastfood: string[];
export declare const cilFax: string[];
export declare const cilFeaturedPlaylist: string[];
export declare const cilFeaturedVideo: string[];
export declare const cilFiberDvr: string[];
export declare const cilFiberManual: string[];
export declare const cilFiberNew: string[];
export declare const cilFiberPin: string[];
export declare const cilFiberSmart: string[];
export declare const cilFileAcrobat: string[];
export declare const cilFileAdd: string[];
export declare const cilFileArchive: string[];
export declare const cilFileCode: string[];
export declare const cilFileAudio: string[];
export declare const cilFileImage: string[];
export declare const cilFileExcel: string[];
export declare const cilFileDoc: string[];
export declare const cilFilePdf: string[];
export declare const cilFilePowerpoint: string[];
export declare const cilFilePpt: string[];
export declare const cilFileXls: string[];
export declare const cilFileWord: string[];
export declare const cilFileVideo: string[];
export declare const cilFilterFrames: string[];
export declare const cilFile: string[];
export declare const cilFilterPhoto: string[];
export declare const cilFilter: string[];
export declare const cilFindReplace: string[];
export declare const cilFingerprint: string[];
export declare const cilFindInPage: string[];
export declare const cilFire: string[];
export declare const cilFlagAlt: string[];
export declare const cilFlagTriangle: string[];
export declare const cilFlag: string[];
export declare const cilFlame: string[];
export declare const cilFlagRectangle: string[];
export declare const cilFlash: string[];
export declare const cilFlightLand: string[];
export declare const cilFlightTakeoff: string[];
export declare const cilFlipToBack: string[];
export declare const cilFlipToFront: string[];
export declare const cilFlip: string[];
export declare const cilFlower: string[];
export declare const cilFolderAlt: string[];
export declare const cilFolderOpen: string[];
export declare const cilFolderPlus: string[];
export declare const cilFolderShared: string[];
export declare const cilFolder: string[];
export declare const cilFolderSpecial: string[];
export declare const cilFont: string[];
export declare const cilFootball: string[];
export declare const cilFork: string[];
export declare const cilFridge: string[];
export declare const cilFrown: string[];
export declare const cilFullscreenExit: string[];
export declare const cilFullscreen: string[];
export declare const cilFunctionsAlt: string[];
export declare const cilFunctions: string[];
export declare const cilGamepad: string[];
export declare const cilGarage: string[];
export declare const cilGem: string[];
export declare const cilGif: string[];
export declare const cilGift: string[];
export declare const cilGlass: string[];
export declare const cilGlobeAltLock: string[];
export declare const cilGlobeLock: string[];
export declare const cilGlobeAlt: string[];
export declare const cilGlobe: string[];
export declare const cilGolfAlt: string[];
export declare const cilGolf: string[];
export declare const cilGradient: string[];
export declare const cilGrain: string[];
export declare const cilGridSlash: string[];
export declare const cilGraph: string[];
export declare const cilGrid: string[];
export declare const cilHappy: string[];
export declare const cilHardDrive: string[];
export declare const cilHamburgerMenu: string[];
export declare const cilHd: string[];
export declare const cilHdr: string[];
export declare const cilHeader: string[];
export declare const cilHdrSlash: string[];
export declare const cilHeadphonesMute: string[];
export declare const cilHeadphonesMic: string[];
export declare const cilHeadphones: string[];
export declare const cilHealing: string[];
export declare const cilHeart: string[];
export declare const cilHighligt: string[];
export declare const cilHighQuality: string[];
export declare const cilHighlighter: string[];
export declare const cilHistory: string[];
export declare const cilHome: string[];
export declare const cilHospital: string[];
export declare const cilHotTub: string[];
export declare const cilHotel: string[];
export declare const cilHourglass: string[];
export declare const cilHq: string[];
export declare const cilHouse: string[];
export declare const cilHttps: string[];
export declare const cilIdBadge: string[];
export declare const cilIdCard: string[];
export declare const cilHttp: string[];
export declare const cilImageBroken: string[];
export declare const cilImage: string[];
export declare const cilImagePlus: string[];
export declare const cilInboxIn: string[];
export declare const cilInboxOut: string[];
export declare const cilImages: string[];
export declare const cilInbox: string[];
export declare const cilIndentDecrease: string[];
export declare const cilIndentIncrease: string[];
export declare const cilIndustrySlash: string[];
export declare const cilInfinity: string[];
export declare const cilInfo: string[];
export declare const cilInputAntenna: string[];
export declare const cilInputComponent: string[];
export declare const cilIndustry: string[];
export declare const cilInputHdmi: string[];
export declare const cilInputPowerOff: string[];
export declare const cilInputPower: string[];
export declare const cilInputSvideo: string[];
export declare const cilInput: string[];
export declare const cilInstitution: string[];
export declare const cilInvert: string[];
export declare const cilItalic: string[];
export declare const cilJustifyCenter: string[];
export declare const cilJustifyRight: string[];
export declare const cilJustifyLeft: string[];
export declare const cilKeyAlt: string[];
export declare const cilKey: string[];
export declare const cilKeyboardHide: string[];
export declare const cilKitchen: string[];
export declare const cilLan: string[];
export declare const cilKeyboard: string[];
export declare const cilLanguage: string[];
export declare const cilLayersSlash: string[];
export declare const cilLaundry: string[];
export declare const cilLaptop: string[];
export declare const cilLayers: string[];
export declare const cilLeaf: string[];
export declare const cilLemon: string[];
export declare const cilLevelDown: string[];
export declare const cilLevelUp: string[];
export declare const cilLibraryAdd: string[];
export declare const cilLibraryBookmark: string[];
export declare const cilLibraryBooks: string[];
export declare const cilLibraryMusic: string[];
export declare const cilLifeRing: string[];
export declare const cilLightbulb: string[];
export declare const cilLibraryBuilding: string[];
export declare const cilLineSpacing: string[];
export declare const cilLineWeight: string[];
export declare const cilLineStyle: string[];
export declare const cilLinkAlt: string[];
export declare const cilLinkBroken: string[];
export declare const cilLinkIntact: string[];
export declare const cilLink: string[];
export declare const cilListFilter: string[];
export declare const cilLinkSlash: string[];
export declare const cilListHighPriority: string[];
export declare const cilListLowPriority: string[];
export declare const cilListNumberedRtl: string[];
export declare const cilListNumbered: string[];
export declare const cilListRich: string[];
export declare const cilList: string[];
export declare const cilLocationGpsFixed: string[];
export declare const cilLocationGps: string[];
export declare const cilLocationPinCheck: string[];
export declare const cilLocationPinEdit: string[];
export declare const cilLocationPinSlash: string[];
export declare const cilLocationPinPlus: string[];
export declare const cilLocationGpsOff: string[];
export declare const cilLocationPin: string[];
export declare const cilLockLocked: string[];
export declare const cilLockMinus: string[];
export declare const cilLockPlus: string[];
export declare const cilLockUnlocked: string[];
export declare const cilLoop1: string[];
export declare const cilLoopCircular: string[];
export declare const cilLocomotive: string[];
export declare const cilLoopSquare: string[];
export declare const cilLowVision: string[];
export declare const cilLoop: string[];
export declare const cilLoyalty: string[];
export declare const cilMagnifyingGlass: string[];
export declare const cilMail: string[];
export declare const cilMailbox: string[];
export declare const cilMapAlt: string[];
export declare const cilMap: string[];
export declare const cilMediaEjectCircle: string[];
export declare const cilMediaEjectSquare: string[];
export declare const cilMediaEject: string[];
export declare const cilMediaPauseCircle: string[];
export declare const cilMediaPauseSquare: string[];
export declare const cilMediaPause: string[];
export declare const cilMediaPlayCircle: string[];
export declare const cilMediaPlaySquare: string[];
export declare const cilMediaRecordCircle: string[];
export declare const cilMediaPlay: string[];
export declare const cilMediaRecordSquare: string[];
export declare const cilMediaRecord: string[];
export declare const cilMediaSkipBackwardCircle: string[];
export declare const cilMediaSkipBackwardSquare: string[];
export declare const cilMediaSkipBackward: string[];
export declare const cilMediaSkipForwardCircle: string[];
export declare const cilMediaSkipForwardSquare: string[];
export declare const cilMediaSkipForward: string[];
export declare const cilMediaStepBackwardCircle: string[];
export declare const cilMediaStepBackwardSquare: string[];
export declare const cilMediaStepBackward: string[];
export declare const cilMediaStepForwardCircle: string[];
export declare const cilMediaStepForwardSquare: string[];
export declare const cilMediaStepForward: string[];
export declare const cilMediaStopCircle: string[];
export declare const cilMediaStopSquare: string[];
export declare const cilMediaStop: string[];
export declare const cilMedicalCross: string[];
export declare const cilMemory: string[];
export declare const cilMeh: string[];
export declare const cilMenu: string[];
export declare const cilMicAlt: string[];
export declare const cilMicSettings: string[];
export declare const cilMicSlash: string[];
export declare const cilMic: string[];
export declare const cilMicrochip: string[];
export declare const cilMicrophoneSettings: string[];
export declare const cilMicrophoneAlt: string[];
export declare const cilMicrophone: string[];
export declare const cilMinusCircle: string[];
export declare const cilMinusSquare: string[];
export declare const cilMinus: string[];
export declare const cilMobileArrowAdd: string[];
export declare const cilMicrophoneSlash: string[];
export declare const cilMobileArrowRemove: string[];
export declare const cilMobileLandscape: string[];
export declare const cilMobileLock: string[];
export declare const cilMobileMinus: string[];
export declare const cilMobilePlus: string[];
export declare const cilMobilePortrait: string[];
export declare const cilMobileSettings: string[];
export declare const cilMobileSlash: string[];
export declare const cilMobileSms: string[];
export declare const cilMobileSpeaker: string[];
export declare const cilMobileVolume: string[];
export declare const cilMobileDeveloperMode: string[];
export declare const cilMoneyBillAlt: string[];
export declare const cilMoneyBillAlt2: string[];
export declare const cilMoneyBill: string[];
export declare const cilMonitor: string[];
export declare const cilMoney: string[];
export declare const cilMoodGood: string[];
export declare const cilMoodBad: string[];
export declare const cilMore: string[];
export declare const cilMoodVeryBad: string[];
export declare const cilMouseAlt: string[];
export declare const cilMotorbike: string[];
export declare const cilMouse: string[];
export declare const cilMouthSlash: string[];
export declare const cilMouth: string[];
export declare const cilMove: string[];
export declare const cilMoodVeryGood: string[];
export declare const cilMovieAlt: string[];
export declare const cilMovie: string[];
export declare const cilMugTea: string[];
export declare const cilMug: string[];
export declare const cilMusicNoteAlt: string[];
export declare const cilMusicNoteSlash: string[];
export declare const cilMusicNote: string[];
export declare const cilNetworkCheck: string[];
export declare const cilMusicVideo: string[];
export declare const cilNewspaper: string[];
export declare const cilNewReleases: string[];
export declare const cilNew: string[];
export declare const cilNoteAdd: string[];
export declare const cilNote: string[];
export declare const cilNotes: string[];
export declare const cilObjectGroup: string[];
export declare const cilObjectUngroup: string[];
export declare const cilOpacity: string[];
export declare const cilOpentype: string[];
export declare const cilOven: string[];
export declare const cilOptions: string[];
export declare const cilOverscanSettings: string[];
export declare const cilOverscan: string[];
export declare const cilPageRestore: string[];
export declare const cilPage: string[];
export declare const cilPageview: string[];
export declare const cilPaintBucket: string[];
export declare const cilPaint: string[];
export declare const cilPaperclip: string[];
export declare const cilPaperPlane: string[];
export declare const cilParagraph: string[];
export declare const cilParking: string[];
export declare const cilPenAlt: string[];
export declare const cilPenFancy: string[];
export declare const cilPenNib: string[];
export declare const cilPen: string[];
export declare const cilPaw: string[];
export declare const cilPencil: string[];
export declare const cilPeople: string[];
export declare const cilPercent: string[];
export declare const cilPersonFemale: string[];
export declare const cilPeople_Plus: string[];
export declare const cilPerson: string[];
export declare const cilPetrolStation: string[];
export declare const cilPhoneBluetooth: string[];
export declare const cilPhoneCall: string[];
export declare const cilPhoneCallEnd: string[];
export declare const cilPhoneCallback: string[];
export declare const cilPhoneForward: string[];
export declare const cilPhoneInTalk: string[];
export declare const cilPhoneLock: string[];
export declare const cilPhoneMinus: string[];
export declare const cilPhoneMissed: string[];
export declare const cilPhonePaused: string[];
export declare const cilPhonePlus: string[];
export declare const cilPhoneRingVolume: string[];
export declare const cilPhoneVolume: string[];
export declare const cilPhone: string[];
export declare const cilPhoneSettings: string[];
export declare const cilPictureInPictureAlt: string[];
export declare const cilPin: string[];
export declare const cilPictureInPicture: string[];
export declare const cilPlant: string[];
export declare const cilPlaylistAddCheck: string[];
export declare const cilPlaylistPlay: string[];
export declare const cilPlaylistAdd: string[];
export declare const cilPizza: string[];
export declare const cilPlusCircle: string[];
export declare const cilPlusOne: string[];
export declare const cilPlusSquare: string[];
export declare const cilPlus: string[];
export declare const cilPool: string[];
export declare const cilPortableWifiOff: string[];
export declare const cilPortableWifi: string[];
export declare const cilPowerSettings: string[];
export declare const cilPowerStandby: string[];
export declare const cilPregnant: string[];
export declare const cilPrint: string[];
export declare const cilPrinter: string[];
export declare const cilPrinterSlash: string[];
export declare const cilPushchair: string[];
export declare const cilPuzzlePiece: string[];
export declare const cilQrCode: string[];
export declare const cilPuzzle: string[];
export declare const cilQueueAdd: string[];
export declare const cilQueueMusic: string[];
export declare const cilQueueRemove: string[];
export declare const cilQueuePlayNext: string[];
export declare const cilQueue: string[];
export declare const cilRadio: string[];
export declare const cilRailway: string[];
export declare const cilRandom: string[];
export declare const cilRecentActors: string[];
export declare const cilRectangle: string[];
export declare const cilRecycle: string[];
export declare const cilReload: string[];
export declare const cilRemoteControl: string[];
export declare const cilRemoteSettings: string[];
export declare const cilReplay: string[];
export declare const cilReportSlash: string[];
export declare const cilReport: string[];
export declare const cilResizeBoth: string[];
export declare const cilResizeHeight: string[];
export declare const cilRestaurantMenu: string[];
export declare const cilResizeWidth: string[];
export declare const cilRestaurant: string[];
export declare const cilRestore: string[];
export declare const cilRoomSlash: string[];
export declare const cilRoom: string[];
export declare const cilRouter: string[];
export declare const cilRowing: string[];
export declare const cilRoundedCorner: string[];
export declare const cilRssAlt: string[];
export declare const cilRss: string[];
export declare const cilRssSquare: string[];
export declare const cilRubleCircleSlash: string[];
export declare const cilRubleCircle: string[];
export declare const cilRubleSlash: string[];
export declare const cilRuble: string[];
export declare const cilSad: string[];
export declare const cilRunning: string[];
export declare const cilSatelite: string[];
export declare const cilSchool: string[];
export declare const cilScanner: string[];
export declare const cilSave: string[];
export declare const cilScooter: string[];
export declare const cilScreenDeskopSlash: string[];
export declare const cilScreenDesktop: string[];
export declare const cilScreenHorizontal: string[];
export declare const cilScreenLandscape: string[];
export declare const cilScreenLockHorizontal: string[];
export declare const cilScreenLockLandscape: string[];
export declare const cilScreenLockPortrait: string[];
export declare const cilScreenLockRotation: string[];
export declare const cilScreenMirroring: string[];
export declare const cilScreenPortrait: string[];
export declare const cilScreenLockVertical: string[];
export declare const cilScreenRotation: string[];
export declare const cilScreenSmartphone: string[];
export declare const cilScreenVertical: string[];
export declare const cilScript: string[];
export declare const cilScrubber: string[];
export declare const cilSdcard: string[];
export declare const cilSearch: string[];
export declare const cilLibrary: string[];
export declare const cilSelectAll: string[];
export declare const cilSend: string[];
export declare const cilSelect: string[];
export declare const cilSettings: string[];
export declare const cilShareAll: string[];
export declare const cilShareBoxed: string[];
export declare const cilShareAlt: string[];
export declare const cilShieldAlt: string[];
export declare const cilShare: string[];
export declare const cilShieldCheck: string[];
export declare const cilShieldPlus: string[];
export declare const cilShieldSlash: string[];
export declare const cilShieldMinus: string[];
export declare const cilShieldX: string[];
export declare const cilShield: string[];
export declare const cilShopMediaTwo: string[];
export declare const cilSecurity: string[];
export declare const cilShortText: string[];
export declare const cilShopMedia: string[];
export declare const cilSignalCellular0: string[];
export declare const cilShower: string[];
export declare const cilSignLanguage: string[];
export declare const cilSignalCellular2: string[];
export declare const cilSignalCellular1: string[];
export declare const cilSignalCellular3: string[];
export declare const cilSignalCellular4: string[];
export declare const cilSignalCellularNoInternet0: string[];
export declare const cilSignalCellularNoInternet1: string[];
export declare const cilSignalCellularNoInternet4: string[];
export declare const cilSignalCellularNoInternet2: string[];
export declare const cilSignalCellularNoInternet3: string[];
export declare const cilSignalCellularOff: string[];
export declare const cilSignalOff: string[];
export declare const cilSignal: string[];
export declare const cilSignpost: string[];
export declare const cilSimSlash: string[];
export declare const cilSim: string[];
export declare const cilSitemap: string[];
export declare const cilSlowMotion: string[];
export declare const cilSmilePlus: string[];
export declare const cilSmile: string[];
export declare const cilSmokeFree: string[];
export declare const cilSmokeSlash: string[];
export declare const cilSmoke: string[];
export declare const cilSmokingRoom: string[];
export declare const cilSoccer: string[];
export declare const cilSofa: string[];
export declare const cilSorroundSound: string[];
export declare const cilSortAlphaUp: string[];
export declare const cilSortAscending: string[];
export declare const cilSortAlphaDown: string[];
export declare const cilSortDescending: string[];
export declare const cilSortNumericDown: string[];
export declare const cilSortNumericUp: string[];
export declare const cilSpaceBar: string[];
export declare const cilSpa: string[];
export declare const cilSpeakerGroup: string[];
export declare const cilSpeaker: string[];
export declare const cilSpeak: string[];
export declare const cilSpeechNotesSlash: string[];
export declare const cilSpeechNotes: string[];
export declare const cilSpeechBubble: string[];
export declare const cilSpeech: string[];
export declare const cilSpeedometer: string[];
export declare const cilSpreadsheet: string[];
export declare const cilSquare: string[];
export declare const cilStarHalf: string[];
export declare const cilStarCircle: string[];
export declare const cilStar: string[];
export declare const cilStorage: string[];
export declare const cilStickyNote: string[];
export declare const cilStore: string[];
export declare const cilStream: string[];
export declare const cilStrikethrough: string[];
export declare const cilSubtitles: string[];
export declare const cilSubway: string[];
export declare const cilSwapHorizontalCircle: string[];
export declare const cilSwapVerticalCircle: string[];
export declare const cilSwapVertical: string[];
export declare const cilSwimming: string[];
export declare const cilSwapHorizontal: string[];
export declare const cilSyncProblem: string[];
export declare const cilSyncDisabled: string[];
export declare const cilTablet: string[];
export declare const cilSync: string[];
export declare const cilTennisBall: string[];
export declare const cilTask: string[];
export declare const cilTerminal: string[];
export declare const cilTaxi: string[];
export declare const cilTennis: string[];
export declare const cilTerrain: string[];
export declare const cilTextDirectionLtr: string[];
export declare const cilTextDirectionRtl: string[];
export declare const cilTextHeight: string[];
export declare const cilTextRotateVertical: string[];
export declare const cilTextFormatClear: string[];
export declare const cilTextRotationUp: string[];
export declare const cilTextRotationDown: string[];
export declare const cilTextSize: string[];
export declare const cilTextRotationNone: string[];
export declare const cilTextSquare: string[];
export declare const cilTextShapes: string[];
export declare const cilTextWidth: string[];
export declare const cilTextStrike: string[];
export declare const cilTimeline: string[];
export declare const cilText: string[];
export declare const cilTimer: string[];
export declare const cilToggleOn: string[];
export declare const cilToilet: string[];
export declare const cilToll: string[];
export declare const cilTouchApp: string[];
export declare const cilToggleOff: string[];
export declare const cilTraffic: string[];
export declare const cilTrainAlt: string[];
export declare const cilTrain: string[];
export declare const cilTransferWithinAStation: string[];
export declare const cilTram: string[];
export declare const cilTransfer: string[];
export declare const cilTranslate: string[];
export declare const cilTrashAlt: string[];
export declare const cilTrashArrowUp: string[];
export declare const cilTrashSweep: string[];
export declare const cilTrashX: string[];
export declare const cilTrash: string[];
export declare const cilTriangle: string[];
export declare const cilTruck: string[];
export declare const cilTvDvr: string[];
export declare const cilTty: string[];
export declare const cilTvLive: string[];
export declare const cilTvSlash: string[];
export declare const cilUnderline: string[];
export declare const cilTv: string[];
export declare const cilUpdate: string[];
export declare const cilUniversalAccess: string[];
export declare const cilUsb: string[];
export declare const cilUserFemale: string[];
export declare const cilUserUnfollow: string[];
export declare const cilUserFollow: string[];
export declare const cilUserSecret: string[];
export declare const cilUser: string[];
export declare const cilVector: string[];
export declare const cilVericalSplit: string[];
export declare const cilVerticalAlignBottom: string[];
export declare const cilVerticalAlignCenter: string[];
export declare const cilVerticalAlignTop: string[];
export declare const cilVideoLibrary: string[];
export declare const cilVideoLabel: string[];
export declare const cilVideoMissed: string[];
export declare const cilVideoPlus: string[];
export declare const cilVideoSlash: string[];
export declare const cilVideo: string[];
export declare const cilVideoSwitch: string[];
export declare const cilVideogame: string[];
export declare const cilViewAgenda: string[];
export declare const cilViewArray: string[];
export declare const cilViewCarousel: string[];
export declare const cilViewColumn: string[];
export declare const cilViewModule: string[];
export declare const cilViewQuilt: string[];
export declare const cilViewStream: string[];
export declare const cilVoiceOverRecord: string[];
export declare const cilVoiceOverSlash: string[];
export declare const cilVoice: string[];
export declare const cilVoicemail: string[];
export declare const cilVolumeHigh: string[];
export declare const cilVolumeLow: string[];
export declare const cilVolumeOff: string[];
export declare const cilVote: string[];
export declare const cilWalk: string[];
export declare const cilWallet: string[];
export declare const cilWallpaper: string[];
export declare const cilWarning: string[];
export declare const cilWatch: string[];
export declare const cilWaves: string[];
export declare const cilWc: string[];
export declare const cilWeights: string[];
export declare const cilWeightlifitng: string[];
export declare const cilWheelchair: string[];
export declare const cilWifiLock: string[];
export declare const cilWidgets: string[];
export declare const cilWifiSignal0: string[];
export declare const cilWifiSignal1: string[];
export declare const cilWifiSignal2: string[];
export declare const cilWifiSignal3: string[];
export declare const cilWifiSignal4: string[];
export declare const cilWifiSignalLock0: string[];
export declare const cilWifiSignalLock1: string[];
export declare const cilWifiSignalLock3: string[];
export declare const cilWifiSignalLock4: string[];
export declare const cilWifi: string[];
export declare const cilWifiSignalOff: string[];
export declare const cilWindowMaximize: string[];
export declare const cilWindowMinimize: string[];
export declare const cilWindow: string[];
export declare const cilWindowRestore: string[];
export declare const cilWrapText: string[];
export declare const cilXCircle: string[];
export declare const cilXSquare: string[];
export declare const cilX: string[];
export declare const cilYenCircleSlash: string[];
export declare const cilWifiSignalLock2: string[];
export declare const cilYenCircle: string[];
export declare const cilYenSlash: string[];
export declare const cilYen: string[];
export declare const cilZoomOut: string[];
export declare const cilZoom: string[];
export declare const cilZoomIn: string[];