export declare const solidSet: {
  "cis3dRotate": string[];
  "cis3d": string[];
  "cis4k": string[];
  "cisAccessibility": string[];
  "cisAccessible": string[];
  "cisAccountLogout": string[];
  "cisActionRedo": string[];
  "cisActionUndo": string[];
  "cisAddressBook": string[];
  "cisAddressCard": string[];
  "cisAirplaneModeOff": string[];
  "cisAirplaneMode": string[];
  "cisAirplay": string[];
  "cisAlarmAdd": string[];
  "cisAlarmOff": string[];
  "cisAlarmOn": string[];
  "cisAlarmSnooze": string[];
  "cisAlarm": string[];
  "cisAlbum": string[];
  "cisAlignCenter": string[];
  "cisAlignLeft": string[];
  "cisAlignRight": string[];
  "cisAmericanFootball": string[];
  "cisAnimal": string[];
  "cisAperture": string[];
  "cisApplicationsSettings": string[];
  "cisApple": string[];
  "cisApplications": string[];
  "cisApps": string[];
  "cisArchive": string[];
  "cisAppsSettings": string[];
  "cisArrowBottom": string[];
  "cisArrowCircleLeft": string[];
  "cisArrowCircleBottom": string[];
  "cisArrowCircleRight": string[];
  "cisArrowCircleTop": string[];
  "cisArrowLeft": string[];
  "cisArrowRight": string[];
  "cisArrowThickBottom": string[];
  "cisArrowThickCircleDown": string[];
  "cisArrowThickCircleLeft": string[];
  "cisArrowThickCircleRight": string[];
  "cisArrowThickCircleUp": string[];
  "cisArrowThickFromBottom": string[];
  "cisArrowThickFromLeft": string[];
  "cisArrowThickFromRight": string[];
  "cisArrowThickFromTop": string[];
  "cisArrowThickLeft": string[];
  "cisArrowThickRight": string[];
  "cisArrowThickSquareLeft": string[];
  "cisArrowThickSquareDown": string[];
  "cisArrowThickSquareRight": string[];
  "cisArrowThickSquareUp": string[];
  "cisArrowThickToBottom": string[];
  "cisArrowThickToLeft": string[];
  "cisArrowThickToRight": string[];
  "cisArrowThickToTop": string[];
  "cisArrowThickTop": string[];
  "cisArrowTop": string[];
  "cisArtTrack": string[];
  "cisAssistiveListeningSystem": string[];
  "cisAsterisk": string[];
  "cisAsteriskCircle": string[];
  "cisAt": string[];
  "cisAudioDescription": string[];
  "cisAudioSpectrum": string[];
  "cisAudio": string[];
  "cisAvTimer": string[];
  "cisBabyCarriage": string[];
  "cisBaby": string[];
  "cisBackspace": string[];
  "cisBadge": string[];
  "cisBalanceScaleRight": string[];
  "cisBalanceScaleLeft": string[];
  "cisBalanceScale": string[];
  "cisBan": string[];
  "cisBank": string[];
  "cisBarChart": string[];
  "cisBarcode": string[];
  "cisBaseball": string[];
  "cisBasketArrowDown": string[];
  "cisBasketLoaded": string[];
  "cisBasketPlus": string[];
  "cisBasket": string[];
  "cisBasketball": string[];
  "cisBath": string[];
  "cisBathroom": string[];
  "cisBattery1": string[];
  "cisBattery0": string[];
  "cisBattery2": string[];
  "cisBattery4": string[];
  "cisBattery3": string[];
  "cisBattery5": string[];
  "cisBatteryAlt0": string[];
  "cisBatteryAlert": string[];
  "cisBatteryAlt2": string[];
  "cisBatteryAlt1": string[];
  "cisBatteryAlt3": string[];
  "cisBatteryAltEmpty": string[];
  "cisBatteryAltFull": string[];
  "cisBatteryAltSlash": string[];
  "cisBatteryCharge": string[];
  "cisBatteryEmpty": string[];
  "cisBatteryFull": string[];
  "cisBatterySlash": string[];
  "cisBatteryUnknown": string[];
  "cisBeachAccess": string[];
  "cisBeaker": string[];
  "cisBed": string[];
  "cisBellExclamation": string[];
  "cisBellPlus": string[];
  "cisBellRing": string[];
  "cisBellSlash": string[];
  "cisBikeAlt": string[];
  "cisBike": string[];
  "cisBirthdayCake": string[];
  "cisBlind": string[];
  "cisBell": string[];
  "cisBluetoothConnected": string[];
  "cisBluetoothSearching": string[];
  "cisBluetoothSettings": string[];
  "cisBluetoothSlash": string[];
  "cisBluetooth": string[];
  "cisBlurCircular": string[];
  "cisBlurLinear": string[];
  "cisBlurSlash": string[];
  "cisBlur": string[];
  "cisBoatAlt": string[];
  "cisBoat": string[];
  "cisBold": string[];
  "cisBoltAlt": string[];
  "cisBolt": string[];
  "cisBoltCircle": string[];
  "cisBookOpen": string[];
  "cisBook": string[];
  "cisBookmark": string[];
  "cisBookmarks": string[];
  "cisBorderAll": string[];
  "cisBorderClear": string[];
  "cisBorderHorizontal": string[];
  "cisBorderBottom": string[];
  "cisBorderInner": string[];
  "cisBorderLeft": string[];
  "cisBorderOuter": string[];
  "cisBorderRight": string[];
  "cisBorderStyle": string[];
  "cisBorderTop": string[];
  "cisBowlingPins": string[];
  "cisBowling": string[];
  "cisBoxAlt": string[];
  "cisBox": string[];
  "cisBraille": string[];
  "cisBrandingWatermark": string[];
  "cisBriefcaseArrowLeft": string[];
  "cisBriefcaseArrowRight": string[];
  "cisBorderVertical": string[];
  "cisBriefcase": string[];
  "cisBrightnessAuto": string[];
  "cisBrightnessHigh": string[];
  "cisBrightnessLow": string[];
  "cisBrightnessMedium": string[];
  "cisBriefcaseSlash": string[];
  "cisBritishPoundCircle": string[];
  "cisBritishPoundSlash": string[];
  "cisBritishPound": string[];
  "cisBroadcastTower": string[];
  "cisBrowser": string[];
  "cisBrushAlt": string[];
  "cisBrush": string[];
  "cisBug": string[];
  "cisBrightness": string[];
  "cisBuildingBusinessSlash": string[];
  "cisBuildingBusiness": string[];
  "cisBuildingSlash": string[];
  "cisBuilding": string[];
  "cisBullhorn": string[];
  "cisBurger": string[];
  "cisBusAlt": string[];
  "cisBusTimer": string[];
  "cisBus": string[];
  "cisCalculator": string[];
  "cisCalendarAlt": string[];
  "cisCalendarCheck": string[];
  "cisCalendarMinus": string[];
  "cisCalendarEvent": string[];
  "cisCalendarNote": string[];
  "cisCalendarPlus": string[];
  "cisCalendarToday": string[];
  "cisCalendarTimes": string[];
  "cisCalendarViewDay": string[];
  "cisCalendar": string[];
  "cisCallMade": string[];
  "cisCallMerge": string[];
  "cisCallMissedOutgoing": string[];
  "cisCallMissed": string[];
  "cisCallSplit": string[];
  "cisCallSwapCalls": string[];
  "cisCallReceived": string[];
  "cisCallToAction": string[];
  "cisCameraControl": string[];
  "cisCameraEnhance": string[];
  "cisCameraPlus": string[];
  "cisCameraRoll": string[];
  "cisCameraSwitch": string[];
  "cisCamera": string[];
  "cisCarAlt": string[];
  "cisCar": string[];
  "cisCardGiftcard": string[];
  "cisCardMembership": string[];
  "cisCardTravel": string[];
  "cisCaretBottom": string[];
  "cisCaretLeft": string[];
  "cisCaretRight": string[];
  "cisCaretTop": string[];
  "cisCartArrowDown": string[];
  "cisCartLoaded": string[];
  "cisCartPlus": string[];
  "cisCartSlash": string[];
  "cisCart": string[];
  "cisCash": string[];
  "cisCasino": string[];
  "cisCastConnected": string[];
  "cisCastForEducation": string[];
  "cisCast": string[];
  "cisCat": string[];
  "cisCc": string[];
  "cisCenterFocusWeak": string[];
  "cisCenterFocus": string[];
  "cisChalkboardTeacher": string[];
  "cisChartArea": string[];
  "cisChartBubble": string[];
  "cisChartDonut": string[];
  "cisChartLine": string[];
  "cisChartMultiline": string[];
  "cisChartPie": string[];
  "cisChartShow": string[];
  "cisChartTable": string[];
  "cisChart": string[];
  "cisChatBubble": string[];
  "cisChatSquare": string[];
  "cisCheckAlt": string[];
  "cisCheckCircle": string[];
  "cisCheckDoubleAlt": string[];
  "cisCheckDouble": string[];
  "cisCheck": string[];
  "cisChevronBottom": string[];
  "cisChevronBottomAlt": string[];
  "cisChevronCircleDownAlt": string[];
  "cisChevronCircleDown": string[];
  "cisChevronCircleLeftAlt": string[];
  "cisChevronCircleLeft": string[];
  "cisChevronCircleRightAlt": string[];
  "cisChevronCircleRight": string[];
  "cisChevronCircleUpAlt": string[];
  "cisChevronCircleUp": string[];
  "cisChevronDoubleDownAlt": string[];
  "cisChevronDoubleDown": string[];
  "cisChevronDoubleLeftAlt": string[];
  "cisChevronDoubleLeft": string[];
  "cisChevronDoubleRight": string[];
  "cisChevronDoubleRightAlt": string[];
  "cisChevronDoubleUpAlt": string[];
  "cisChevronDoubleUp": string[];
  "cisChevronLeftAlt": string[];
  "cisChevronLeft": string[];
  "cisChevronRightAlt": string[];
  "cisChevronSquareDownAlt": string[];
  "cisChevronRight": string[];
  "cisChevronSquareDown": string[];
  "cisChevronSquareLeftAlt": string[];
  "cisChevronSquareLeft": string[];
  "cisChevronSquareRightAlt": string[];
  "cisChevronSquareRight": string[];
  "cisChevronSquareUpAlt": string[];
  "cisChevronSquareUp": string[];
  "cisChevronTopAlt": string[];
  "cisChevronTop": string[];
  "cisChildFriendly": string[];
  "cisChild": string[];
  "cisCircle": string[];
  "cisClearAll": string[];
  "cisCity": string[];
  "cisClipboard": string[];
  "cisClock": string[];
  "cisClone": string[];
  "cisClosedCaptioning": string[];
  "cisCloudCheck": string[];
  "cisCloudCircle": string[];
  "cisCloudDownload": string[];
  "cisCloudSlash": string[];
  "cisCloudUpload": string[];
  "cisCloud": string[];
  "cisCode": string[];
  "cisCoffee": string[];
  "cisCog": string[];
  "cisColorBorder": string[];
  "cisColorFill": string[];
  "cisColorPalette": string[];
  "cisColumns": string[];
  "cisCommand": string[];
  "cisCommentBubbleCheck": string[];
  "cisCommentBubbleEdit": string[];
  "cisCommentBubbleExclamation": string[];
  "cisCommentBubbleLines": string[];
  "cisCommentBubbleMinus": string[];
  "cisCommentBubblePlus": string[];
  "cisCommentBubbleQuestion": string[];
  "cisCommentBubbleSmile": string[];
  "cisCommentBubbleX": string[];
  "cisCommentBubble": string[];
  "cisCommentSquareCheck": string[];
  "cisCommentSquareEdit": string[];
  "cisCommentSquareExclamation": string[];
  "cisCommentSquareImage": string[];
  "cisCommentSquareLines": string[];
  "cisCommentSquareMinus": string[];
  "cisCommentSquarePlus": string[];
  "cisCommentSquareRateReview": string[];
  "cisCommentSquareSmile": string[];
  "cisCommentSquareX": string[];
  "cisCommentSquare": string[];
  "cisCommute": string[];
  "cisCompare": string[];
  "cisCompassCalibration": string[];
  "cisCompassSlash": string[];
  "cisCompass": string[];
  "cisCompressWide": string[];
  "cisCompress": string[];
  "cisContactMail": string[];
  "cisContactPhone": string[];
  "cisContact": string[];
  "cisContacts": string[];
  "cisContrast": string[];
  "cisControl": string[];
  "cisCopy": string[];
  "cisCoreFree": string[];
  "cisCoreLogoFull": string[];
  "cisCoreLogo": string[];
  "cisCorePro": string[];
  "cisCreditCard": string[];
  "cisCouch": string[];
  "cisCropRotate": string[];
  "cisCrop": string[];
  "cisCursorMove": string[];
  "cisCursor": string[];
  "cisCut": string[];
  "cisDataTransferDown": string[];
  "cisDeaf": string[];
  "cisDataTransferUp": string[];
  "cisDelete": string[];
  "cisDescription": string[];
  "cisDeveloperBoard": string[];
  "cisDeviceUnknown": string[];
  "cisDevicesImportant": string[];
  "cisDevicesOther": string[];
  "cisDevicesSlash": string[];
  "cisDevices": string[];
  "cisDial": string[];
  "cisDialpad": string[];
  "cisDiamond": string[];
  "cisDinner": string[];
  "cisDirections": string[];
  "cisDisabled": string[];
  "cisDns": string[];
  "cisDock": string[];
  "cisDocument": string[];
  "cisDog": string[];
  "cisDollarCircleSlash": string[];
  "cisDollarCircle": string[];
  "cisDollarSlash": string[];
  "cisDollar": string[];
  "cisDonate": string[];
  "cisDoor": string[];
  "cisDoubleQuoteSansLeft": string[];
  "cisDoubleQuoteSansRight": string[];
  "cisDoubleQuoteSerifLeft": string[];
  "cisDoubleQuoteSerifRight": string[];
  "cisDrinkAlcohol": string[];
  "cisDrink": string[];
  "cisDropSlash": string[];
  "cisDrop": string[];
  "cisDvr": string[];
  "cisEar": string[];
  "cisEco": string[];
  "cisEducation": string[];
  "cisElevator": string[];
  "cisEnergyCircle": string[];
  "cisEnergy": string[];
  "cisEnvelopeClosed": string[];
  "cisEnvelopeLetter": string[];
  "cisEnvelopeOpen": string[];
  "cisEnvelopeMinus": string[];
  "cisEnvelopePlus": string[];
  "cisEqualizer": string[];
  "cisEthernetAlt": string[];
  "cisEthernet": string[];
  "cisEuroCircleSlash": string[];
  "cisEuroCircle": string[];
  "cisEuroSlash": string[];
  "cisEuro": string[];
  "cisEvStation": string[];
  "cisExcerpt": string[];
  "cisExclamationCircle": string[];
  "cisExclamation": string[];
  "cisExitToApp": string[];
  "cisExpandLeft": string[];
  "cisExpandDown": string[];
  "cisExpandRight": string[];
  "cisExpandUp": string[];
  "cisExposure": string[];
  "cisExternalLink": string[];
  "cisEyeSlash": string[];
  "cisEye": string[];
  "cisEyedropper": string[];
  "cisFace": string[];
  "cisFaceDead": string[];
  "cisFactorySlash": string[];
  "cisFastfood": string[];
  "cisFax": string[];
  "cisFactory": string[];
  "cisFeaturedPlaylist": string[];
  "cisFeaturedVideo": string[];
  "cisFiberDvr": string[];
  "cisFiberManual": string[];
  "cisFiberNew": string[];
  "cisFiberPin": string[];
  "cisFileAcrobat": string[];
  "cisFiberSmart": string[];
  "cisFileAdd": string[];
  "cisFileArchive": string[];
  "cisFileAudio": string[];
  "cisFileCode": string[];
  "cisFileDoc": string[];
  "cisFileExcel": string[];
  "cisFileImage": string[];
  "cisFilePdf": string[];
  "cisFilePpt": string[];
  "cisFilePowerpoint": string[];
  "cisFileVideo": string[];
  "cisFileWord": string[];
  "cisFileXls": string[];
  "cisFile": string[];
  "cisFilterFrames": string[];
  "cisFilterPhoto": string[];
  "cisFilter": string[];
  "cisFindInPage": string[];
  "cisFindReplace": string[];
  "cisFire": string[];
  "cisFingerprint": string[];
  "cisFlagAlt": string[];
  "cisFlagRectangle": string[];
  "cisFlagTriangle": string[];
  "cisFlag": string[];
  "cisFlame": string[];
  "cisFlash": string[];
  "cisFlightTakeoff": string[];
  "cisFlightLand": string[];
  "cisFlipToFront": string[];
  "cisFlipToBack": string[];
  "cisFlower": string[];
  "cisFolderAlt": string[];
  "cisFolderOpen": string[];
  "cisFolderPlus": string[];
  "cisFolderShared": string[];
  "cisFolderSpecial": string[];
  "cisFlip": string[];
  "cisFolder": string[];
  "cisFont": string[];
  "cisFootball": string[];
  "cisFork": string[];
  "cisFridge": string[];
  "cisFrown": string[];
  "cisFullscreenExit": string[];
  "cisFullscreen": string[];
  "cisFunctionsAlt": string[];
  "cisFunctions": string[];
  "cisGamepad": string[];
  "cisGarage": string[];
  "cisGem": string[];
  "cisGif": string[];
  "cisGift": string[];
  "cisGlass": string[];
  "cisGlobeAltLock": string[];
  "cisGlobeAlt": string[];
  "cisGlobeLock": string[];
  "cisGlobe": string[];
  "cisGolfAlt": string[];
  "cisGolf": string[];
  "cisGradient": string[];
  "cisGrain": string[];
  "cisGraph": string[];
  "cisGridSlash": string[];
  "cisGrid": string[];
  "cisHamburgerMenu": string[];
  "cisHappy": string[];
  "cisHardDrive": string[];
  "cisHd": string[];
  "cisHdr": string[];
  "cisHeader": string[];
  "cisHeadphonesMic": string[];
  "cisHeadphonesMute": string[];
  "cisHeadphones": string[];
  "cisHealing": string[];
  "cisHighQuality": string[];
  "cisHeart": string[];
  "cisHighlighter": string[];
  "cisHighligt": string[];
  "cisHistory": string[];
  "cisHome": string[];
  "cisHospital": string[];
  "cisHotTub": string[];
  "cisHotel": string[];
  "cisHourglass": string[];
  "cisHouse": string[];
  "cisHq": string[];
  "cisHttp": string[];
  "cisHttps": string[];
  "cisIdBadge": string[];
  "cisIdCard": string[];
  "cisImageBroken": string[];
  "cisImagePlus": string[];
  "cisImage": string[];
  "cisImages": string[];
  "cisInboxIn": string[];
  "cisInboxOut": string[];
  "cisInbox": string[];
  "cisIndentDecrease": string[];
  "cisIndentIncrease": string[];
  "cisIndustrySlash": string[];
  "cisInfinity": string[];
  "cisIndustry": string[];
  "cisInfo": string[];
  "cisInputAntenna": string[];
  "cisInputComponent": string[];
  "cisInputHdmi": string[];
  "cisInputPowerOff": string[];
  "cisInputPower": string[];
  "cisInput": string[];
  "cisInputSvideo": string[];
  "cisInstitution": string[];
  "cisInvert": string[];
  "cisItalic": string[];
  "cisJustifyCenter": string[];
  "cisJustifyLeft": string[];
  "cisJustifyRight": string[];
  "cisKeyAlt": string[];
  "cisKey": string[];
  "cisKeyboardHide": string[];
  "cisLanguage": string[];
  "cisLan": string[];
  "cisKeyboard": string[];
  "cisLaptop": string[];
  "cisLaundry": string[];
  "cisKitchen": string[];
  "cisLayers": string[];
  "cisLayersSlash": string[];
  "cisLeaf": string[];
  "cisLemon": string[];
  "cisLevelDown": string[];
  "cisLevelUp": string[];
  "cisLibraryAdd": string[];
  "cisLibraryBookmark": string[];
  "cisLibraryBooks": string[];
  "cisLibraryBuilding": string[];
  "cisLibraryMusic": string[];
  "cisHdrSlash": string[];
  "cisLibrary": string[];
  "cisLightbulb": string[];
  "cisLifeRing": string[];
  "cisLineSpacing": string[];
  "cisLineStyle": string[];
  "cisLinkAlt": string[];
  "cisLineWeight": string[];
  "cisLinkBroken": string[];
  "cisLinkIntact": string[];
  "cisLinkSlash": string[];
  "cisLink": string[];
  "cisListFilter": string[];
  "cisListHighPriority": string[];
  "cisListLowPriority": string[];
  "cisListNumberedRtl": string[];
  "cisListNumbered": string[];
  "cisListRich": string[];
  "cisList": string[];
  "cisLocationGpsFixed": string[];
  "cisLocationGpsOff": string[];
  "cisLocationGps": string[];
  "cisLocationPinCheck": string[];
  "cisLocationPinEdit": string[];
  "cisLocationPinPlus": string[];
  "cisLocationPinSlash": string[];
  "cisLocationPin": string[];
  "cisLockLocked": string[];
  "cisLockMinus": string[];
  "cisLockPlus": string[];
  "cisLockUnlocked": string[];
  "cisLocomotive": string[];
  "cisLoop1": string[];
  "cisLoopCircular": string[];
  "cisLoopSquare": string[];
  "cisLoop": string[];
  "cisLowVision": string[];
  "cisLoyalty": string[];
  "cisMagnifyingGlass": string[];
  "cisMail": string[];
  "cisMailbox": string[];
  "cisMapAlt": string[];
  "cisMap": string[];
  "cisMediaEjectCircle": string[];
  "cisMediaEjectSquare": string[];
  "cisMediaEject": string[];
  "cisMediaPauseCircle": string[];
  "cisMediaPauseSquare": string[];
  "cisMediaPause": string[];
  "cisMediaPlaySquare": string[];
  "cisMediaPlayCircle": string[];
  "cisMediaPlay": string[];
  "cisMediaRecordCircle": string[];
  "cisMediaRecordSquare": string[];
  "cisMediaRecord": string[];
  "cisMediaSkipBackwardSquare": string[];
  "cisMediaSkipBackwardCircle": string[];
  "cisMediaSkipBackward": string[];
  "cisMediaSkipForwardCircle": string[];
  "cisMediaSkipForwardSquare": string[];
  "cisMediaSkipForward": string[];
  "cisMediaStepBackwardCircle": string[];
  "cisMediaStepBackwardSquare": string[];
  "cisMediaStepBackward": string[];
  "cisMediaStepForwardCircle": string[];
  "cisMediaStepForwardSquare": string[];
  "cisMediaStepForward": string[];
  "cisMediaStopCircle": string[];
  "cisMediaStopSquare": string[];
  "cisMediaStop": string[];
  "cisMedicalCross": string[];
  "cisMemory": string[];
  "cisMenu": string[];
  "cisMeh": string[];
  "cisMicAlt": string[];
  "cisMicSettings": string[];
  "cisMicSlash": string[];
  "cisMic": string[];
  "cisMicrochip": string[];
  "cisMicrophoneAlt": string[];
  "cisMicrophoneSlash": string[];
  "cisMicrophoneSettings": string[];
  "cisMicrophone": string[];
  "cisMinusCircle": string[];
  "cisMinusSquare": string[];
  "cisMinus": string[];
  "cisMobileArrowAdd": string[];
  "cisMobileArrowRemove": string[];
  "cisMobileCheck": string[];
  "cisMobileDeveloperMode": string[];
  "cisMobileLandscape": string[];
  "cisMobileLock": string[];
  "cisMobileMinus": string[];
  "cisMobilePlus": string[];
  "cisMobilePortrait": string[];
  "cisMobileSettings": string[];
  "cisMobileSlash": string[];
  "cisMobileSms": string[];
  "cisMobileSpeaker": string[];
  "cisMobileX": string[];
  "cisMobile": string[];
  "cisMoneyBillAlt": string[];
  "cisMoneyBillAlt2": string[];
  "cisMoneyBill": string[];
  "cisMobileVolume": string[];
  "cisMonitor": string[];
  "cisMoney": string[];
  "cisMoodBad": string[];
  "cisMoodGood": string[];
  "cisMoodVeryGood": string[];
  "cisMore": string[];
  "cisMoodVeryBad": string[];
  "cisMotorbike": string[];
  "cisMouseAlt": string[];
  "cisMouse": string[];
  "cisMouthSlash": string[];
  "cisMouth": string[];
  "cisMove": string[];
  "cisMovieAlt": string[];
  "cisMovie": string[];
  "cisMugTea": string[];
  "cisMug": string[];
  "cisMusicNoteAlt": string[];
  "cisMusicNoteSlash": string[];
  "cisMusicNote": string[];
  "cisMusicVideo": string[];
  "cisNetworkCheck": string[];
  "cisNewReleases": string[];
  "cisNew": string[];
  "cisNewspaper": string[];
  "cisNoteAdd": string[];
  "cisNote": string[];
  "cisNotes": string[];
  "cisObjectUngroup": string[];
  "cisObjectGroup": string[];
  "cisOpacity": string[];
  "cisOptions": string[];
  "cisOpentype": string[];
  "cisOverscanSettings": string[];
  "cisOven": string[];
  "cisOverscan": string[];
  "cisPageRestore": string[];
  "cisPage": string[];
  "cisPageview": string[];
  "cisPaintBucket": string[];
  "cisPaint": string[];
  "cisPaperPlane": string[];
  "cisPaperclip": string[];
  "cisParagraph": string[];
  "cisParking": string[];
  "cisPaw": string[];
  "cisPenAlt": string[];
  "cisPenFancy": string[];
  "cisPenNib": string[];
  "cisPen": string[];
  "cisPencil": string[];
  "cisPeople": string[];
  "cisPeople_Plus": string[];
  "cisPercent": string[];
  "cisPersonFemale": string[];
  "cisPerson": string[];
  "cisPetrolStation": string[];
  "cisPhoneBluetooth": string[];
  "cisPhoneCallEnd": string[];
  "cisPhoneCall": string[];
  "cisPhoneCallback": string[];
  "cisPhoneCheck": string[];
  "cisPhoneForward": string[];
  "cisPhoneInTalk": string[];
  "cisPhoneLock": string[];
  "cisPhoneMinus": string[];
  "cisPhoneMissed": string[];
  "cisPhonePaused": string[];
  "cisPhonePlus": string[];
  "cisPhoneRingVolume": string[];
  "cisPhoneSettings": string[];
  "cisPhoneSlash": string[];
  "cisPhoneSquare": string[];
  "cisPhoneVolume": string[];
  "cisPhoneX": string[];
  "cisPhone": string[];
  "cisPictureInPictureAlt": string[];
  "cisPictureInPicture": string[];
  "cisPin": string[];
  "cisPizza": string[];
  "cisPlant": string[];
  "cisPlaylistAddCheck": string[];
  "cisPlaylistAdd": string[];
  "cisPlaylistPlay": string[];
  "cisPlusCircle": string[];
  "cisPlusOne": string[];
  "cisPlusSquare": string[];
  "cisPlus": string[];
  "cisPool": string[];
  "cisPortableWifiOff": string[];
  "cisPortableWifi": string[];
  "cisPowerSettings": string[];
  "cisPowerStandby": string[];
  "cisPregnant": string[];
  "cisPrint": string[];
  "cisPrinterSlash": string[];
  "cisPrinter": string[];
  "cisPushchair": string[];
  "cisPuzzlePiece": string[];
  "cisPuzzle": string[];
  "cisQrCode": string[];
  "cisQueueAdd": string[];
  "cisQueueMusic": string[];
  "cisQueuePlayNext": string[];
  "cisQueueRemove": string[];
  "cisQueue": string[];
  "cisRadio": string[];
  "cisRandom": string[];
  "cisRailway": string[];
  "cisRecentActors": string[];
  "cisRectangle": string[];
  "cisRecycle": string[];
  "cisRemoteControl": string[];
  "cisReload": string[];
  "cisRemoteSettings": string[];
  "cisReplay": string[];
  "cisReport": string[];
  "cisReportSlash": string[];
  "cisResizeBoth": string[];
  "cisResizeHeight": string[];
  "cisResizeWidth": string[];
  "cisRestaurantMenu": string[];
  "cisRestaurant": string[];
  "cisRestore": string[];
  "cisRoomSlash": string[];
  "cisRoom": string[];
  "cisRouter": string[];
  "cisRoundedCorner": string[];
  "cisRowing": string[];
  "cisRssAlt": string[];
  "cisRssSquare": string[];
  "cisRss": string[];
  "cisRubleCircleSlash": string[];
  "cisRubleCircle": string[];
  "cisRubleSlash": string[];
  "cisRuble": string[];
  "cisRunning": string[];
  "cisSad": string[];
  "cisSatelite": string[];
  "cisSave": string[];
  "cisScanner": string[];
  "cisSchool": string[];
  "cisScooter": string[];
  "cisScreenDeskopSlash": string[];
  "cisScreenDesktop": string[];
  "cisScreenHorizontal": string[];
  "cisScreenLockHorizontal": string[];
  "cisScreenLandscape": string[];
  "cisScreenLockLandscape": string[];
  "cisScreenLockRotation": string[];
  "cisScreenMirroring": string[];
  "cisScreenLockVertical": string[];
  "cisScreenPortrait": string[];
  "cisScreenRotation": string[];
  "cisScreenSmartphone": string[];
  "cisScreenVertical": string[];
  "cisScript": string[];
  "cisScrubber": string[];
  "cisSdcard": string[];
  "cisScreenLockPortrait": string[];
  "cisSearch": string[];
  "cisSecurity": string[];
  "cisSelectAll": string[];
  "cisSelect": string[];
  "cisSend": string[];
  "cisSettings": string[];
  "cisShareAll": string[];
  "cisShareAlt": string[];
  "cisShareBoxed": string[];
  "cisShare": string[];
  "cisShieldAlt": string[];
  "cisShieldCheck": string[];
  "cisShieldMinus": string[];
  "cisShieldPlus": string[];
  "cisShieldSlash": string[];
  "cisShieldX": string[];
  "cisShield": string[];
  "cisShopMediaTwo": string[];
  "cisShopMedia": string[];
  "cisShortText": string[];
  "cisShower": string[];
  "cisSignLanguage": string[];
  "cisSignalCellular0": string[];
  "cisSignalCellular1": string[];
  "cisSignalCellular2": string[];
  "cisSignalCellular3": string[];
  "cisSignalCellular4": string[];
  "cisSignalCellularNoInternet0": string[];
  "cisSignalCellularNoInternet1": string[];
  "cisSignalCellularNoInternet2": string[];
  "cisSignalCellularNoInternet3": string[];
  "cisSignalCellularOff": string[];
  "cisSignalCellularNoInternet4": string[];
  "cisSignalCellularOff_1": string[];
  "cisSignpost": string[];
  "cisSimSlash": string[];
  "cisSim": string[];
  "cisSitemap": string[];
  "cisSlowMotion": string[];
  "cisSmilePlus": string[];
  "cisSmile": string[];
  "cisSmokeFree": string[];
  "cisSmokeSlash": string[];
  "cisSmoke": string[];
  "cisSmokingRoom": string[];
  "cisSoccer": string[];
  "cisSofa": string[];
  "cisSorroundSound": string[];
  "cisSortAlphaDown": string[];
  "cisSortAlphaUp": string[];
  "cisSortAscending": string[];
  "cisSortDescending": string[];
  "cisSortNumericDown": string[];
  "cisSortNumericUp": string[];
  "cisSpa": string[];
  "cisSpaceBar": string[];
  "cisSpeak": string[];
  "cisSpeakerGroup": string[];
  "cisSpeechBubble": string[];
  "cisSpeaker": string[];
  "cisSpeechNotes": string[];
  "cisSpeechNotesSlash": string[];
  "cisSpeech": string[];
  "cisSpeedometer": string[];
  "cisSpreadsheet": string[];
  "cisSquare": string[];
  "cisStarHalf": string[];
  "cisStarCircle": string[];
  "cisStar": string[];
  "cisStickyNote": string[];
  "cisStorage": string[];
  "cisStore": string[];
  "cisStrikethrough": string[];
  "cisStream": string[];
  "cisSubtitles": string[];
  "cisSubway": string[];
  "cisSwapHorizontalCircle": string[];
  "cisSwapHorizontal": string[];
  "cisSwapVerticalCircle": string[];
  "cisSwapVertical": string[];
  "cisSwimming": string[];
  "cisSyncDisabled": string[];
  "cisSyncProblem": string[];
  "cisSync": string[];
  "cisTablet": string[];
  "cisTag": string[];
  "cisTarget": string[];
  "cisTask": string[];
  "cisTaxi": string[];
  "cisTennisBall": string[];
  "cisTennis": string[];
  "cisTerminal": string[];
  "cisTerrain": string[];
  "cisTextDirectionLtr": string[];
  "cisTextDirectionRtl": string[];
  "cisTextFormatClear": string[];
  "cisTextHeight": string[];
  "cisTextRotateVertical": string[];
  "cisTextRotationDown": string[];
  "cisTextRotationNone": string[];
  "cisTextShapes": string[];
  "cisTextRotationUp": string[];
  "cisTextSize": string[];
  "cisTextSquare": string[];
  "cisTextStrike": string[];
  "cisTextWidth": string[];
  "cisText": string[];
  "cisTimeline": string[];
  "cisTimer": string[];
  "cisToggleOff": string[];
  "cisToggleOn": string[];
  "cisTags": string[];
  "cisToilet": string[];
  "cisTouchApp": string[];
  "cisToll": string[];
  "cisTraffic": string[];
  "cisTrain": string[];
  "cisTrainAlt": string[];
  "cisTram": string[];
  "cisTransferWithinAStation": string[];
  "cisTransfer": string[];
  "cisTranslate": string[];
  "cisTrashAlt": string[];
  "cisTrashArrowUp": string[];
  "cisTrashSweep": string[];
  "cisTrashX": string[];
  "cisTrash": string[];
  "cisTruck": string[];
  "cisTriangle": string[];
  "cisTvDvr": string[];
  "cisTty": string[];
  "cisTvLive": string[];
  "cisTvSlash": string[];
  "cisUnderline": string[];
  "cisTv": string[];
  "cisUpdate": string[];
  "cisUniversalAccess": string[];
  "cisUsb": string[];
  "cisUserFemale": string[];
  "cisSignal": string[];
  "cisUserFollow": string[];
  "cisUserSecret": string[];
  "cisUserUnfollow": string[];
  "cisUser": string[];
  "cisVericalSplit": string[];
  "cisVector": string[];
  "cisVerticalAlignCenter": string[];
  "cisVerticalAlignBottom": string[];
  "cisVerticalAlignTop": string[];
  "cisVideoLabel": string[];
  "cisVideoLibrary": string[];
  "cisVideoMissed": string[];
  "cisVideoPlus": string[];
  "cisVideoSlash": string[];
  "cisVideoSwitch": string[];
  "cisVideo": string[];
  "cisVideogame": string[];
  "cisViewAgenda": string[];
  "cisViewArray": string[];
  "cisViewCarousel": string[];
  "cisViewColumn": string[];
  "cisViewModule": string[];
  "cisViewQuilt": string[];
  "cisViewStream": string[];
  "cisVoiceOverSlash": string[];
  "cisVoiceOverRecord": string[];
  "cisVoice": string[];
  "cisVoicemail": string[];
  "cisVolumeHigh": string[];
  "cisVolumeLow": string[];
  "cisVolumeOff": string[];
  "cisVote": string[];
  "cisWalk": string[];
  "cisWallet": string[];
  "cisWallpaper": string[];
  "cisWarning": string[];
  "cisWatch": string[];
  "cisWaves": string[];
  "cisWc": string[];
  "cisWeightlifitng": string[];
  "cisWeights": string[];
  "cisWheelchair": string[];
  "cisWidgets": string[];
  "cisWifiSignal0": string[];
  "cisWifiLock": string[];
  "cisWifiSignal1": string[];
  "cisWifiSignal2": string[];
  "cisWifiSignal3": string[];
  "cisWifiSignal4": string[];
  "cisWifiSignalLock0": string[];
  "cisWifiSignalLock1": string[];
  "cisWifiSignalLock2": string[];
  "cisWifiSignalLock3": string[];
  "cisWifiSignalOff": string[];
  "cisWifiSignalLock4": string[];
  "cisWifi": string[];
  "cisWindowMaximize": string[];
  "cisWindowMinimize": string[];
  "cisWindowRestore": string[];
  "cisWindow": string[];
  "cisXCircle": string[];
  "cisWrapText": string[];
  "cisXSquare": string[];
  "cisX": string[];
  "cisYenCircleSlash": string[];
  "cisYenCircle": string[];
  "cisYenSlash": string[];
  "cisYen": string[];
  "cisZoomIn": string[];
  "cisZoomOut": string[];
  "cisZoom": string[];
}
export declare const cis3dRotate: string[];
export declare const cis3d: string[];
export declare const cis4k: string[];
export declare const cisAccessibility: string[];
export declare const cisAccessible: string[];
export declare const cisAccountLogout: string[];
export declare const cisActionRedo: string[];
export declare const cisActionUndo: string[];
export declare const cisAddressBook: string[];
export declare const cisAddressCard: string[];
export declare const cisAirplaneModeOff: string[];
export declare const cisAirplaneMode: string[];
export declare const cisAirplay: string[];
export declare const cisAlarmAdd: string[];
export declare const cisAlarmOff: string[];
export declare const cisAlarmOn: string[];
export declare const cisAlarmSnooze: string[];
export declare const cisAlarm: string[];
export declare const cisAlbum: string[];
export declare const cisAlignCenter: string[];
export declare const cisAlignLeft: string[];
export declare const cisAlignRight: string[];
export declare const cisAmericanFootball: string[];
export declare const cisAnimal: string[];
export declare const cisAperture: string[];
export declare const cisApplicationsSettings: string[];
export declare const cisApple: string[];
export declare const cisApplications: string[];
export declare const cisApps: string[];
export declare const cisArchive: string[];
export declare const cisAppsSettings: string[];
export declare const cisArrowBottom: string[];
export declare const cisArrowCircleLeft: string[];
export declare const cisArrowCircleBottom: string[];
export declare const cisArrowCircleRight: string[];
export declare const cisArrowCircleTop: string[];
export declare const cisArrowLeft: string[];
export declare const cisArrowRight: string[];
export declare const cisArrowThickBottom: string[];
export declare const cisArrowThickCircleDown: string[];
export declare const cisArrowThickCircleLeft: string[];
export declare const cisArrowThickCircleRight: string[];
export declare const cisArrowThickCircleUp: string[];
export declare const cisArrowThickFromBottom: string[];
export declare const cisArrowThickFromLeft: string[];
export declare const cisArrowThickFromRight: string[];
export declare const cisArrowThickFromTop: string[];
export declare const cisArrowThickLeft: string[];
export declare const cisArrowThickRight: string[];
export declare const cisArrowThickSquareLeft: string[];
export declare const cisArrowThickSquareDown: string[];
export declare const cisArrowThickSquareRight: string[];
export declare const cisArrowThickSquareUp: string[];
export declare const cisArrowThickToBottom: string[];
export declare const cisArrowThickToLeft: string[];
export declare const cisArrowThickToRight: string[];
export declare const cisArrowThickToTop: string[];
export declare const cisArrowThickTop: string[];
export declare const cisArrowTop: string[];
export declare const cisArtTrack: string[];
export declare const cisAssistiveListeningSystem: string[];
export declare const cisAsterisk: string[];
export declare const cisAsteriskCircle: string[];
export declare const cisAt: string[];
export declare const cisAudioDescription: string[];
export declare const cisAudioSpectrum: string[];
export declare const cisAudio: string[];
export declare const cisAvTimer: string[];
export declare const cisBabyCarriage: string[];
export declare const cisBaby: string[];
export declare const cisBackspace: string[];
export declare const cisBadge: string[];
export declare const cisBalanceScaleRight: string[];
export declare const cisBalanceScaleLeft: string[];
export declare const cisBalanceScale: string[];
export declare const cisBan: string[];
export declare const cisBank: string[];
export declare const cisBarChart: string[];
export declare const cisBarcode: string[];
export declare const cisBaseball: string[];
export declare const cisBasketArrowDown: string[];
export declare const cisBasketLoaded: string[];
export declare const cisBasketPlus: string[];
export declare const cisBasket: string[];
export declare const cisBasketball: string[];
export declare const cisBath: string[];
export declare const cisBathroom: string[];
export declare const cisBattery1: string[];
export declare const cisBattery0: string[];
export declare const cisBattery2: string[];
export declare const cisBattery4: string[];
export declare const cisBattery3: string[];
export declare const cisBattery5: string[];
export declare const cisBatteryAlt0: string[];
export declare const cisBatteryAlert: string[];
export declare const cisBatteryAlt2: string[];
export declare const cisBatteryAlt1: string[];
export declare const cisBatteryAlt3: string[];
export declare const cisBatteryAltEmpty: string[];
export declare const cisBatteryAltFull: string[];
export declare const cisBatteryAltSlash: string[];
export declare const cisBatteryCharge: string[];
export declare const cisBatteryEmpty: string[];
export declare const cisBatteryFull: string[];
export declare const cisBatterySlash: string[];
export declare const cisBatteryUnknown: string[];
export declare const cisBeachAccess: string[];
export declare const cisBeaker: string[];
export declare const cisBed: string[];
export declare const cisBellExclamation: string[];
export declare const cisBellPlus: string[];
export declare const cisBellRing: string[];
export declare const cisBellSlash: string[];
export declare const cisBikeAlt: string[];
export declare const cisBike: string[];
export declare const cisBirthdayCake: string[];
export declare const cisBlind: string[];
export declare const cisBell: string[];
export declare const cisBluetoothConnected: string[];
export declare const cisBluetoothSearching: string[];
export declare const cisBluetoothSettings: string[];
export declare const cisBluetoothSlash: string[];
export declare const cisBluetooth: string[];
export declare const cisBlurCircular: string[];
export declare const cisBlurLinear: string[];
export declare const cisBlurSlash: string[];
export declare const cisBlur: string[];
export declare const cisBoatAlt: string[];
export declare const cisBoat: string[];
export declare const cisBold: string[];
export declare const cisBoltAlt: string[];
export declare const cisBolt: string[];
export declare const cisBoltCircle: string[];
export declare const cisBookOpen: string[];
export declare const cisBook: string[];
export declare const cisBookmark: string[];
export declare const cisBookmarks: string[];
export declare const cisBorderAll: string[];
export declare const cisBorderClear: string[];
export declare const cisBorderHorizontal: string[];
export declare const cisBorderBottom: string[];
export declare const cisBorderInner: string[];
export declare const cisBorderLeft: string[];
export declare const cisBorderOuter: string[];
export declare const cisBorderRight: string[];
export declare const cisBorderStyle: string[];
export declare const cisBorderTop: string[];
export declare const cisBowlingPins: string[];
export declare const cisBowling: string[];
export declare const cisBoxAlt: string[];
export declare const cisBox: string[];
export declare const cisBraille: string[];
export declare const cisBrandingWatermark: string[];
export declare const cisBriefcaseArrowLeft: string[];
export declare const cisBriefcaseArrowRight: string[];
export declare const cisBorderVertical: string[];
export declare const cisBriefcase: string[];
export declare const cisBrightnessAuto: string[];
export declare const cisBrightnessHigh: string[];
export declare const cisBrightnessLow: string[];
export declare const cisBrightnessMedium: string[];
export declare const cisBriefcaseSlash: string[];
export declare const cisBritishPoundCircle: string[];
export declare const cisBritishPoundSlash: string[];
export declare const cisBritishPound: string[];
export declare const cisBroadcastTower: string[];
export declare const cisBrowser: string[];
export declare const cisBrushAlt: string[];
export declare const cisBrush: string[];
export declare const cisBug: string[];
export declare const cisBrightness: string[];
export declare const cisBuildingBusinessSlash: string[];
export declare const cisBuildingBusiness: string[];
export declare const cisBuildingSlash: string[];
export declare const cisBuilding: string[];
export declare const cisBullhorn: string[];
export declare const cisBurger: string[];
export declare const cisBusAlt: string[];
export declare const cisBusTimer: string[];
export declare const cisBus: string[];
export declare const cisCalculator: string[];
export declare const cisCalendarAlt: string[];
export declare const cisCalendarCheck: string[];
export declare const cisCalendarMinus: string[];
export declare const cisCalendarEvent: string[];
export declare const cisCalendarNote: string[];
export declare const cisCalendarPlus: string[];
export declare const cisCalendarToday: string[];
export declare const cisCalendarTimes: string[];
export declare const cisCalendarViewDay: string[];
export declare const cisCalendar: string[];
export declare const cisCallMade: string[];
export declare const cisCallMerge: string[];
export declare const cisCallMissedOutgoing: string[];
export declare const cisCallMissed: string[];
export declare const cisCallSplit: string[];
export declare const cisCallSwapCalls: string[];
export declare const cisCallReceived: string[];
export declare const cisCallToAction: string[];
export declare const cisCameraControl: string[];
export declare const cisCameraEnhance: string[];
export declare const cisCameraPlus: string[];
export declare const cisCameraRoll: string[];
export declare const cisCameraSwitch: string[];
export declare const cisCamera: string[];
export declare const cisCarAlt: string[];
export declare const cisCar: string[];
export declare const cisCardGiftcard: string[];
export declare const cisCardMembership: string[];
export declare const cisCardTravel: string[];
export declare const cisCaretBottom: string[];
export declare const cisCaretLeft: string[];
export declare const cisCaretRight: string[];
export declare const cisCaretTop: string[];
export declare const cisCartArrowDown: string[];
export declare const cisCartLoaded: string[];
export declare const cisCartPlus: string[];
export declare const cisCartSlash: string[];
export declare const cisCart: string[];
export declare const cisCash: string[];
export declare const cisCasino: string[];
export declare const cisCastConnected: string[];
export declare const cisCastForEducation: string[];
export declare const cisCast: string[];
export declare const cisCat: string[];
export declare const cisCc: string[];
export declare const cisCenterFocusWeak: string[];
export declare const cisCenterFocus: string[];
export declare const cisChalkboardTeacher: string[];
export declare const cisChartArea: string[];
export declare const cisChartBubble: string[];
export declare const cisChartDonut: string[];
export declare const cisChartLine: string[];
export declare const cisChartMultiline: string[];
export declare const cisChartPie: string[];
export declare const cisChartShow: string[];
export declare const cisChartTable: string[];
export declare const cisChart: string[];
export declare const cisChatBubble: string[];
export declare const cisChatSquare: string[];
export declare const cisCheckAlt: string[];
export declare const cisCheckCircle: string[];
export declare const cisCheckDoubleAlt: string[];
export declare const cisCheckDouble: string[];
export declare const cisCheck: string[];
export declare const cisChevronBottom: string[];
export declare const cisChevronBottomAlt: string[];
export declare const cisChevronCircleDownAlt: string[];
export declare const cisChevronCircleDown: string[];
export declare const cisChevronCircleLeftAlt: string[];
export declare const cisChevronCircleLeft: string[];
export declare const cisChevronCircleRightAlt: string[];
export declare const cisChevronCircleRight: string[];
export declare const cisChevronCircleUpAlt: string[];
export declare const cisChevronCircleUp: string[];
export declare const cisChevronDoubleDownAlt: string[];
export declare const cisChevronDoubleDown: string[];
export declare const cisChevronDoubleLeftAlt: string[];
export declare const cisChevronDoubleLeft: string[];
export declare const cisChevronDoubleRight: string[];
export declare const cisChevronDoubleRightAlt: string[];
export declare const cisChevronDoubleUpAlt: string[];
export declare const cisChevronDoubleUp: string[];
export declare const cisChevronLeftAlt: string[];
export declare const cisChevronLeft: string[];
export declare const cisChevronRightAlt: string[];
export declare const cisChevronSquareDownAlt: string[];
export declare const cisChevronRight: string[];
export declare const cisChevronSquareDown: string[];
export declare const cisChevronSquareLeftAlt: string[];
export declare const cisChevronSquareLeft: string[];
export declare const cisChevronSquareRightAlt: string[];
export declare const cisChevronSquareRight: string[];
export declare const cisChevronSquareUpAlt: string[];
export declare const cisChevronSquareUp: string[];
export declare const cisChevronTopAlt: string[];
export declare const cisChevronTop: string[];
export declare const cisChildFriendly: string[];
export declare const cisChild: string[];
export declare const cisCircle: string[];
export declare const cisClearAll: string[];
export declare const cisCity: string[];
export declare const cisClipboard: string[];
export declare const cisClock: string[];
export declare const cisClone: string[];
export declare const cisClosedCaptioning: string[];
export declare const cisCloudCheck: string[];
export declare const cisCloudCircle: string[];
export declare const cisCloudDownload: string[];
export declare const cisCloudSlash: string[];
export declare const cisCloudUpload: string[];
export declare const cisCloud: string[];
export declare const cisCode: string[];
export declare const cisCoffee: string[];
export declare const cisCog: string[];
export declare const cisColorBorder: string[];
export declare const cisColorFill: string[];
export declare const cisColorPalette: string[];
export declare const cisColumns: string[];
export declare const cisCommand: string[];
export declare const cisCommentBubbleCheck: string[];
export declare const cisCommentBubbleEdit: string[];
export declare const cisCommentBubbleExclamation: string[];
export declare const cisCommentBubbleLines: string[];
export declare const cisCommentBubbleMinus: string[];
export declare const cisCommentBubblePlus: string[];
export declare const cisCommentBubbleQuestion: string[];
export declare const cisCommentBubbleSmile: string[];
export declare const cisCommentBubbleX: string[];
export declare const cisCommentBubble: string[];
export declare const cisCommentSquareCheck: string[];
export declare const cisCommentSquareEdit: string[];
export declare const cisCommentSquareExclamation: string[];
export declare const cisCommentSquareImage: string[];
export declare const cisCommentSquareLines: string[];
export declare const cisCommentSquareMinus: string[];
export declare const cisCommentSquarePlus: string[];
export declare const cisCommentSquareRateReview: string[];
export declare const cisCommentSquareSmile: string[];
export declare const cisCommentSquareX: string[];
export declare const cisCommentSquare: string[];
export declare const cisCommute: string[];
export declare const cisCompare: string[];
export declare const cisCompassCalibration: string[];
export declare const cisCompassSlash: string[];
export declare const cisCompass: string[];
export declare const cisCompressWide: string[];
export declare const cisCompress: string[];
export declare const cisContactMail: string[];
export declare const cisContactPhone: string[];
export declare const cisContact: string[];
export declare const cisContacts: string[];
export declare const cisContrast: string[];
export declare const cisControl: string[];
export declare const cisCopy: string[];
export declare const cisCoreFree: string[];
export declare const cisCoreLogoFull: string[];
export declare const cisCoreLogo: string[];
export declare const cisCorePro: string[];
export declare const cisCreditCard: string[];
export declare const cisCouch: string[];
export declare const cisCropRotate: string[];
export declare const cisCrop: string[];
export declare const cisCursorMove: string[];
export declare const cisCursor: string[];
export declare const cisCut: string[];
export declare const cisDataTransferDown: string[];
export declare const cisDeaf: string[];
export declare const cisDataTransferUp: string[];
export declare const cisDelete: string[];
export declare const cisDescription: string[];
export declare const cisDeveloperBoard: string[];
export declare const cisDeviceUnknown: string[];
export declare const cisDevicesImportant: string[];
export declare const cisDevicesOther: string[];
export declare const cisDevicesSlash: string[];
export declare const cisDevices: string[];
export declare const cisDial: string[];
export declare const cisDialpad: string[];
export declare const cisDiamond: string[];
export declare const cisDinner: string[];
export declare const cisDirections: string[];
export declare const cisDisabled: string[];
export declare const cisDns: string[];
export declare const cisDock: string[];
export declare const cisDocument: string[];
export declare const cisDog: string[];
export declare const cisDollarCircleSlash: string[];
export declare const cisDollarCircle: string[];
export declare const cisDollarSlash: string[];
export declare const cisDollar: string[];
export declare const cisDonate: string[];
export declare const cisDoor: string[];
export declare const cisDoubleQuoteSansLeft: string[];
export declare const cisDoubleQuoteSansRight: string[];
export declare const cisDoubleQuoteSerifLeft: string[];
export declare const cisDoubleQuoteSerifRight: string[];
export declare const cisDrinkAlcohol: string[];
export declare const cisDrink: string[];
export declare const cisDropSlash: string[];
export declare const cisDrop: string[];
export declare const cisDvr: string[];
export declare const cisEar: string[];
export declare const cisEco: string[];
export declare const cisEducation: string[];
export declare const cisElevator: string[];
export declare const cisEnergyCircle: string[];
export declare const cisEnergy: string[];
export declare const cisEnvelopeClosed: string[];
export declare const cisEnvelopeLetter: string[];
export declare const cisEnvelopeOpen: string[];
export declare const cisEnvelopeMinus: string[];
export declare const cisEnvelopePlus: string[];
export declare const cisEqualizer: string[];
export declare const cisEthernetAlt: string[];
export declare const cisEthernet: string[];
export declare const cisEuroCircleSlash: string[];
export declare const cisEuroCircle: string[];
export declare const cisEuroSlash: string[];
export declare const cisEuro: string[];
export declare const cisEvStation: string[];
export declare const cisExcerpt: string[];
export declare const cisExclamationCircle: string[];
export declare const cisExclamation: string[];
export declare const cisExitToApp: string[];
export declare const cisExpandLeft: string[];
export declare const cisExpandDown: string[];
export declare const cisExpandRight: string[];
export declare const cisExpandUp: string[];
export declare const cisExposure: string[];
export declare const cisExternalLink: string[];
export declare const cisEyeSlash: string[];
export declare const cisEye: string[];
export declare const cisEyedropper: string[];
export declare const cisFace: string[];
export declare const cisFaceDead: string[];
export declare const cisFactorySlash: string[];
export declare const cisFastfood: string[];
export declare const cisFax: string[];
export declare const cisFactory: string[];
export declare const cisFeaturedPlaylist: string[];
export declare const cisFeaturedVideo: string[];
export declare const cisFiberDvr: string[];
export declare const cisFiberManual: string[];
export declare const cisFiberNew: string[];
export declare const cisFiberPin: string[];
export declare const cisFileAcrobat: string[];
export declare const cisFiberSmart: string[];
export declare const cisFileAdd: string[];
export declare const cisFileArchive: string[];
export declare const cisFileAudio: string[];
export declare const cisFileCode: string[];
export declare const cisFileDoc: string[];
export declare const cisFileExcel: string[];
export declare const cisFileImage: string[];
export declare const cisFilePdf: string[];
export declare const cisFilePpt: string[];
export declare const cisFilePowerpoint: string[];
export declare const cisFileVideo: string[];
export declare const cisFileWord: string[];
export declare const cisFileXls: string[];
export declare const cisFile: string[];
export declare const cisFilterFrames: string[];
export declare const cisFilterPhoto: string[];
export declare const cisFilter: string[];
export declare const cisFindInPage: string[];
export declare const cisFindReplace: string[];
export declare const cisFire: string[];
export declare const cisFingerprint: string[];
export declare const cisFlagAlt: string[];
export declare const cisFlagRectangle: string[];
export declare const cisFlagTriangle: string[];
export declare const cisFlag: string[];
export declare const cisFlame: string[];
export declare const cisFlash: string[];
export declare const cisFlightTakeoff: string[];
export declare const cisFlightLand: string[];
export declare const cisFlipToFront: string[];
export declare const cisFlipToBack: string[];
export declare const cisFlower: string[];
export declare const cisFolderAlt: string[];
export declare const cisFolderOpen: string[];
export declare const cisFolderPlus: string[];
export declare const cisFolderShared: string[];
export declare const cisFolderSpecial: string[];
export declare const cisFlip: string[];
export declare const cisFolder: string[];
export declare const cisFont: string[];
export declare const cisFootball: string[];
export declare const cisFork: string[];
export declare const cisFridge: string[];
export declare const cisFrown: string[];
export declare const cisFullscreenExit: string[];
export declare const cisFullscreen: string[];
export declare const cisFunctionsAlt: string[];
export declare const cisFunctions: string[];
export declare const cisGamepad: string[];
export declare const cisGarage: string[];
export declare const cisGem: string[];
export declare const cisGif: string[];
export declare const cisGift: string[];
export declare const cisGlass: string[];
export declare const cisGlobeAltLock: string[];
export declare const cisGlobeAlt: string[];
export declare const cisGlobeLock: string[];
export declare const cisGlobe: string[];
export declare const cisGolfAlt: string[];
export declare const cisGolf: string[];
export declare const cisGradient: string[];
export declare const cisGrain: string[];
export declare const cisGraph: string[];
export declare const cisGridSlash: string[];
export declare const cisGrid: string[];
export declare const cisHamburgerMenu: string[];
export declare const cisHappy: string[];
export declare const cisHardDrive: string[];
export declare const cisHd: string[];
export declare const cisHdr: string[];
export declare const cisHeader: string[];
export declare const cisHeadphonesMic: string[];
export declare const cisHeadphonesMute: string[];
export declare const cisHeadphones: string[];
export declare const cisHealing: string[];
export declare const cisHighQuality: string[];
export declare const cisHeart: string[];
export declare const cisHighlighter: string[];
export declare const cisHighligt: string[];
export declare const cisHistory: string[];
export declare const cisHome: string[];
export declare const cisHospital: string[];
export declare const cisHotTub: string[];
export declare const cisHotel: string[];
export declare const cisHourglass: string[];
export declare const cisHouse: string[];
export declare const cisHq: string[];
export declare const cisHttp: string[];
export declare const cisHttps: string[];
export declare const cisIdBadge: string[];
export declare const cisIdCard: string[];
export declare const cisImageBroken: string[];
export declare const cisImagePlus: string[];
export declare const cisImage: string[];
export declare const cisImages: string[];
export declare const cisInboxIn: string[];
export declare const cisInboxOut: string[];
export declare const cisInbox: string[];
export declare const cisIndentDecrease: string[];
export declare const cisIndentIncrease: string[];
export declare const cisIndustrySlash: string[];
export declare const cisInfinity: string[];
export declare const cisIndustry: string[];
export declare const cisInfo: string[];
export declare const cisInputAntenna: string[];
export declare const cisInputComponent: string[];
export declare const cisInputHdmi: string[];
export declare const cisInputPowerOff: string[];
export declare const cisInputPower: string[];
export declare const cisInput: string[];
export declare const cisInputSvideo: string[];
export declare const cisInstitution: string[];
export declare const cisInvert: string[];
export declare const cisItalic: string[];
export declare const cisJustifyCenter: string[];
export declare const cisJustifyLeft: string[];
export declare const cisJustifyRight: string[];
export declare const cisKeyAlt: string[];
export declare const cisKey: string[];
export declare const cisKeyboardHide: string[];
export declare const cisLanguage: string[];
export declare const cisLan: string[];
export declare const cisKeyboard: string[];
export declare const cisLaptop: string[];
export declare const cisLaundry: string[];
export declare const cisKitchen: string[];
export declare const cisLayers: string[];
export declare const cisLayersSlash: string[];
export declare const cisLeaf: string[];
export declare const cisLemon: string[];
export declare const cisLevelDown: string[];
export declare const cisLevelUp: string[];
export declare const cisLibraryAdd: string[];
export declare const cisLibraryBookmark: string[];
export declare const cisLibraryBooks: string[];
export declare const cisLibraryBuilding: string[];
export declare const cisLibraryMusic: string[];
export declare const cisHdrSlash: string[];
export declare const cisLibrary: string[];
export declare const cisLightbulb: string[];
export declare const cisLifeRing: string[];
export declare const cisLineSpacing: string[];
export declare const cisLineStyle: string[];
export declare const cisLinkAlt: string[];
export declare const cisLineWeight: string[];
export declare const cisLinkBroken: string[];
export declare const cisLinkIntact: string[];
export declare const cisLinkSlash: string[];
export declare const cisLink: string[];
export declare const cisListFilter: string[];
export declare const cisListHighPriority: string[];
export declare const cisListLowPriority: string[];
export declare const cisListNumberedRtl: string[];
export declare const cisListNumbered: string[];
export declare const cisListRich: string[];
export declare const cisList: string[];
export declare const cisLocationGpsFixed: string[];
export declare const cisLocationGpsOff: string[];
export declare const cisLocationGps: string[];
export declare const cisLocationPinCheck: string[];
export declare const cisLocationPinEdit: string[];
export declare const cisLocationPinPlus: string[];
export declare const cisLocationPinSlash: string[];
export declare const cisLocationPin: string[];
export declare const cisLockLocked: string[];
export declare const cisLockMinus: string[];
export declare const cisLockPlus: string[];
export declare const cisLockUnlocked: string[];
export declare const cisLocomotive: string[];
export declare const cisLoop1: string[];
export declare const cisLoopCircular: string[];
export declare const cisLoopSquare: string[];
export declare const cisLoop: string[];
export declare const cisLowVision: string[];
export declare const cisLoyalty: string[];
export declare const cisMagnifyingGlass: string[];
export declare const cisMail: string[];
export declare const cisMailbox: string[];
export declare const cisMapAlt: string[];
export declare const cisMap: string[];
export declare const cisMediaEjectCircle: string[];
export declare const cisMediaEjectSquare: string[];
export declare const cisMediaEject: string[];
export declare const cisMediaPauseCircle: string[];
export declare const cisMediaPauseSquare: string[];
export declare const cisMediaPause: string[];
export declare const cisMediaPlaySquare: string[];
export declare const cisMediaPlayCircle: string[];
export declare const cisMediaPlay: string[];
export declare const cisMediaRecordCircle: string[];
export declare const cisMediaRecordSquare: string[];
export declare const cisMediaRecord: string[];
export declare const cisMediaSkipBackwardSquare: string[];
export declare const cisMediaSkipBackwardCircle: string[];
export declare const cisMediaSkipBackward: string[];
export declare const cisMediaSkipForwardCircle: string[];
export declare const cisMediaSkipForwardSquare: string[];
export declare const cisMediaSkipForward: string[];
export declare const cisMediaStepBackwardCircle: string[];
export declare const cisMediaStepBackwardSquare: string[];
export declare const cisMediaStepBackward: string[];
export declare const cisMediaStepForwardCircle: string[];
export declare const cisMediaStepForwardSquare: string[];
export declare const cisMediaStepForward: string[];
export declare const cisMediaStopCircle: string[];
export declare const cisMediaStopSquare: string[];
export declare const cisMediaStop: string[];
export declare const cisMedicalCross: string[];
export declare const cisMemory: string[];
export declare const cisMenu: string[];
export declare const cisMeh: string[];
export declare const cisMicAlt: string[];
export declare const cisMicSettings: string[];
export declare const cisMicSlash: string[];
export declare const cisMic: string[];
export declare const cisMicrochip: string[];
export declare const cisMicrophoneAlt: string[];
export declare const cisMicrophoneSlash: string[];
export declare const cisMicrophoneSettings: string[];
export declare const cisMicrophone: string[];
export declare const cisMinusCircle: string[];
export declare const cisMinusSquare: string[];
export declare const cisMinus: string[];
export declare const cisMobileArrowAdd: string[];
export declare const cisMobileArrowRemove: string[];
export declare const cisMobileCheck: string[];
export declare const cisMobileDeveloperMode: string[];
export declare const cisMobileLandscape: string[];
export declare const cisMobileLock: string[];
export declare const cisMobileMinus: string[];
export declare const cisMobilePlus: string[];
export declare const cisMobilePortrait: string[];
export declare const cisMobileSettings: string[];
export declare const cisMobileSlash: string[];
export declare const cisMobileSms: string[];
export declare const cisMobileSpeaker: string[];
export declare const cisMobileX: string[];
export declare const cisMobile: string[];
export declare const cisMoneyBillAlt: string[];
export declare const cisMoneyBillAlt2: string[];
export declare const cisMoneyBill: string[];
export declare const cisMobileVolume: string[];
export declare const cisMonitor: string[];
export declare const cisMoney: string[];
export declare const cisMoodBad: string[];
export declare const cisMoodGood: string[];
export declare const cisMoodVeryGood: string[];
export declare const cisMore: string[];
export declare const cisMoodVeryBad: string[];
export declare const cisMotorbike: string[];
export declare const cisMouseAlt: string[];
export declare const cisMouse: string[];
export declare const cisMouthSlash: string[];
export declare const cisMouth: string[];
export declare const cisMove: string[];
export declare const cisMovieAlt: string[];
export declare const cisMovie: string[];
export declare const cisMugTea: string[];
export declare const cisMug: string[];
export declare const cisMusicNoteAlt: string[];
export declare const cisMusicNoteSlash: string[];
export declare const cisMusicNote: string[];
export declare const cisMusicVideo: string[];
export declare const cisNetworkCheck: string[];
export declare const cisNewReleases: string[];
export declare const cisNew: string[];
export declare const cisNewspaper: string[];
export declare const cisNoteAdd: string[];
export declare const cisNote: string[];
export declare const cisNotes: string[];
export declare const cisObjectUngroup: string[];
export declare const cisObjectGroup: string[];
export declare const cisOpacity: string[];
export declare const cisOptions: string[];
export declare const cisOpentype: string[];
export declare const cisOverscanSettings: string[];
export declare const cisOven: string[];
export declare const cisOverscan: string[];
export declare const cisPageRestore: string[];
export declare const cisPage: string[];
export declare const cisPageview: string[];
export declare const cisPaintBucket: string[];
export declare const cisPaint: string[];
export declare const cisPaperPlane: string[];
export declare const cisPaperclip: string[];
export declare const cisParagraph: string[];
export declare const cisParking: string[];
export declare const cisPaw: string[];
export declare const cisPenAlt: string[];
export declare const cisPenFancy: string[];
export declare const cisPenNib: string[];
export declare const cisPen: string[];
export declare const cisPencil: string[];
export declare const cisPeople: string[];
export declare const cisPeople_Plus: string[];
export declare const cisPercent: string[];
export declare const cisPersonFemale: string[];
export declare const cisPerson: string[];
export declare const cisPetrolStation: string[];
export declare const cisPhoneBluetooth: string[];
export declare const cisPhoneCallEnd: string[];
export declare const cisPhoneCall: string[];
export declare const cisPhoneCallback: string[];
export declare const cisPhoneCheck: string[];
export declare const cisPhoneForward: string[];
export declare const cisPhoneInTalk: string[];
export declare const cisPhoneLock: string[];
export declare const cisPhoneMinus: string[];
export declare const cisPhoneMissed: string[];
export declare const cisPhonePaused: string[];
export declare const cisPhonePlus: string[];
export declare const cisPhoneRingVolume: string[];
export declare const cisPhoneSettings: string[];
export declare const cisPhoneSlash: string[];
export declare const cisPhoneSquare: string[];
export declare const cisPhoneVolume: string[];
export declare const cisPhoneX: string[];
export declare const cisPhone: string[];
export declare const cisPictureInPictureAlt: string[];
export declare const cisPictureInPicture: string[];
export declare const cisPin: string[];
export declare const cisPizza: string[];
export declare const cisPlant: string[];
export declare const cisPlaylistAddCheck: string[];
export declare const cisPlaylistAdd: string[];
export declare const cisPlaylistPlay: string[];
export declare const cisPlusCircle: string[];
export declare const cisPlusOne: string[];
export declare const cisPlusSquare: string[];
export declare const cisPlus: string[];
export declare const cisPool: string[];
export declare const cisPortableWifiOff: string[];
export declare const cisPortableWifi: string[];
export declare const cisPowerSettings: string[];
export declare const cisPowerStandby: string[];
export declare const cisPregnant: string[];
export declare const cisPrint: string[];
export declare const cisPrinterSlash: string[];
export declare const cisPrinter: string[];
export declare const cisPushchair: string[];
export declare const cisPuzzlePiece: string[];
export declare const cisPuzzle: string[];
export declare const cisQrCode: string[];
export declare const cisQueueAdd: string[];
export declare const cisQueueMusic: string[];
export declare const cisQueuePlayNext: string[];
export declare const cisQueueRemove: string[];
export declare const cisQueue: string[];
export declare const cisRadio: string[];
export declare const cisRandom: string[];
export declare const cisRailway: string[];
export declare const cisRecentActors: string[];
export declare const cisRectangle: string[];
export declare const cisRecycle: string[];
export declare const cisRemoteControl: string[];
export declare const cisReload: string[];
export declare const cisRemoteSettings: string[];
export declare const cisReplay: string[];
export declare const cisReport: string[];
export declare const cisReportSlash: string[];
export declare const cisResizeBoth: string[];
export declare const cisResizeHeight: string[];
export declare const cisResizeWidth: string[];
export declare const cisRestaurantMenu: string[];
export declare const cisRestaurant: string[];
export declare const cisRestore: string[];
export declare const cisRoomSlash: string[];
export declare const cisRoom: string[];
export declare const cisRouter: string[];
export declare const cisRoundedCorner: string[];
export declare const cisRowing: string[];
export declare const cisRssAlt: string[];
export declare const cisRssSquare: string[];
export declare const cisRss: string[];
export declare const cisRubleCircleSlash: string[];
export declare const cisRubleCircle: string[];
export declare const cisRubleSlash: string[];
export declare const cisRuble: string[];
export declare const cisRunning: string[];
export declare const cisSad: string[];
export declare const cisSatelite: string[];
export declare const cisSave: string[];
export declare const cisScanner: string[];
export declare const cisSchool: string[];
export declare const cisScooter: string[];
export declare const cisScreenDeskopSlash: string[];
export declare const cisScreenDesktop: string[];
export declare const cisScreenHorizontal: string[];
export declare const cisScreenLockHorizontal: string[];
export declare const cisScreenLandscape: string[];
export declare const cisScreenLockLandscape: string[];
export declare const cisScreenLockRotation: string[];
export declare const cisScreenMirroring: string[];
export declare const cisScreenLockVertical: string[];
export declare const cisScreenPortrait: string[];
export declare const cisScreenRotation: string[];
export declare const cisScreenSmartphone: string[];
export declare const cisScreenVertical: string[];
export declare const cisScript: string[];
export declare const cisScrubber: string[];
export declare const cisSdcard: string[];
export declare const cisScreenLockPortrait: string[];
export declare const cisSearch: string[];
export declare const cisSecurity: string[];
export declare const cisSelectAll: string[];
export declare const cisSelect: string[];
export declare const cisSend: string[];
export declare const cisSettings: string[];
export declare const cisShareAll: string[];
export declare const cisShareAlt: string[];
export declare const cisShareBoxed: string[];
export declare const cisShare: string[];
export declare const cisShieldAlt: string[];
export declare const cisShieldCheck: string[];
export declare const cisShieldMinus: string[];
export declare const cisShieldPlus: string[];
export declare const cisShieldSlash: string[];
export declare const cisShieldX: string[];
export declare const cisShield: string[];
export declare const cisShopMediaTwo: string[];
export declare const cisShopMedia: string[];
export declare const cisShortText: string[];
export declare const cisShower: string[];
export declare const cisSignLanguage: string[];
export declare const cisSignalCellular0: string[];
export declare const cisSignalCellular1: string[];
export declare const cisSignalCellular2: string[];
export declare const cisSignalCellular3: string[];
export declare const cisSignalCellular4: string[];
export declare const cisSignalCellularNoInternet0: string[];
export declare const cisSignalCellularNoInternet1: string[];
export declare const cisSignalCellularNoInternet2: string[];
export declare const cisSignalCellularNoInternet3: string[];
export declare const cisSignalCellularOff: string[];
export declare const cisSignalCellularNoInternet4: string[];
export declare const cisSignalCellularOff_1: string[];
export declare const cisSignpost: string[];
export declare const cisSimSlash: string[];
export declare const cisSim: string[];
export declare const cisSitemap: string[];
export declare const cisSlowMotion: string[];
export declare const cisSmilePlus: string[];
export declare const cisSmile: string[];
export declare const cisSmokeFree: string[];
export declare const cisSmokeSlash: string[];
export declare const cisSmoke: string[];
export declare const cisSmokingRoom: string[];
export declare const cisSoccer: string[];
export declare const cisSofa: string[];
export declare const cisSorroundSound: string[];
export declare const cisSortAlphaDown: string[];
export declare const cisSortAlphaUp: string[];
export declare const cisSortAscending: string[];
export declare const cisSortDescending: string[];
export declare const cisSortNumericDown: string[];
export declare const cisSortNumericUp: string[];
export declare const cisSpa: string[];
export declare const cisSpaceBar: string[];
export declare const cisSpeak: string[];
export declare const cisSpeakerGroup: string[];
export declare const cisSpeechBubble: string[];
export declare const cisSpeaker: string[];
export declare const cisSpeechNotes: string[];
export declare const cisSpeechNotesSlash: string[];
export declare const cisSpeech: string[];
export declare const cisSpeedometer: string[];
export declare const cisSpreadsheet: string[];
export declare const cisSquare: string[];
export declare const cisStarHalf: string[];
export declare const cisStarCircle: string[];
export declare const cisStar: string[];
export declare const cisStickyNote: string[];
export declare const cisStorage: string[];
export declare const cisStore: string[];
export declare const cisStrikethrough: string[];
export declare const cisStream: string[];
export declare const cisSubtitles: string[];
export declare const cisSubway: string[];
export declare const cisSwapHorizontalCircle: string[];
export declare const cisSwapHorizontal: string[];
export declare const cisSwapVerticalCircle: string[];
export declare const cisSwapVertical: string[];
export declare const cisSwimming: string[];
export declare const cisSyncDisabled: string[];
export declare const cisSyncProblem: string[];
export declare const cisSync: string[];
export declare const cisTablet: string[];
export declare const cisTag: string[];
export declare const cisTarget: string[];
export declare const cisTask: string[];
export declare const cisTaxi: string[];
export declare const cisTennisBall: string[];
export declare const cisTennis: string[];
export declare const cisTerminal: string[];
export declare const cisTerrain: string[];
export declare const cisTextDirectionLtr: string[];
export declare const cisTextDirectionRtl: string[];
export declare const cisTextFormatClear: string[];
export declare const cisTextHeight: string[];
export declare const cisTextRotateVertical: string[];
export declare const cisTextRotationDown: string[];
export declare const cisTextRotationNone: string[];
export declare const cisTextShapes: string[];
export declare const cisTextRotationUp: string[];
export declare const cisTextSize: string[];
export declare const cisTextSquare: string[];
export declare const cisTextStrike: string[];
export declare const cisTextWidth: string[];
export declare const cisText: string[];
export declare const cisTimeline: string[];
export declare const cisTimer: string[];
export declare const cisToggleOff: string[];
export declare const cisToggleOn: string[];
export declare const cisTags: string[];
export declare const cisToilet: string[];
export declare const cisTouchApp: string[];
export declare const cisToll: string[];
export declare const cisTraffic: string[];
export declare const cisTrain: string[];
export declare const cisTrainAlt: string[];
export declare const cisTram: string[];
export declare const cisTransferWithinAStation: string[];
export declare const cisTransfer: string[];
export declare const cisTranslate: string[];
export declare const cisTrashAlt: string[];
export declare const cisTrashArrowUp: string[];
export declare const cisTrashSweep: string[];
export declare const cisTrashX: string[];
export declare const cisTrash: string[];
export declare const cisTruck: string[];
export declare const cisTriangle: string[];
export declare const cisTvDvr: string[];
export declare const cisTty: string[];
export declare const cisTvLive: string[];
export declare const cisTvSlash: string[];
export declare const cisUnderline: string[];
export declare const cisTv: string[];
export declare const cisUpdate: string[];
export declare const cisUniversalAccess: string[];
export declare const cisUsb: string[];
export declare const cisUserFemale: string[];
export declare const cisSignal: string[];
export declare const cisUserFollow: string[];
export declare const cisUserSecret: string[];
export declare const cisUserUnfollow: string[];
export declare const cisUser: string[];
export declare const cisVericalSplit: string[];
export declare const cisVector: string[];
export declare const cisVerticalAlignCenter: string[];
export declare const cisVerticalAlignBottom: string[];
export declare const cisVerticalAlignTop: string[];
export declare const cisVideoLabel: string[];
export declare const cisVideoLibrary: string[];
export declare const cisVideoMissed: string[];
export declare const cisVideoPlus: string[];
export declare const cisVideoSlash: string[];
export declare const cisVideoSwitch: string[];
export declare const cisVideo: string[];
export declare const cisVideogame: string[];
export declare const cisViewAgenda: string[];
export declare const cisViewArray: string[];
export declare const cisViewCarousel: string[];
export declare const cisViewColumn: string[];
export declare const cisViewModule: string[];
export declare const cisViewQuilt: string[];
export declare const cisViewStream: string[];
export declare const cisVoiceOverSlash: string[];
export declare const cisVoiceOverRecord: string[];
export declare const cisVoice: string[];
export declare const cisVoicemail: string[];
export declare const cisVolumeHigh: string[];
export declare const cisVolumeLow: string[];
export declare const cisVolumeOff: string[];
export declare const cisVote: string[];
export declare const cisWalk: string[];
export declare const cisWallet: string[];
export declare const cisWallpaper: string[];
export declare const cisWarning: string[];
export declare const cisWatch: string[];
export declare const cisWaves: string[];
export declare const cisWc: string[];
export declare const cisWeightlifitng: string[];
export declare const cisWeights: string[];
export declare const cisWheelchair: string[];
export declare const cisWidgets: string[];
export declare const cisWifiSignal0: string[];
export declare const cisWifiLock: string[];
export declare const cisWifiSignal1: string[];
export declare const cisWifiSignal2: string[];
export declare const cisWifiSignal3: string[];
export declare const cisWifiSignal4: string[];
export declare const cisWifiSignalLock0: string[];
export declare const cisWifiSignalLock1: string[];
export declare const cisWifiSignalLock2: string[];
export declare const cisWifiSignalLock3: string[];
export declare const cisWifiSignalOff: string[];
export declare const cisWifiSignalLock4: string[];
export declare const cisWifi: string[];
export declare const cisWindowMaximize: string[];
export declare const cisWindowMinimize: string[];
export declare const cisWindowRestore: string[];
export declare const cisWindow: string[];
export declare const cisXCircle: string[];
export declare const cisWrapText: string[];
export declare const cisXSquare: string[];
export declare const cisX: string[];
export declare const cisYenCircleSlash: string[];
export declare const cisYenCircle: string[];
export declare const cisYenSlash: string[];
export declare const cisYen: string[];
export declare const cisZoomIn: string[];
export declare const cisZoomOut: string[];
export declare const cisZoom: string[];