export declare const duotoneSet: {
  "cid3dRotate": string[];
  "cid4k": string[];
  "cid3d": string[];
  "cidAccessible": string[];
  "cidAccountLogout": string[];
  "cidActionUndo": string[];
  "cidAddressBook": string[];
  "cidAddressCard": string[];
  "cidAirplaneModeOff": string[];
  "cidAirplaneMode": string[];
  "cidAirplay": string[];
  "cidAlarmAdd": string[];
  "cidAlarmOff": string[];
  "cidAlarmSnooze": string[];
  "cidAlarmOn": string[];
  "cidAlarm": string[];
  "cidAlbum": string[];
  "cidAlignCenter": string[];
  "cidAlignLeft": string[];
  "cidActionRedo": string[];
  "cidAlignRight": string[];
  "cidAmericanFootball": string[];
  "cidAnimal": string[];
  "cidAperture": string[];
  "cidApple": string[];
  "cidApplicationsSettings": string[];
  "cidApplications": string[];
  "cidAppsSettings": string[];
  "cidApps": string[];
  "cidArrowCircleBottom": string[];
  "cidArchive": string[];
  "cidArrowCircleLeft": string[];
  "cidArrowCircleRight": string[];
  "cidArrowCircleTop": string[];
  "cidArrowThickCircleDown": string[];
  "cidArrowThickCircleLeft": string[];
  "cidArrowThickCircleRight": string[];
  "cidArrowThickCircleUp": string[];
  "cidArrowThickFromBottom": string[];
  "cidArrowThickFromLeft": string[];
  "cidArrowThickFromRight": string[];
  "cidArrowThickFromTop": string[];
  "cidArrowThickSquareLeft": string[];
  "cidArrowThickSquareDown": string[];
  "cidArrowThickSquareRight": string[];
  "cidArrowThickSquareUp": string[];
  "cidArrowThickToBottom": string[];
  "cidArrowThickToLeft": string[];
  "cidArrowThickToRight": string[];
  "cidArrowThickToTop": string[];
  "cidArtTrack": string[];
  "cidAssistiveListeningSystem": string[];
  "cidAsteriskCircle": string[];
  "cidAt": string[];
  "cidAudioDescription": string[];
  "cidAudioSpectrum": string[];
  "cidAudio": string[];
  "cidAvTimer": string[];
  "cidBabyCarriage": string[];
  "cidBaby": string[];
  "cidBackspace": string[];
  "cidBadge": string[];
  "cidBalanceScaleLeft": string[];
  "cidBalanceScaleRight": string[];
  "cidBalanceScale": string[];
  "cidBan": string[];
  "cidBank": string[];
  "cidBarcode": string[];
  "cidBarChart": string[];
  "cidBaseball": string[];
  "cidBasketArrowDown": string[];
  "cidBasketPlus": string[];
  "cidBasketLoaded": string[];
  "cidBasket": string[];
  "cidBath": string[];
  "cidBasketball": string[];
  "cidBathroom": string[];
  "cidBattery0": string[];
  "cidBattery2": string[];
  "cidBattery1": string[];
  "cidBattery3": string[];
  "cidBattery4": string[];
  "cidBatteryAlert": string[];
  "cidBatteryAlt1": string[];
  "cidBatteryAlt0": string[];
  "cidBatteryAlt2": string[];
  "cidBattery5": string[];
  "cidBatteryAltEmpty": string[];
  "cidBatteryAltFull": string[];
  "cidBatteryAlt3": string[];
  "cidBatteryCharge": string[];
  "cidBatteryAltSlash": string[];
  "cidBatteryEmpty": string[];
  "cidBatterySlash": string[];
  "cidBatteryFull": string[];
  "cidBatteryUnknown": string[];
  "cidBeachAccess": string[];
  "cidBeaker": string[];
  "cidBed": string[];
  "cidBellExclamation": string[];
  "cidBellPlus": string[];
  "cidBellRing": string[];
  "cidBellSlash": string[];
  "cidBell": string[];
  "cidBikeAlt": string[];
  "cidBirthdayCake": string[];
  "cidBlind": string[];
  "cidBluetoothConnected": string[];
  "cidBluetoothSearching": string[];
  "cidBluetoothSettings": string[];
  "cidBoatAlt": string[];
  "cidBluetooth": string[];
  "cidBluetoothSlash": string[];
  "cidBoat": string[];
  "cidBold": string[];
  "cidBoltCircle": string[];
  "cidBookOpen": string[];
  "cidBook": string[];
  "cidBookmark": string[];
  "cidBookmarks": string[];
  "cidBorderAll": string[];
  "cidBorderBottom": string[];
  "cidBorderHorizontal": string[];
  "cidBike": string[];
  "cidBorderClear": string[];
  "cidBorderInner": string[];
  "cidBorderLeft": string[];
  "cidBorderOuter": string[];
  "cidBorderRight": string[];
  "cidBorderStyle": string[];
  "cidBorderTop": string[];
  "cidBorderVertical": string[];
  "cidBowlingPins": string[];
  "cidBowling": string[];
  "cidBoxAlt": string[];
  "cidBraille": string[];
  "cidBox": string[];
  "cidBrandingWatermark": string[];
  "cidBriefcaseArrowLeft": string[];
  "cidBriefcaseArrowRight": string[];
  "cidBriefcaseSlash": string[];
  "cidBriefcase": string[];
  "cidBrightnessAuto": string[];
  "cidBrightnessLow": string[];
  "cidBrightnessHigh": string[];
  "cidBrightnessMedium": string[];
  "cidBrightness": string[];
  "cidBritishPoundCircle": string[];
  "cidBritishPoundSlash": string[];
  "cidBroadcastTower": string[];
  "cidBrowser": string[];
  "cidBrushAlt": string[];
  "cidBrush": string[];
  "cidBug": string[];
  "cidBuildingBusinessSlash": string[];
  "cidBuildingBusiness": string[];
  "cidBuildingSlash": string[];
  "cidBuilding": string[];
  "cidBullhorn": string[];
  "cidBusAlt": string[];
  "cidBusTimer": string[];
  "cidBurger": string[];
  "cidBus": string[];
  "cidCalculator": string[];
  "cidCalendarCheck": string[];
  "cidCalendarEvent": string[];
  "cidCalendarMinus": string[];
  "cidCalendarNote": string[];
  "cidCalendarPlus": string[];
  "cidCalendarToday": string[];
  "cidCalendarTimes": string[];
  "cidCalendarViewDay": string[];
  "cidCalendar": string[];
  "cidCallMade": string[];
  "cidCallMerge": string[];
  "cidCallMissedOutgoing": string[];
  "cidCallReceived": string[];
  "cidCallMissed": string[];
  "cidCallSplit": string[];
  "cidCallSwapCalls": string[];
  "cidCallToAction": string[];
  "cidCameraControl": string[];
  "cidCameraEnhance": string[];
  "cidCameraPlus": string[];
  "cidCameraRoll": string[];
  "cidCameraSwitch": string[];
  "cidCamera": string[];
  "cidCarAlt": string[];
  "cidCar": string[];
  "cidCardGiftcard": string[];
  "cidCardMembership": string[];
  "cidCardTravel": string[];
  "cidCaretBottom": string[];
  "cidCaretLeft": string[];
  "cidCaretRight": string[];
  "cidCaretTop": string[];
  "cidCartArrowDown": string[];
  "cidCartLoaded": string[];
  "cidCartPlus": string[];
  "cidCartSlash": string[];
  "cidCart": string[];
  "cidCash": string[];
  "cidCasino": string[];
  "cidCastConnected": string[];
  "cidCastForEducation": string[];
  "cidCast": string[];
  "cidCat": string[];
  "cidCc": string[];
  "cidCenterFocusWeak": string[];
  "cidCenterFocus": string[];
  "cidChalkboardTeacher": string[];
  "cidChartArea": string[];
  "cidChartBubble": string[];
  "cidChartDonut": string[];
  "cidChartLine": string[];
  "cidChartMultiline": string[];
  "cidChartPie": string[];
  "cidChartShow": string[];
  "cidChart": string[];
  "cidChartTable": string[];
  "cidChatBubble": string[];
  "cidChatSquare": string[];
  "cidCheckAlt": string[];
  "cidCheckCircle": string[];
  "cidCheckDoubleAlt": string[];
  "cidCheckDouble": string[];
  "cidCheck": string[];
  "cidChevronBottom": string[];
  "cidChevronCircleDownAlt": string[];
  "cidChevronCircleDown": string[];
  "cidChevronCircleLeftAlt": string[];
  "cidChevronCircleLeft": string[];
  "cidChevronCircleRightAlt": string[];
  "cidChevronCircleRight": string[];
  "cidChevronCircleUpAlt": string[];
  "cidChevronCircleUp": string[];
  "cidChevronDoubleDown": string[];
  "cidChevronDoubleDownAlt": string[];
  "cidChevronDoubleLeftAlt": string[];
  "cidChevronDoubleLeft": string[];
  "cidChevronDoubleRightAlt": string[];
  "cidChevronDoubleRight": string[];
  "cidChevronDoubleUpAlt": string[];
  "cidChevronDoubleUp": string[];
  "cidChevronBottomAlt": string[];
  "cidChevronLeftAlt": string[];
  "cidChevronRightAlt": string[];
  "cidChevronSquareDown": string[];
  "cidChevronSquareDownAlt": string[];
  "cidChevronSquareLeftAlt": string[];
  "cidChevronSquareLeft": string[];
  "cidChevronSquareRight": string[];
  "cidChevronSquareRightAlt": string[];
  "cidChevronSquareUpAlt": string[];
  "cidChevronSquareUp": string[];
  "cidChevronTopAlt": string[];
  "cidChildFriendly": string[];
  "cidClearAll": string[];
  "cidChild": string[];
  "cidClipboard": string[];
  "cidCity": string[];
  "cidClock": string[];
  "cidClone": string[];
  "cidCloudCheck": string[];
  "cidClosedCaptioning": string[];
  "cidCloudSlash": string[];
  "cidCloudDownload": string[];
  "cidCloudCircle": string[];
  "cidCloudUpload": string[];
  "cidCloudy": string[];
  "cidCog": string[];
  "cidCode": string[];
  "cidCoffee": string[];
  "cidColorBorder": string[];
  "cidColorFill": string[];
  "cidColorPalette": string[];
  "cidColumns": string[];
  "cidCommand": string[];
  "cidCloud": string[];
  "cidCommentBubbleCheck": string[];
  "cidCommentBubbleEdit": string[];
  "cidCommentBubbleExclamation": string[];
  "cidCommentBubbleLines": string[];
  "cidCommentBubbleMinus": string[];
  "cidCommentBubblePlus": string[];
  "cidCommentBubbleQuestion": string[];
  "cidCommentBubbleSmile": string[];
  "cidCommentBubbleX": string[];
  "cidCommentBubble": string[];
  "cidCommentSquareEdit": string[];
  "cidCommentSquareCheck": string[];
  "cidCommentSquareExclamation": string[];
  "cidCommentSquareLines": string[];
  "cidCommentSquareImage": string[];
  "cidCommentSquareMinus": string[];
  "cidCommentSquareRateReview": string[];
  "cidCommentSquare": string[];
  "cidCommentSquareSmile": string[];
  "cidCommentSquarePlus": string[];
  "cidCommute": string[];
  "cidCompare": string[];
  "cidCompassCalibration": string[];
  "cidCompassSlash": string[];
  "cidCompass": string[];
  "cidCompress": string[];
  "cidContactPhone": string[];
  "cidCompressWide": string[];
  "cidContactMail": string[];
  "cidContact": string[];
  "cidCommentSquareX": string[];
  "cidContacts": string[];
  "cidContrast": string[];
  "cidControl": string[];
  "cidCouch": string[];
  "cidCopy": string[];
  "cidCropRotate": string[];
  "cidCreditCard": string[];
  "cidCrop": string[];
  "cidCursorMove": string[];
  "cidCursor": string[];
  "cidCut": string[];
  "cidDataTransferDown": string[];
  "cidDataTransferUp": string[];
  "cidDeaf": string[];
  "cidDelete": string[];
  "cidDeveloperBoard": string[];
  "cidDescription": string[];
  "cidDeviceUnknown": string[];
  "cidDevicesImportant": string[];
  "cidDevicesOther": string[];
  "cidDevicesSlash": string[];
  "cidDevices": string[];
  "cidDial": string[];
  "cidDialpad": string[];
  "cidDiamond": string[];
  "cidDinner": string[];
  "cidDirections": string[];
  "cidDisabled": string[];
  "cidDns": string[];
  "cidDock": string[];
  "cidDocument": string[];
  "cidDog": string[];
  "cidDollarCircleSlash": string[];
  "cidDollarCircle": string[];
  "cidDollarSlash": string[];
  "cidDonate": string[];
  "cidDoor": string[];
  "cidDoubleQuoteSansLeft": string[];
  "cidDoubleQuoteSansRight": string[];
  "cidDoubleQuoteSerifLeft": string[];
  "cidDoubleQuoteSerifRight": string[];
  "cidDrinkAlcohol": string[];
  "cidDrink": string[];
  "cidDropSlash": string[];
  "cidDrop": string[];
  "cidDvr": string[];
  "cidEar": string[];
  "cidEco": string[];
  "cidEducation": string[];
  "cidElevator": string[];
  "cidEnvelopeClosed": string[];
  "cidEnvelopeLetter": string[];
  "cidEnvelopeMinus": string[];
  "cidEnvelopeOpen": string[];
  "cidEnvelopePlus": string[];
  "cidEqualizer": string[];
  "cidEthernetAlt": string[];
  "cidEthernet": string[];
  "cidEuroCircleSlash": string[];
  "cidEuroCircle": string[];
  "cidEuroSlash": string[];
  "cidEvStation": string[];
  "cidExcerpt": string[];
  "cidEnergyCircle": string[];
  "cidExclamationCircle": string[];
  "cidExclamation": string[];
  "cidExitToApp": string[];
  "cidExpandLeft": string[];
  "cidExpandDown": string[];
  "cidExpandRight": string[];
  "cidExpandUp": string[];
  "cidExposure": string[];
  "cidExternalLink": string[];
  "cidEyeSlash": string[];
  "cidEye": string[];
  "cidEyedropper": string[];
  "cidFaceDead": string[];
  "cidFace": string[];
  "cidFactorySlash": string[];
  "cidFactory": string[];
  "cidFastfood": string[];
  "cidFeaturedPlaylist": string[];
  "cidFax": string[];
  "cidFeaturedVideo": string[];
  "cidFiberDvr": string[];
  "cidFiberManual": string[];
  "cidFiberNew": string[];
  "cidFiberPin": string[];
  "cidFiberSmart": string[];
  "cidFileAcrobat": string[];
  "cidFileAdd": string[];
  "cidFileAudio": string[];
  "cidFileArchive": string[];
  "cidFileCode": string[];
  "cidFileDoc": string[];
  "cidFileExcel": string[];
  "cidFileImage": string[];
  "cidFilePowerpoint": string[];
  "cidFilePdf": string[];
  "cidFilePpt": string[];
  "cidFileVideo": string[];
  "cidFileWord": string[];
  "cidFileXls": string[];
  "cidFile": string[];
  "cidFilterFrames": string[];
  "cidFilterPhoto": string[];
  "cidFilter": string[];
  "cidFindInPage": string[];
  "cidFingerprint": string[];
  "cidFire": string[];
  "cidFindReplace": string[];
  "cidFlagAlt": string[];
  "cidFlagRectangle": string[];
  "cidFlagTriangle": string[];
  "cidFlag": string[];
  "cidFlightLand": string[];
  "cidFlightTakeoff": string[];
  "cidFlipToFront": string[];
  "cidFlipToBack": string[];
  "cidFlip": string[];
  "cidFlower": string[];
  "cidFolderAlt": string[];
  "cidFolderOpen": string[];
  "cidFolderPlus": string[];
  "cidFolderShared": string[];
  "cidFolderSpecial": string[];
  "cidFont": string[];
  "cidFolder": string[];
  "cidFootball": string[];
  "cidFridge": string[];
  "cidFork": string[];
  "cidFrown": string[];
  "cidFullscreenExit": string[];
  "cidFullscreen": string[];
  "cidFunctionsAlt": string[];
  "cidFunctions": string[];
  "cidGamepad": string[];
  "cidGarage": string[];
  "cidGem": string[];
  "cidGif": string[];
  "cidGift": string[];
  "cidGlobeLock": string[];
  "cidGlass": string[];
  "cidGolf": string[];
  "cidGlobe": string[];
  "cidGolfAlt": string[];
  "cidGradient": string[];
  "cidGrain": string[];
  "cidGridSlash": string[];
  "cidGraph": string[];
  "cidHamburgerMenu": string[];
  "cidGrid": string[];
  "cidHandPointer": string[];
  "cidHappy": string[];
  "cidHdrSlash": string[];
  "cidHardDrive": string[];
  "cidHd": string[];
  "cidHdr": string[];
  "cidHeadphonesMute": string[];
  "cidHeader": string[];
  "cidHeadphones": string[];
  "cidHeadphonesMic": string[];
  "cidHighlighter": string[];
  "cidHealing": string[];
  "cidHighQuality": string[];
  "cidHighligt": string[];
  "cidHome": string[];
  "cidHospital": string[];
  "cidHotel": string[];
  "cidHotTub": string[];
  "cidHistory": string[];
  "cidHourglass": string[];
  "cidHouse": string[];
  "cidHttps": string[];
  "cidHttp": string[];
  "cidHq": string[];
  "cidIdBadge": string[];
  "cidImageBroken": string[];
  "cidIdCard": string[];
  "cidImagePlus": string[];
  "cidInboxIn": string[];
  "cidImage": string[];
  "cidImages": string[];
  "cidInboxOut": string[];
  "cidInbox": string[];
  "cidIndentIncrease": string[];
  "cidIndentDecrease": string[];
  "cidIndustrySlash": string[];
  "cidInfinity": string[];
  "cidInfo": string[];
  "cidInputAntenna": string[];
  "cidInputComponent": string[];
  "cidInputHdmi": string[];
  "cidInputPowerOff": string[];
  "cidInputPower": string[];
  "cidInputSvideo": string[];
  "cidInput": string[];
  "cidInstitution": string[];
  "cidInvert": string[];
  "cidItalic": string[];
  "cidJustifyCenter": string[];
  "cidJustifyLeft": string[];
  "cidJustifyRight": string[];
  "cidKeyAlt": string[];
  "cidKey": string[];
  "cidKeyboard": string[];
  "cidKeyboardHide": string[];
  "cidKitchen": string[];
  "cidLan": string[];
  "cidLaptop": string[];
  "cidLanguage": string[];
  "cidLaundry": string[];
  "cidLayersSlash": string[];
  "cidLayers": string[];
  "cidLeaf": string[];
  "cidLemon": string[];
  "cidLevelDown": string[];
  "cidLevelUp": string[];
  "cidLibraryAdd": string[];
  "cidLibraryBookmark": string[];
  "cidLibraryBooks": string[];
  "cidLibraryBuilding": string[];
  "cidLibraryMusic": string[];
  "cidLibrary": string[];
  "cidLifeRing": string[];
  "cidLightbulb": string[];
  "cidLineSpacing": string[];
  "cidLineStyle": string[];
  "cidLineWeight": string[];
  "cidLinkBroken": string[];
  "cidLinkIntact": string[];
  "cidLinkAlt": string[];
  "cidLinkSlash": string[];
  "cidIndustry": string[];
  "cidLink": string[];
  "cidListFilter": string[];
  "cidListHighPriority": string[];
  "cidListLowPriority": string[];
  "cidListNumbered": string[];
  "cidListNumberedRtl": string[];
  "cidListRich": string[];
  "cidList": string[];
  "cidLocationGpsFixed": string[];
  "cidLocationGpsOff": string[];
  "cidLocationGps": string[];
  "cidLocationPinCheck": string[];
  "cidLocationPinEdit": string[];
  "cidLocationPinPlus": string[];
  "cidLocationPinSlash": string[];
  "cidLocationPin": string[];
  "cidLockLocked": string[];
  "cidLockMinus": string[];
  "cidLockPlus": string[];
  "cidLockUnlocked": string[];
  "cidLocomotive": string[];
  "cidLoop1": string[];
  "cidLoopCircular": string[];
  "cidLoopSquare": string[];
  "cidLoop": string[];
  "cidLoyalty": string[];
  "cidLowVision": string[];
  "cidMagnifyingGlass": string[];
  "cidMailbox": string[];
  "cidMapAlt": string[];
  "cidMail": string[];
  "cidMap": string[];
  "cidMediaEjectSquare": string[];
  "cidMediaEjectCircle": string[];
  "cidMediaEject": string[];
  "cidMediaPauseCircle": string[];
  "cidMediaPauseSquare": string[];
  "cidMediaPlayCircle": string[];
  "cidMediaPlaySquare": string[];
  "cidMediaRecordCircle": string[];
  "cidMediaRecordSquare": string[];
  "cidMediaSkipBackwardCircle": string[];
  "cidMediaSkipBackwardSquare": string[];
  "cidMediaSkipForwardCircle": string[];
  "cidMediaSkipForwardSquare": string[];
  "cidMediaStepBackwardCircle": string[];
  "cidMediaStepBackwardSquare": string[];
  "cidMediaStepBackward": string[];
  "cidMediaStepForwardCircle": string[];
  "cidMediaStepForwardSquare": string[];
  "cidMediaStepForward": string[];
  "cidMediaStopCircle": string[];
  "cidMediaStopSquare": string[];
  "cidMedicalCross": string[];
  "cidMeh": string[];
  "cidMemory": string[];
  "cidMenu": string[];
  "cidMicAlt": string[];
  "cidMicSettings": string[];
  "cidMicSlash": string[];
  "cidMic": string[];
  "cidMicrochip": string[];
  "cidMicrophoneAlt": string[];
  "cidMicrophoneSettings": string[];
  "cidMicrophoneSlash": string[];
  "cidMicrophone": string[];
  "cidMinusCircle": string[];
  "cidMinusSquare": string[];
  "cidMobileArrowAdd": string[];
  "cidMobileArrowRemove": string[];
  "cidMobileCheck": string[];
  "cidMobileDeveloperMode": string[];
  "cidMobileLandscape": string[];
  "cidMobileLock": string[];
  "cidMobileMinus": string[];
  "cidMobilePlus": string[];
  "cidMobilePortrait": string[];
  "cidMobileSettings": string[];
  "cidMobileSlash": string[];
  "cidMobileSms": string[];
  "cidMobileSpeaker": string[];
  "cidMobileVolume": string[];
  "cidMobileX": string[];
  "cidMobile": string[];
  "cidMoneyBillAlt": string[];
  "cidMoneyBill": string[];
  "cidMoneyBillAlt2": string[];
  "cidMoney": string[];
  "cidMonitor": string[];
  "cidMoodBad": string[];
  "cidMoodGood": string[];
  "cidMoodVeryBad": string[];
  "cidMoodVeryGood": string[];
  "cidMoon": string[];
  "cidMore": string[];
  "cidMotorbike": string[];
  "cidMouseAlt": string[];
  "cidMouse": string[];
  "cidMouthSlash": string[];
  "cidMouth": string[];
  "cidMove": string[];
  "cidMovieAlt": string[];
  "cidMovie": string[];
  "cidMugTea": string[];
  "cidMug": string[];
  "cidMusicNoteAlt": string[];
  "cidMusicNoteSlash": string[];
  "cidMusicNote": string[];
  "cidMusicVideo": string[];
  "cidNetworkCheck": string[];
  "cidNewReleases": string[];
  "cidNew": string[];
  "cidNewspaper": string[];
  "cidNoteAdd": string[];
  "cidNote": string[];
  "cidNotes": string[];
  "cidObjectGroup": string[];
  "cidObjectUngroup": string[];
  "cidOpacity": string[];
  "cidOpentype": string[];
  "cidOptions": string[];
  "cidOven": string[];
  "cidOverscanSettings": string[];
  "cidOverscan": string[];
  "cidPageRestore": string[];
  "cidPage": string[];
  "cidPageview": string[];
  "cidPaintBucket": string[];
  "cidPaint": string[];
  "cidPaperclip": string[];
  "cidPaperPlane": string[];
  "cidParagraph": string[];
  "cidParking": string[];
  "cidPaw": string[];
  "cidPenAlt": string[];
  "cidPenFancy": string[];
  "cidPenNib": string[];
  "cidPen": string[];
  "cidPencil": string[];
  "cidPeople": string[];
  "cidPeople_Plus": string[];
  "cidPercent": string[];
  "cidPersonFemale": string[];
  "cidPerson": string[];
  "cidPetrolStation": string[];
  "cidPhoneBluetooth": string[];
  "cidPhoneCallEnd": string[];
  "cidPhoneCall": string[];
  "cidPhoneCallback": string[];
  "cidPhoneCheck": string[];
  "cidPhoneForward": string[];
  "cidPhoneInTalk": string[];
  "cidPhoneLock": string[];
  "cidPhoneMinus": string[];
  "cidPhoneMissed": string[];
  "cidPhonePaused": string[];
  "cidPhonePlus": string[];
  "cidPhoneRingVolume": string[];
  "cidPhoneSettings": string[];
  "cidPhoneSlash": string[];
  "cidPhoneSquare": string[];
  "cidPhoneVolume": string[];
  "cidPhoneX": string[];
  "cidPhone": string[];
  "cidPictureInPictureAlt": string[];
  "cidPictureInPicture": string[];
  "cidPin": string[];
  "cidPlant": string[];
  "cidPizza": string[];
  "cidPlaylistAdd": string[];
  "cidPlaylistPlay": string[];
  "cidPlusCircle": string[];
  "cidPlaylistAddCheck": string[];
  "cidPool": string[];
  "cidPlusSquare": string[];
  "cidPlusOne": string[];
  "cidPortableWifiOff": string[];
  "cidPortableWifi": string[];
  "cidPowerSettings": string[];
  "cidPregnant": string[];
  "cidPowerStandby": string[];
  "cidPrint": string[];
  "cidPrinterSlash": string[];
  "cidPrinter": string[];
  "cidQueueAdd": string[];
  "cidQrCode": string[];
  "cidQueueMusic": string[];
  "cidQueuePlayNext": string[];
  "cidQueueRemove": string[];
  "cidQueue": string[];
  "cidRadio": string[];
  "cidRailway": string[];
  "cidRain": string[];
  "cidRandom": string[];
  "cidRecycle": string[];
  "cidReload": string[];
  "cidRecentActors": string[];
  "cidRemoteControl": string[];
  "cidRemoteSettings": string[];
  "cidReplay": string[];
  "cidReportSlash": string[];
  "cidReport": string[];
  "cidResizeHeight": string[];
  "cidResizeBoth": string[];
  "cidResizeWidth": string[];
  "cidRestaurantMenu": string[];
  "cidRestaurant": string[];
  "cidRestore": string[];
  "cidRoomSlash": string[];
  "cidRoom": string[];
  "cidRouter": string[];
  "cidRowing": string[];
  "cidRoundedCorner": string[];
  "cidRssSquare": string[];
  "cidRssAlt": string[];
  "cidRss": string[];
  "cidRubleCircleSlash": string[];
  "cidRubleSlash": string[];
  "cidSad": string[];
  "cidSatelite": string[];
  "cidSave": string[];
  "cidScanner": string[];
  "cidScreenDeskopSlash": string[];
  "cidScooter": string[];
  "cidSchool": string[];
  "cidScreenDesktop": string[];
  "cidScreenHorizontal": string[];
  "cidScreenLandscape": string[];
  "cidScreenLockHorizontal": string[];
  "cidScreenLockLandscape": string[];
  "cidScreenLockPortrait": string[];
  "cidScreenLockRotation": string[];
  "cidScreenLockVertical": string[];
  "cidScreenMirroring": string[];
  "cidScreenPortrait": string[];
  "cidScreenRotation": string[];
  "cidScreenSmartphone": string[];
  "cidScreenVertical": string[];
  "cidScript": string[];
  "cidSdcard": string[];
  "cidScrubber": string[];
  "cidSearch": string[];
  "cidSecurity": string[];
  "cidSelectAll": string[];
  "cidSelect": string[];
  "cidSend": string[];
  "cidRubleCircle": string[];
  "cidSettings": string[];
  "cidShareAlt": string[];
  "cidShareAll": string[];
  "cidShare": string[];
  "cidShieldAlt": string[];
  "cidShareBoxed": string[];
  "cidShieldCheck": string[];
  "cidShieldMinus": string[];
  "cidShieldPlus": string[];
  "cidShieldSlash": string[];
  "cidShieldX": string[];
  "cidShield": string[];
  "cidShopMediaTwo": string[];
  "cidShopMedia": string[];
  "cidShortText": string[];
  "cidShower": string[];
  "cidSignLanguage": string[];
  "cidSignalCellular0": string[];
  "cidSignalCellular1": string[];
  "cidSignalCellular2": string[];
  "cidSignalCellular4": string[];
  "cidSignalCellular3": string[];
  "cidSignalCellularNoInternet0": string[];
  "cidSignalCellularNoInternet1": string[];
  "cidSignalCellularNoInternet2": string[];
  "cidSignalCellularNoInternet3": string[];
  "cidSignalCellularNoInternet4": string[];
  "cidSignalCellularOff_1": string[];
  "cidSignpost": string[];
  "cidSimSlash": string[];
  "cidSim": string[];
  "cidSitemap": string[];
  "cidSlowMotion": string[];
  "cidSmilePlus": string[];
  "cidSmokeFree": string[];
  "cidSmile": string[];
  "cidSmokeSlash": string[];
  "cidPushchair": string[];
  "cidSmoke": string[];
  "cidSmokingRoom": string[];
  "cidSofa": string[];
  "cidSoccer": string[];
  "cidSorroundSound": string[];
  "cidSortAlphaUp": string[];
  "cidSortAlphaDown": string[];
  "cidSortNumericDown": string[];
  "cidSortAscending": string[];
  "cidSortNumericUp": string[];
  "cidSpa": string[];
  "cidSpaceBar": string[];
  "cidSortDescending": string[];
  "cidSpeak": string[];
  "cidSpeakerGroup": string[];
  "cidSpeaker": string[];
  "cidSpeechNotes": string[];
  "cidSpeechNotesSlash": string[];
  "cidSpeech": string[];
  "cidSpeedometer": string[];
  "cidSpreadsheet": string[];
  "cidStickyNote": string[];
  "cidStarHalf": string[];
  "cidStore": string[];
  "cidStorage": string[];
  "cidStream": string[];
  "cidStrikethrough": string[];
  "cidSubtitles": string[];
  "cidSubway": string[];
  "cidSun": string[];
  "cidSwapHorizontalCircle": string[];
  "cidSwapVerticalCircle": string[];
  "cidSwapHorizontal": string[];
  "cidSwapVertical": string[];
  "cidSyncDisabled": string[];
  "cidSyncProblem": string[];
  "cidSync": string[];
  "cidTablet": string[];
  "cidTags": string[];
  "cidTarget": string[];
  "cidSwimming": string[];
  "cidTask": string[];
  "cidTennisBall": string[];
  "cidTaxi": string[];
  "cidTennis": string[];
  "cidTag": string[];
  "cidTerminal": string[];
  "cidTerrain": string[];
  "cidTextDirectionLtr": string[];
  "cidTextDirectionRtl": string[];
  "cidTextFormatClear": string[];
  "cidTextHeight": string[];
  "cidSpeechBubble": string[];
  "cidTextRotationDown": string[];
  "cidTextRotateVertical": string[];
  "cidTextRotationUp": string[];
  "cidTextRotationNone": string[];
  "cidTextShapes": string[];
  "cidTextSize": string[];
  "cidTextSquare": string[];
  "cidTextStrike": string[];
  "cidTextWidth": string[];
  "cidText": string[];
  "cidThumbDown": string[];
  "cidThumbUp": string[];
  "cidTimeline": string[];
  "cidTimer": string[];
  "cidToggleOn": string[];
  "cidToggleOff": string[];
  "cidToll": string[];
  "cidToilet": string[];
  "cidTouchApp": string[];
  "cidTrainAlt": string[];
  "cidTram": string[];
  "cidTrain": string[];
  "cidTransferWithinAStation": string[];
  "cidTranslate": string[];
  "cidTrashAlt": string[];
  "cidTrashSweep": string[];
  "cidTrashArrowUp": string[];
  "cidTraffic": string[];
  "cidTrash": string[];
  "cidTrashX": string[];
  "cidTruck": string[];
  "cidTty": string[];
  "cidTvDvr": string[];
  "cidTvLive": string[];
  "cidTv": string[];
  "cidTvSlash": string[];
  "cidUnderline": string[];
  "cidUniversalAccess": string[];
  "cidUpdate": string[];
  "cidUserFemale": string[];
  "cidUserFollow": string[];
  "cidUserSecret": string[];
  "cidUserUnfollow": string[];
  "cidTransfer": string[];
  "cidUser": string[];
  "cidVector": string[];
  "cidVericalSplit": string[];
  "cidVerticalAlignBottom": string[];
  "cidVerticalAlignCenter": string[];
  "cidVerticalAlignTop": string[];
  "cidVideoLabel": string[];
  "cidVideoMissed": string[];
  "cidVideoSlash": string[];
  "cidVideoPlus": string[];
  "cidUsb": string[];
  "cidVideoSwitch": string[];
  "cidVideo": string[];
  "cidVideogame": string[];
  "cidVideoLibrary": string[];
  "cidViewArray": string[];
  "cidViewCarousel": string[];
  "cidViewColumn": string[];
  "cidViewModule": string[];
  "cidViewAgenda": string[];
  "cidViewQuilt": string[];
  "cidVoiceOverRecord": string[];
  "cidVoice": string[];
  "cidVoiceOverSlash": string[];
  "cidViewStream": string[];
  "cidVoicemail": string[];
  "cidVolumeLow": string[];
  "cidVolumeHigh": string[];
  "cidVolumeOff": string[];
  "cidVote": string[];
  "cidWallet": string[];
  "cidWallpaper": string[];
  "cidWarning": string[];
  "cidWatch": string[];
  "cidWc": string[];
  "cidWeightlifitng": string[];
  "cidWaves": string[];
  "cidWeights": string[];
  "cidWidgets": string[];
  "cidWifiLock": string[];
  "cidWifiSignal1": string[];
  "cidWifiSignal0": string[];
  "cidWifiSignal2": string[];
  "cidWifiSignal3": string[];
  "cidWifiSignalLock1": string[];
  "cidWifiSignalLock0": string[];
  "cidWifiSignalLock2": string[];
  "cidWifiSignalLock4": string[];
  "cidWheelchair": string[];
  "cidWifiSignalOff": string[];
  "cidWifi": string[];
  "cidWindowMaximize": string[];
  "cidWindowRestore": string[];
  "cidWindow": string[];
  "cidWindowMinimize": string[];
  "cidWrapText": string[];
  "cidXSquare": string[];
  "cidYenCircleSlash": string[];
  "cidYenCircle": string[];
  "cidWifiSignalLock3": string[];
  "cidZoomIn": string[];
  "cidZoomOut": string[];
  "cidXCircle": string[];
  "cidZoom": string[];
  "cidYenSlash": string[];
  "cidWifiSignal4": string[];
  "cidGlobeAltLock": string[];
  "cidGlobeAlt": string[];
}
export declare const cid3dRotate: string[];
export declare const cid4k: string[];
export declare const cid3d: string[];
export declare const cidAccessible: string[];
export declare const cidAccountLogout: string[];
export declare const cidActionUndo: string[];
export declare const cidAddressBook: string[];
export declare const cidAddressCard: string[];
export declare const cidAirplaneModeOff: string[];
export declare const cidAirplaneMode: string[];
export declare const cidAirplay: string[];
export declare const cidAlarmAdd: string[];
export declare const cidAlarmOff: string[];
export declare const cidAlarmSnooze: string[];
export declare const cidAlarmOn: string[];
export declare const cidAlarm: string[];
export declare const cidAlbum: string[];
export declare const cidAlignCenter: string[];
export declare const cidAlignLeft: string[];
export declare const cidActionRedo: string[];
export declare const cidAlignRight: string[];
export declare const cidAmericanFootball: string[];
export declare const cidAnimal: string[];
export declare const cidAperture: string[];
export declare const cidApple: string[];
export declare const cidApplicationsSettings: string[];
export declare const cidApplications: string[];
export declare const cidAppsSettings: string[];
export declare const cidApps: string[];
export declare const cidArrowCircleBottom: string[];
export declare const cidArchive: string[];
export declare const cidArrowCircleLeft: string[];
export declare const cidArrowCircleRight: string[];
export declare const cidArrowCircleTop: string[];
export declare const cidArrowThickCircleDown: string[];
export declare const cidArrowThickCircleLeft: string[];
export declare const cidArrowThickCircleRight: string[];
export declare const cidArrowThickCircleUp: string[];
export declare const cidArrowThickFromBottom: string[];
export declare const cidArrowThickFromLeft: string[];
export declare const cidArrowThickFromRight: string[];
export declare const cidArrowThickFromTop: string[];
export declare const cidArrowThickSquareLeft: string[];
export declare const cidArrowThickSquareDown: string[];
export declare const cidArrowThickSquareRight: string[];
export declare const cidArrowThickSquareUp: string[];
export declare const cidArrowThickToBottom: string[];
export declare const cidArrowThickToLeft: string[];
export declare const cidArrowThickToRight: string[];
export declare const cidArrowThickToTop: string[];
export declare const cidArtTrack: string[];
export declare const cidAssistiveListeningSystem: string[];
export declare const cidAsteriskCircle: string[];
export declare const cidAt: string[];
export declare const cidAudioDescription: string[];
export declare const cidAudioSpectrum: string[];
export declare const cidAudio: string[];
export declare const cidAvTimer: string[];
export declare const cidBabyCarriage: string[];
export declare const cidBaby: string[];
export declare const cidBackspace: string[];
export declare const cidBadge: string[];
export declare const cidBalanceScaleLeft: string[];
export declare const cidBalanceScaleRight: string[];
export declare const cidBalanceScale: string[];
export declare const cidBan: string[];
export declare const cidBank: string[];
export declare const cidBarcode: string[];
export declare const cidBarChart: string[];
export declare const cidBaseball: string[];
export declare const cidBasketArrowDown: string[];
export declare const cidBasketPlus: string[];
export declare const cidBasketLoaded: string[];
export declare const cidBasket: string[];
export declare const cidBath: string[];
export declare const cidBasketball: string[];
export declare const cidBathroom: string[];
export declare const cidBattery0: string[];
export declare const cidBattery2: string[];
export declare const cidBattery1: string[];
export declare const cidBattery3: string[];
export declare const cidBattery4: string[];
export declare const cidBatteryAlert: string[];
export declare const cidBatteryAlt1: string[];
export declare const cidBatteryAlt0: string[];
export declare const cidBatteryAlt2: string[];
export declare const cidBattery5: string[];
export declare const cidBatteryAltEmpty: string[];
export declare const cidBatteryAltFull: string[];
export declare const cidBatteryAlt3: string[];
export declare const cidBatteryCharge: string[];
export declare const cidBatteryAltSlash: string[];
export declare const cidBatteryEmpty: string[];
export declare const cidBatterySlash: string[];
export declare const cidBatteryFull: string[];
export declare const cidBatteryUnknown: string[];
export declare const cidBeachAccess: string[];
export declare const cidBeaker: string[];
export declare const cidBed: string[];
export declare const cidBellExclamation: string[];
export declare const cidBellPlus: string[];
export declare const cidBellRing: string[];
export declare const cidBellSlash: string[];
export declare const cidBell: string[];
export declare const cidBikeAlt: string[];
export declare const cidBirthdayCake: string[];
export declare const cidBlind: string[];
export declare const cidBluetoothConnected: string[];
export declare const cidBluetoothSearching: string[];
export declare const cidBluetoothSettings: string[];
export declare const cidBoatAlt: string[];
export declare const cidBluetooth: string[];
export declare const cidBluetoothSlash: string[];
export declare const cidBoat: string[];
export declare const cidBold: string[];
export declare const cidBoltCircle: string[];
export declare const cidBookOpen: string[];
export declare const cidBook: string[];
export declare const cidBookmark: string[];
export declare const cidBookmarks: string[];
export declare const cidBorderAll: string[];
export declare const cidBorderBottom: string[];
export declare const cidBorderHorizontal: string[];
export declare const cidBike: string[];
export declare const cidBorderClear: string[];
export declare const cidBorderInner: string[];
export declare const cidBorderLeft: string[];
export declare const cidBorderOuter: string[];
export declare const cidBorderRight: string[];
export declare const cidBorderStyle: string[];
export declare const cidBorderTop: string[];
export declare const cidBorderVertical: string[];
export declare const cidBowlingPins: string[];
export declare const cidBowling: string[];
export declare const cidBoxAlt: string[];
export declare const cidBraille: string[];
export declare const cidBox: string[];
export declare const cidBrandingWatermark: string[];
export declare const cidBriefcaseArrowLeft: string[];
export declare const cidBriefcaseArrowRight: string[];
export declare const cidBriefcaseSlash: string[];
export declare const cidBriefcase: string[];
export declare const cidBrightnessAuto: string[];
export declare const cidBrightnessLow: string[];
export declare const cidBrightnessHigh: string[];
export declare const cidBrightnessMedium: string[];
export declare const cidBrightness: string[];
export declare const cidBritishPoundCircle: string[];
export declare const cidBritishPoundSlash: string[];
export declare const cidBroadcastTower: string[];
export declare const cidBrowser: string[];
export declare const cidBrushAlt: string[];
export declare const cidBrush: string[];
export declare const cidBug: string[];
export declare const cidBuildingBusinessSlash: string[];
export declare const cidBuildingBusiness: string[];
export declare const cidBuildingSlash: string[];
export declare const cidBuilding: string[];
export declare const cidBullhorn: string[];
export declare const cidBusAlt: string[];
export declare const cidBusTimer: string[];
export declare const cidBurger: string[];
export declare const cidBus: string[];
export declare const cidCalculator: string[];
export declare const cidCalendarCheck: string[];
export declare const cidCalendarEvent: string[];
export declare const cidCalendarMinus: string[];
export declare const cidCalendarNote: string[];
export declare const cidCalendarPlus: string[];
export declare const cidCalendarToday: string[];
export declare const cidCalendarTimes: string[];
export declare const cidCalendarViewDay: string[];
export declare const cidCalendar: string[];
export declare const cidCallMade: string[];
export declare const cidCallMerge: string[];
export declare const cidCallMissedOutgoing: string[];
export declare const cidCallReceived: string[];
export declare const cidCallMissed: string[];
export declare const cidCallSplit: string[];
export declare const cidCallSwapCalls: string[];
export declare const cidCallToAction: string[];
export declare const cidCameraControl: string[];
export declare const cidCameraEnhance: string[];
export declare const cidCameraPlus: string[];
export declare const cidCameraRoll: string[];
export declare const cidCameraSwitch: string[];
export declare const cidCamera: string[];
export declare const cidCarAlt: string[];
export declare const cidCar: string[];
export declare const cidCardGiftcard: string[];
export declare const cidCardMembership: string[];
export declare const cidCardTravel: string[];
export declare const cidCaretBottom: string[];
export declare const cidCaretLeft: string[];
export declare const cidCaretRight: string[];
export declare const cidCaretTop: string[];
export declare const cidCartArrowDown: string[];
export declare const cidCartLoaded: string[];
export declare const cidCartPlus: string[];
export declare const cidCartSlash: string[];
export declare const cidCart: string[];
export declare const cidCash: string[];
export declare const cidCasino: string[];
export declare const cidCastConnected: string[];
export declare const cidCastForEducation: string[];
export declare const cidCast: string[];
export declare const cidCat: string[];
export declare const cidCc: string[];
export declare const cidCenterFocusWeak: string[];
export declare const cidCenterFocus: string[];
export declare const cidChalkboardTeacher: string[];
export declare const cidChartArea: string[];
export declare const cidChartBubble: string[];
export declare const cidChartDonut: string[];
export declare const cidChartLine: string[];
export declare const cidChartMultiline: string[];
export declare const cidChartPie: string[];
export declare const cidChartShow: string[];
export declare const cidChart: string[];
export declare const cidChartTable: string[];
export declare const cidChatBubble: string[];
export declare const cidChatSquare: string[];
export declare const cidCheckAlt: string[];
export declare const cidCheckCircle: string[];
export declare const cidCheckDoubleAlt: string[];
export declare const cidCheckDouble: string[];
export declare const cidCheck: string[];
export declare const cidChevronBottom: string[];
export declare const cidChevronCircleDownAlt: string[];
export declare const cidChevronCircleDown: string[];
export declare const cidChevronCircleLeftAlt: string[];
export declare const cidChevronCircleLeft: string[];
export declare const cidChevronCircleRightAlt: string[];
export declare const cidChevronCircleRight: string[];
export declare const cidChevronCircleUpAlt: string[];
export declare const cidChevronCircleUp: string[];
export declare const cidChevronDoubleDown: string[];
export declare const cidChevronDoubleDownAlt: string[];
export declare const cidChevronDoubleLeftAlt: string[];
export declare const cidChevronDoubleLeft: string[];
export declare const cidChevronDoubleRightAlt: string[];
export declare const cidChevronDoubleRight: string[];
export declare const cidChevronDoubleUpAlt: string[];
export declare const cidChevronDoubleUp: string[];
export declare const cidChevronBottomAlt: string[];
export declare const cidChevronLeftAlt: string[];
export declare const cidChevronRightAlt: string[];
export declare const cidChevronSquareDown: string[];
export declare const cidChevronSquareDownAlt: string[];
export declare const cidChevronSquareLeftAlt: string[];
export declare const cidChevronSquareLeft: string[];
export declare const cidChevronSquareRight: string[];
export declare const cidChevronSquareRightAlt: string[];
export declare const cidChevronSquareUpAlt: string[];
export declare const cidChevronSquareUp: string[];
export declare const cidChevronTopAlt: string[];
export declare const cidChildFriendly: string[];
export declare const cidClearAll: string[];
export declare const cidChild: string[];
export declare const cidClipboard: string[];
export declare const cidCity: string[];
export declare const cidClock: string[];
export declare const cidClone: string[];
export declare const cidCloudCheck: string[];
export declare const cidClosedCaptioning: string[];
export declare const cidCloudSlash: string[];
export declare const cidCloudDownload: string[];
export declare const cidCloudCircle: string[];
export declare const cidCloudUpload: string[];
export declare const cidCloudy: string[];
export declare const cidCog: string[];
export declare const cidCode: string[];
export declare const cidCoffee: string[];
export declare const cidColorBorder: string[];
export declare const cidColorFill: string[];
export declare const cidColorPalette: string[];
export declare const cidColumns: string[];
export declare const cidCommand: string[];
export declare const cidCloud: string[];
export declare const cidCommentBubbleCheck: string[];
export declare const cidCommentBubbleEdit: string[];
export declare const cidCommentBubbleExclamation: string[];
export declare const cidCommentBubbleLines: string[];
export declare const cidCommentBubbleMinus: string[];
export declare const cidCommentBubblePlus: string[];
export declare const cidCommentBubbleQuestion: string[];
export declare const cidCommentBubbleSmile: string[];
export declare const cidCommentBubbleX: string[];
export declare const cidCommentBubble: string[];
export declare const cidCommentSquareEdit: string[];
export declare const cidCommentSquareCheck: string[];
export declare const cidCommentSquareExclamation: string[];
export declare const cidCommentSquareLines: string[];
export declare const cidCommentSquareImage: string[];
export declare const cidCommentSquareMinus: string[];
export declare const cidCommentSquareRateReview: string[];
export declare const cidCommentSquare: string[];
export declare const cidCommentSquareSmile: string[];
export declare const cidCommentSquarePlus: string[];
export declare const cidCommute: string[];
export declare const cidCompare: string[];
export declare const cidCompassCalibration: string[];
export declare const cidCompassSlash: string[];
export declare const cidCompass: string[];
export declare const cidCompress: string[];
export declare const cidContactPhone: string[];
export declare const cidCompressWide: string[];
export declare const cidContactMail: string[];
export declare const cidContact: string[];
export declare const cidCommentSquareX: string[];
export declare const cidContacts: string[];
export declare const cidContrast: string[];
export declare const cidControl: string[];
export declare const cidCouch: string[];
export declare const cidCopy: string[];
export declare const cidCropRotate: string[];
export declare const cidCreditCard: string[];
export declare const cidCrop: string[];
export declare const cidCursorMove: string[];
export declare const cidCursor: string[];
export declare const cidCut: string[];
export declare const cidDataTransferDown: string[];
export declare const cidDataTransferUp: string[];
export declare const cidDeaf: string[];
export declare const cidDelete: string[];
export declare const cidDeveloperBoard: string[];
export declare const cidDescription: string[];
export declare const cidDeviceUnknown: string[];
export declare const cidDevicesImportant: string[];
export declare const cidDevicesOther: string[];
export declare const cidDevicesSlash: string[];
export declare const cidDevices: string[];
export declare const cidDial: string[];
export declare const cidDialpad: string[];
export declare const cidDiamond: string[];
export declare const cidDinner: string[];
export declare const cidDirections: string[];
export declare const cidDisabled: string[];
export declare const cidDns: string[];
export declare const cidDock: string[];
export declare const cidDocument: string[];
export declare const cidDog: string[];
export declare const cidDollarCircleSlash: string[];
export declare const cidDollarCircle: string[];
export declare const cidDollarSlash: string[];
export declare const cidDonate: string[];
export declare const cidDoor: string[];
export declare const cidDoubleQuoteSansLeft: string[];
export declare const cidDoubleQuoteSansRight: string[];
export declare const cidDoubleQuoteSerifLeft: string[];
export declare const cidDoubleQuoteSerifRight: string[];
export declare const cidDrinkAlcohol: string[];
export declare const cidDrink: string[];
export declare const cidDropSlash: string[];
export declare const cidDrop: string[];
export declare const cidDvr: string[];
export declare const cidEar: string[];
export declare const cidEco: string[];
export declare const cidEducation: string[];
export declare const cidElevator: string[];
export declare const cidEnvelopeClosed: string[];
export declare const cidEnvelopeLetter: string[];
export declare const cidEnvelopeMinus: string[];
export declare const cidEnvelopeOpen: string[];
export declare const cidEnvelopePlus: string[];
export declare const cidEqualizer: string[];
export declare const cidEthernetAlt: string[];
export declare const cidEthernet: string[];
export declare const cidEuroCircleSlash: string[];
export declare const cidEuroCircle: string[];
export declare const cidEuroSlash: string[];
export declare const cidEvStation: string[];
export declare const cidExcerpt: string[];
export declare const cidEnergyCircle: string[];
export declare const cidExclamationCircle: string[];
export declare const cidExclamation: string[];
export declare const cidExitToApp: string[];
export declare const cidExpandLeft: string[];
export declare const cidExpandDown: string[];
export declare const cidExpandRight: string[];
export declare const cidExpandUp: string[];
export declare const cidExposure: string[];
export declare const cidExternalLink: string[];
export declare const cidEyeSlash: string[];
export declare const cidEye: string[];
export declare const cidEyedropper: string[];
export declare const cidFaceDead: string[];
export declare const cidFace: string[];
export declare const cidFactorySlash: string[];
export declare const cidFactory: string[];
export declare const cidFastfood: string[];
export declare const cidFeaturedPlaylist: string[];
export declare const cidFax: string[];
export declare const cidFeaturedVideo: string[];
export declare const cidFiberDvr: string[];
export declare const cidFiberManual: string[];
export declare const cidFiberNew: string[];
export declare const cidFiberPin: string[];
export declare const cidFiberSmart: string[];
export declare const cidFileAcrobat: string[];
export declare const cidFileAdd: string[];
export declare const cidFileAudio: string[];
export declare const cidFileArchive: string[];
export declare const cidFileCode: string[];
export declare const cidFileDoc: string[];
export declare const cidFileExcel: string[];
export declare const cidFileImage: string[];
export declare const cidFilePowerpoint: string[];
export declare const cidFilePdf: string[];
export declare const cidFilePpt: string[];
export declare const cidFileVideo: string[];
export declare const cidFileWord: string[];
export declare const cidFileXls: string[];
export declare const cidFile: string[];
export declare const cidFilterFrames: string[];
export declare const cidFilterPhoto: string[];
export declare const cidFilter: string[];
export declare const cidFindInPage: string[];
export declare const cidFingerprint: string[];
export declare const cidFire: string[];
export declare const cidFindReplace: string[];
export declare const cidFlagAlt: string[];
export declare const cidFlagRectangle: string[];
export declare const cidFlagTriangle: string[];
export declare const cidFlag: string[];
export declare const cidFlightLand: string[];
export declare const cidFlightTakeoff: string[];
export declare const cidFlipToFront: string[];
export declare const cidFlipToBack: string[];
export declare const cidFlip: string[];
export declare const cidFlower: string[];
export declare const cidFolderAlt: string[];
export declare const cidFolderOpen: string[];
export declare const cidFolderPlus: string[];
export declare const cidFolderShared: string[];
export declare const cidFolderSpecial: string[];
export declare const cidFont: string[];
export declare const cidFolder: string[];
export declare const cidFootball: string[];
export declare const cidFridge: string[];
export declare const cidFork: string[];
export declare const cidFrown: string[];
export declare const cidFullscreenExit: string[];
export declare const cidFullscreen: string[];
export declare const cidFunctionsAlt: string[];
export declare const cidFunctions: string[];
export declare const cidGamepad: string[];
export declare const cidGarage: string[];
export declare const cidGem: string[];
export declare const cidGif: string[];
export declare const cidGift: string[];
export declare const cidGlobeLock: string[];
export declare const cidGlass: string[];
export declare const cidGolf: string[];
export declare const cidGlobe: string[];
export declare const cidGolfAlt: string[];
export declare const cidGradient: string[];
export declare const cidGrain: string[];
export declare const cidGridSlash: string[];
export declare const cidGraph: string[];
export declare const cidHamburgerMenu: string[];
export declare const cidGrid: string[];
export declare const cidHandPointer: string[];
export declare const cidHappy: string[];
export declare const cidHdrSlash: string[];
export declare const cidHardDrive: string[];
export declare const cidHd: string[];
export declare const cidHdr: string[];
export declare const cidHeadphonesMute: string[];
export declare const cidHeader: string[];
export declare const cidHeadphones: string[];
export declare const cidHeadphonesMic: string[];
export declare const cidHighlighter: string[];
export declare const cidHealing: string[];
export declare const cidHighQuality: string[];
export declare const cidHighligt: string[];
export declare const cidHome: string[];
export declare const cidHospital: string[];
export declare const cidHotel: string[];
export declare const cidHotTub: string[];
export declare const cidHistory: string[];
export declare const cidHourglass: string[];
export declare const cidHouse: string[];
export declare const cidHttps: string[];
export declare const cidHttp: string[];
export declare const cidHq: string[];
export declare const cidIdBadge: string[];
export declare const cidImageBroken: string[];
export declare const cidIdCard: string[];
export declare const cidImagePlus: string[];
export declare const cidInboxIn: string[];
export declare const cidImage: string[];
export declare const cidImages: string[];
export declare const cidInboxOut: string[];
export declare const cidInbox: string[];
export declare const cidIndentIncrease: string[];
export declare const cidIndentDecrease: string[];
export declare const cidIndustrySlash: string[];
export declare const cidInfinity: string[];
export declare const cidInfo: string[];
export declare const cidInputAntenna: string[];
export declare const cidInputComponent: string[];
export declare const cidInputHdmi: string[];
export declare const cidInputPowerOff: string[];
export declare const cidInputPower: string[];
export declare const cidInputSvideo: string[];
export declare const cidInput: string[];
export declare const cidInstitution: string[];
export declare const cidInvert: string[];
export declare const cidItalic: string[];
export declare const cidJustifyCenter: string[];
export declare const cidJustifyLeft: string[];
export declare const cidJustifyRight: string[];
export declare const cidKeyAlt: string[];
export declare const cidKey: string[];
export declare const cidKeyboard: string[];
export declare const cidKeyboardHide: string[];
export declare const cidKitchen: string[];
export declare const cidLan: string[];
export declare const cidLaptop: string[];
export declare const cidLanguage: string[];
export declare const cidLaundry: string[];
export declare const cidLayersSlash: string[];
export declare const cidLayers: string[];
export declare const cidLeaf: string[];
export declare const cidLemon: string[];
export declare const cidLevelDown: string[];
export declare const cidLevelUp: string[];
export declare const cidLibraryAdd: string[];
export declare const cidLibraryBookmark: string[];
export declare const cidLibraryBooks: string[];
export declare const cidLibraryBuilding: string[];
export declare const cidLibraryMusic: string[];
export declare const cidLibrary: string[];
export declare const cidLifeRing: string[];
export declare const cidLightbulb: string[];
export declare const cidLineSpacing: string[];
export declare const cidLineStyle: string[];
export declare const cidLineWeight: string[];
export declare const cidLinkBroken: string[];
export declare const cidLinkIntact: string[];
export declare const cidLinkAlt: string[];
export declare const cidLinkSlash: string[];
export declare const cidIndustry: string[];
export declare const cidLink: string[];
export declare const cidListFilter: string[];
export declare const cidListHighPriority: string[];
export declare const cidListLowPriority: string[];
export declare const cidListNumbered: string[];
export declare const cidListNumberedRtl: string[];
export declare const cidListRich: string[];
export declare const cidList: string[];
export declare const cidLocationGpsFixed: string[];
export declare const cidLocationGpsOff: string[];
export declare const cidLocationGps: string[];
export declare const cidLocationPinCheck: string[];
export declare const cidLocationPinEdit: string[];
export declare const cidLocationPinPlus: string[];
export declare const cidLocationPinSlash: string[];
export declare const cidLocationPin: string[];
export declare const cidLockLocked: string[];
export declare const cidLockMinus: string[];
export declare const cidLockPlus: string[];
export declare const cidLockUnlocked: string[];
export declare const cidLocomotive: string[];
export declare const cidLoop1: string[];
export declare const cidLoopCircular: string[];
export declare const cidLoopSquare: string[];
export declare const cidLoop: string[];
export declare const cidLoyalty: string[];
export declare const cidLowVision: string[];
export declare const cidMagnifyingGlass: string[];
export declare const cidMailbox: string[];
export declare const cidMapAlt: string[];
export declare const cidMail: string[];
export declare const cidMap: string[];
export declare const cidMediaEjectSquare: string[];
export declare const cidMediaEjectCircle: string[];
export declare const cidMediaEject: string[];
export declare const cidMediaPauseCircle: string[];
export declare const cidMediaPauseSquare: string[];
export declare const cidMediaPlayCircle: string[];
export declare const cidMediaPlaySquare: string[];
export declare const cidMediaRecordCircle: string[];
export declare const cidMediaRecordSquare: string[];
export declare const cidMediaSkipBackwardCircle: string[];
export declare const cidMediaSkipBackwardSquare: string[];
export declare const cidMediaSkipForwardCircle: string[];
export declare const cidMediaSkipForwardSquare: string[];
export declare const cidMediaStepBackwardCircle: string[];
export declare const cidMediaStepBackwardSquare: string[];
export declare const cidMediaStepBackward: string[];
export declare const cidMediaStepForwardCircle: string[];
export declare const cidMediaStepForwardSquare: string[];
export declare const cidMediaStepForward: string[];
export declare const cidMediaStopCircle: string[];
export declare const cidMediaStopSquare: string[];
export declare const cidMedicalCross: string[];
export declare const cidMeh: string[];
export declare const cidMemory: string[];
export declare const cidMenu: string[];
export declare const cidMicAlt: string[];
export declare const cidMicSettings: string[];
export declare const cidMicSlash: string[];
export declare const cidMic: string[];
export declare const cidMicrochip: string[];
export declare const cidMicrophoneAlt: string[];
export declare const cidMicrophoneSettings: string[];
export declare const cidMicrophoneSlash: string[];
export declare const cidMicrophone: string[];
export declare const cidMinusCircle: string[];
export declare const cidMinusSquare: string[];
export declare const cidMobileArrowAdd: string[];
export declare const cidMobileArrowRemove: string[];
export declare const cidMobileCheck: string[];
export declare const cidMobileDeveloperMode: string[];
export declare const cidMobileLandscape: string[];
export declare const cidMobileLock: string[];
export declare const cidMobileMinus: string[];
export declare const cidMobilePlus: string[];
export declare const cidMobilePortrait: string[];
export declare const cidMobileSettings: string[];
export declare const cidMobileSlash: string[];
export declare const cidMobileSms: string[];
export declare const cidMobileSpeaker: string[];
export declare const cidMobileVolume: string[];
export declare const cidMobileX: string[];
export declare const cidMobile: string[];
export declare const cidMoneyBillAlt: string[];
export declare const cidMoneyBill: string[];
export declare const cidMoneyBillAlt2: string[];
export declare const cidMoney: string[];
export declare const cidMonitor: string[];
export declare const cidMoodBad: string[];
export declare const cidMoodGood: string[];
export declare const cidMoodVeryBad: string[];
export declare const cidMoodVeryGood: string[];
export declare const cidMoon: string[];
export declare const cidMore: string[];
export declare const cidMotorbike: string[];
export declare const cidMouseAlt: string[];
export declare const cidMouse: string[];
export declare const cidMouthSlash: string[];
export declare const cidMouth: string[];
export declare const cidMove: string[];
export declare const cidMovieAlt: string[];
export declare const cidMovie: string[];
export declare const cidMugTea: string[];
export declare const cidMug: string[];
export declare const cidMusicNoteAlt: string[];
export declare const cidMusicNoteSlash: string[];
export declare const cidMusicNote: string[];
export declare const cidMusicVideo: string[];
export declare const cidNetworkCheck: string[];
export declare const cidNewReleases: string[];
export declare const cidNew: string[];
export declare const cidNewspaper: string[];
export declare const cidNoteAdd: string[];
export declare const cidNote: string[];
export declare const cidNotes: string[];
export declare const cidObjectGroup: string[];
export declare const cidObjectUngroup: string[];
export declare const cidOpacity: string[];
export declare const cidOpentype: string[];
export declare const cidOptions: string[];
export declare const cidOven: string[];
export declare const cidOverscanSettings: string[];
export declare const cidOverscan: string[];
export declare const cidPageRestore: string[];
export declare const cidPage: string[];
export declare const cidPageview: string[];
export declare const cidPaintBucket: string[];
export declare const cidPaint: string[];
export declare const cidPaperclip: string[];
export declare const cidPaperPlane: string[];
export declare const cidParagraph: string[];
export declare const cidParking: string[];
export declare const cidPaw: string[];
export declare const cidPenAlt: string[];
export declare const cidPenFancy: string[];
export declare const cidPenNib: string[];
export declare const cidPen: string[];
export declare const cidPencil: string[];
export declare const cidPeople: string[];
export declare const cidPeople_Plus: string[];
export declare const cidPercent: string[];
export declare const cidPersonFemale: string[];
export declare const cidPerson: string[];
export declare const cidPetrolStation: string[];
export declare const cidPhoneBluetooth: string[];
export declare const cidPhoneCallEnd: string[];
export declare const cidPhoneCall: string[];
export declare const cidPhoneCallback: string[];
export declare const cidPhoneCheck: string[];
export declare const cidPhoneForward: string[];
export declare const cidPhoneInTalk: string[];
export declare const cidPhoneLock: string[];
export declare const cidPhoneMinus: string[];
export declare const cidPhoneMissed: string[];
export declare const cidPhonePaused: string[];
export declare const cidPhonePlus: string[];
export declare const cidPhoneRingVolume: string[];
export declare const cidPhoneSettings: string[];
export declare const cidPhoneSlash: string[];
export declare const cidPhoneSquare: string[];
export declare const cidPhoneVolume: string[];
export declare const cidPhoneX: string[];
export declare const cidPhone: string[];
export declare const cidPictureInPictureAlt: string[];
export declare const cidPictureInPicture: string[];
export declare const cidPin: string[];
export declare const cidPlant: string[];
export declare const cidPizza: string[];
export declare const cidPlaylistAdd: string[];
export declare const cidPlaylistPlay: string[];
export declare const cidPlusCircle: string[];
export declare const cidPlaylistAddCheck: string[];
export declare const cidPool: string[];
export declare const cidPlusSquare: string[];
export declare const cidPlusOne: string[];
export declare const cidPortableWifiOff: string[];
export declare const cidPortableWifi: string[];
export declare const cidPowerSettings: string[];
export declare const cidPregnant: string[];
export declare const cidPowerStandby: string[];
export declare const cidPrint: string[];
export declare const cidPrinterSlash: string[];
export declare const cidPrinter: string[];
export declare const cidQueueAdd: string[];
export declare const cidQrCode: string[];
export declare const cidQueueMusic: string[];
export declare const cidQueuePlayNext: string[];
export declare const cidQueueRemove: string[];
export declare const cidQueue: string[];
export declare const cidRadio: string[];
export declare const cidRailway: string[];
export declare const cidRain: string[];
export declare const cidRandom: string[];
export declare const cidRecycle: string[];
export declare const cidReload: string[];
export declare const cidRecentActors: string[];
export declare const cidRemoteControl: string[];
export declare const cidRemoteSettings: string[];
export declare const cidReplay: string[];
export declare const cidReportSlash: string[];
export declare const cidReport: string[];
export declare const cidResizeHeight: string[];
export declare const cidResizeBoth: string[];
export declare const cidResizeWidth: string[];
export declare const cidRestaurantMenu: string[];
export declare const cidRestaurant: string[];
export declare const cidRestore: string[];
export declare const cidRoomSlash: string[];
export declare const cidRoom: string[];
export declare const cidRouter: string[];
export declare const cidRowing: string[];
export declare const cidRoundedCorner: string[];
export declare const cidRssSquare: string[];
export declare const cidRssAlt: string[];
export declare const cidRss: string[];
export declare const cidRubleCircleSlash: string[];
export declare const cidRubleSlash: string[];
export declare const cidSad: string[];
export declare const cidSatelite: string[];
export declare const cidSave: string[];
export declare const cidScanner: string[];
export declare const cidScreenDeskopSlash: string[];
export declare const cidScooter: string[];
export declare const cidSchool: string[];
export declare const cidScreenDesktop: string[];
export declare const cidScreenHorizontal: string[];
export declare const cidScreenLandscape: string[];
export declare const cidScreenLockHorizontal: string[];
export declare const cidScreenLockLandscape: string[];
export declare const cidScreenLockPortrait: string[];
export declare const cidScreenLockRotation: string[];
export declare const cidScreenLockVertical: string[];
export declare const cidScreenMirroring: string[];
export declare const cidScreenPortrait: string[];
export declare const cidScreenRotation: string[];
export declare const cidScreenSmartphone: string[];
export declare const cidScreenVertical: string[];
export declare const cidScript: string[];
export declare const cidSdcard: string[];
export declare const cidScrubber: string[];
export declare const cidSearch: string[];
export declare const cidSecurity: string[];
export declare const cidSelectAll: string[];
export declare const cidSelect: string[];
export declare const cidSend: string[];
export declare const cidRubleCircle: string[];
export declare const cidSettings: string[];
export declare const cidShareAlt: string[];
export declare const cidShareAll: string[];
export declare const cidShare: string[];
export declare const cidShieldAlt: string[];
export declare const cidShareBoxed: string[];
export declare const cidShieldCheck: string[];
export declare const cidShieldMinus: string[];
export declare const cidShieldPlus: string[];
export declare const cidShieldSlash: string[];
export declare const cidShieldX: string[];
export declare const cidShield: string[];
export declare const cidShopMediaTwo: string[];
export declare const cidShopMedia: string[];
export declare const cidShortText: string[];
export declare const cidShower: string[];
export declare const cidSignLanguage: string[];
export declare const cidSignalCellular0: string[];
export declare const cidSignalCellular1: string[];
export declare const cidSignalCellular2: string[];
export declare const cidSignalCellular4: string[];
export declare const cidSignalCellular3: string[];
export declare const cidSignalCellularNoInternet0: string[];
export declare const cidSignalCellularNoInternet1: string[];
export declare const cidSignalCellularNoInternet2: string[];
export declare const cidSignalCellularNoInternet3: string[];
export declare const cidSignalCellularNoInternet4: string[];
export declare const cidSignalCellularOff_1: string[];
export declare const cidSignpost: string[];
export declare const cidSimSlash: string[];
export declare const cidSim: string[];
export declare const cidSitemap: string[];
export declare const cidSlowMotion: string[];
export declare const cidSmilePlus: string[];
export declare const cidSmokeFree: string[];
export declare const cidSmile: string[];
export declare const cidSmokeSlash: string[];
export declare const cidPushchair: string[];
export declare const cidSmoke: string[];
export declare const cidSmokingRoom: string[];
export declare const cidSofa: string[];
export declare const cidSoccer: string[];
export declare const cidSorroundSound: string[];
export declare const cidSortAlphaUp: string[];
export declare const cidSortAlphaDown: string[];
export declare const cidSortNumericDown: string[];
export declare const cidSortAscending: string[];
export declare const cidSortNumericUp: string[];
export declare const cidSpa: string[];
export declare const cidSpaceBar: string[];
export declare const cidSortDescending: string[];
export declare const cidSpeak: string[];
export declare const cidSpeakerGroup: string[];
export declare const cidSpeaker: string[];
export declare const cidSpeechNotes: string[];
export declare const cidSpeechNotesSlash: string[];
export declare const cidSpeech: string[];
export declare const cidSpeedometer: string[];
export declare const cidSpreadsheet: string[];
export declare const cidStickyNote: string[];
export declare const cidStarHalf: string[];
export declare const cidStore: string[];
export declare const cidStorage: string[];
export declare const cidStream: string[];
export declare const cidStrikethrough: string[];
export declare const cidSubtitles: string[];
export declare const cidSubway: string[];
export declare const cidSun: string[];
export declare const cidSwapHorizontalCircle: string[];
export declare const cidSwapVerticalCircle: string[];
export declare const cidSwapHorizontal: string[];
export declare const cidSwapVertical: string[];
export declare const cidSyncDisabled: string[];
export declare const cidSyncProblem: string[];
export declare const cidSync: string[];
export declare const cidTablet: string[];
export declare const cidTags: string[];
export declare const cidTarget: string[];
export declare const cidSwimming: string[];
export declare const cidTask: string[];
export declare const cidTennisBall: string[];
export declare const cidTaxi: string[];
export declare const cidTennis: string[];
export declare const cidTag: string[];
export declare const cidTerminal: string[];
export declare const cidTerrain: string[];
export declare const cidTextDirectionLtr: string[];
export declare const cidTextDirectionRtl: string[];
export declare const cidTextFormatClear: string[];
export declare const cidTextHeight: string[];
export declare const cidSpeechBubble: string[];
export declare const cidTextRotationDown: string[];
export declare const cidTextRotateVertical: string[];
export declare const cidTextRotationUp: string[];
export declare const cidTextRotationNone: string[];
export declare const cidTextShapes: string[];
export declare const cidTextSize: string[];
export declare const cidTextSquare: string[];
export declare const cidTextStrike: string[];
export declare const cidTextWidth: string[];
export declare const cidText: string[];
export declare const cidThumbDown: string[];
export declare const cidThumbUp: string[];
export declare const cidTimeline: string[];
export declare const cidTimer: string[];
export declare const cidToggleOn: string[];
export declare const cidToggleOff: string[];
export declare const cidToll: string[];
export declare const cidToilet: string[];
export declare const cidTouchApp: string[];
export declare const cidTrainAlt: string[];
export declare const cidTram: string[];
export declare const cidTrain: string[];
export declare const cidTransferWithinAStation: string[];
export declare const cidTranslate: string[];
export declare const cidTrashAlt: string[];
export declare const cidTrashSweep: string[];
export declare const cidTrashArrowUp: string[];
export declare const cidTraffic: string[];
export declare const cidTrash: string[];
export declare const cidTrashX: string[];
export declare const cidTruck: string[];
export declare const cidTty: string[];
export declare const cidTvDvr: string[];
export declare const cidTvLive: string[];
export declare const cidTv: string[];
export declare const cidTvSlash: string[];
export declare const cidUnderline: string[];
export declare const cidUniversalAccess: string[];
export declare const cidUpdate: string[];
export declare const cidUserFemale: string[];
export declare const cidUserFollow: string[];
export declare const cidUserSecret: string[];
export declare const cidUserUnfollow: string[];
export declare const cidTransfer: string[];
export declare const cidUser: string[];
export declare const cidVector: string[];
export declare const cidVericalSplit: string[];
export declare const cidVerticalAlignBottom: string[];
export declare const cidVerticalAlignCenter: string[];
export declare const cidVerticalAlignTop: string[];
export declare const cidVideoLabel: string[];
export declare const cidVideoMissed: string[];
export declare const cidVideoSlash: string[];
export declare const cidVideoPlus: string[];
export declare const cidUsb: string[];
export declare const cidVideoSwitch: string[];
export declare const cidVideo: string[];
export declare const cidVideogame: string[];
export declare const cidVideoLibrary: string[];
export declare const cidViewArray: string[];
export declare const cidViewCarousel: string[];
export declare const cidViewColumn: string[];
export declare const cidViewModule: string[];
export declare const cidViewAgenda: string[];
export declare const cidViewQuilt: string[];
export declare const cidVoiceOverRecord: string[];
export declare const cidVoice: string[];
export declare const cidVoiceOverSlash: string[];
export declare const cidViewStream: string[];
export declare const cidVoicemail: string[];
export declare const cidVolumeLow: string[];
export declare const cidVolumeHigh: string[];
export declare const cidVolumeOff: string[];
export declare const cidVote: string[];
export declare const cidWallet: string[];
export declare const cidWallpaper: string[];
export declare const cidWarning: string[];
export declare const cidWatch: string[];
export declare const cidWc: string[];
export declare const cidWeightlifitng: string[];
export declare const cidWaves: string[];
export declare const cidWeights: string[];
export declare const cidWidgets: string[];
export declare const cidWifiLock: string[];
export declare const cidWifiSignal1: string[];
export declare const cidWifiSignal0: string[];
export declare const cidWifiSignal2: string[];
export declare const cidWifiSignal3: string[];
export declare const cidWifiSignalLock1: string[];
export declare const cidWifiSignalLock0: string[];
export declare const cidWifiSignalLock2: string[];
export declare const cidWifiSignalLock4: string[];
export declare const cidWheelchair: string[];
export declare const cidWifiSignalOff: string[];
export declare const cidWifi: string[];
export declare const cidWindowMaximize: string[];
export declare const cidWindowRestore: string[];
export declare const cidWindow: string[];
export declare const cidWindowMinimize: string[];
export declare const cidWrapText: string[];
export declare const cidXSquare: string[];
export declare const cidYenCircleSlash: string[];
export declare const cidYenCircle: string[];
export declare const cidWifiSignalLock3: string[];
export declare const cidZoomIn: string[];
export declare const cidZoomOut: string[];
export declare const cidXCircle: string[];
export declare const cidZoom: string[];
export declare const cidYenSlash: string[];
export declare const cidWifiSignal4: string[];
export declare const cidGlobeAltLock: string[];
export declare const cidGlobeAlt: string[];